### ISSUE TITLE
AttributeError: 'Plugin' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by XKaguya** [HibiKier/zhenxun_bot#1037]
### 错误截图

![image](https://user-images.githubusercontent.com/96401952/186323967-c1310650-4465-4aa8-95b6-8a6e1d7dbb63.png)
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：wbtop 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：translate 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：nbnhhsh 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：roll 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：query_memo 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：query_role 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：genshin_sign 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：resin_remind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：bind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：query_resource_points 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：material_remind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：black_word 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：pix_show_info 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：one_friend 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：ai 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：almanac 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：draw_card 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：todaybefore 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：nonebot_plugin_emojimix 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：crazy_thursday 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：nonebot_plugin_miragetank 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：tarot 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：cp 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：random_cat_gif 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：nonebot_plugin_petpet 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：abstract 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：avatar 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：nickname 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [WARNING] basic_plugins | 配置文件 模块：zhenxun_plugin_meiriyiju-main 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
08-24 11:12:46 [ERROR] uvicorn | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/zhenxun_bot/basic_plugins/init_plugin_config/__init__.py", line 39, in _
    init_plugins_settings(DATA_PATH)
  File "/home/zhenxun_bot/basic_plugins/init_plugin_config/init_plugins_settings.py", line 39, in init_plugins_settings
    metadata = _plugin.metadata
AttributeError: 'Plugin' object has no attribute 'metadata'

08-24 11:12:46 [ERROR] uvicorn | Application startup failed. Exiting.

### 错误说明

AttributeError: 'Plugin' object has no attribute 'metadata'

**Comment by DeparturesNeko** [comment]
依赖没有及时更新导致的问题，可以先执行一次poetry install
见#1029

**Comment by XKaguya** [comment]
> 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029

![image](https://user-images.githubusercontent.com/96401952/186397759-de70b7c9-6e38-4cf1-87dd-dcc2c07a83a4.png)
执行了也没用，不知道为什么

**Comment by XKaguya** [comment]
> 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029

用的是自动部署脚本部署的真寻，后来手动poetry install了一次也提示同样的效果

**Comment by XKaguya** [comment]
> 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029
尝试了下手动开启bot.py 一样的报错

**Comment by DeparturesNeko** [comment]
> > 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029
> > 尝试了下手动开启bot.py 一样的报错

我不清楚一键部署是不是走poetry的虚拟环境的，install这个方式在另一个issue的反馈也是这样，一键部署的无法用这个方式修复，手动安装的可以

**Comment by XKaguya** [comment]
> > > 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029
> > > 尝试了下手动开启bot.py 一样的报错
> 
> 我不清楚一键部署是不是走poetry的虚拟环境的，install这个方式在另一个issue的反馈也是这样，一键部署的无法用这个方式修复，手动安装的可以

啧，那就比较麻烦了，主要是我自己走了一次poetry环境还是一样的结果，不知道为什么

**Comment by XKaguya** [comment]
> > > 依赖没有及时更新导致的问题，可以先执行一次poetry install 见#1029
> > > 尝试了下手动开启bot.py 一样的报错
> 
> 我不清楚一键部署是不是走poetry的虚拟环境的，install这个方式在另一个issue的反馈也是这样，一键部署的无法用这个方式修复，手动安装的可以

不知道为什么，我又手动安装了一次，依旧不行。
![image](https://user-images.githubusercontent.com/96401952/186491183-f6b31607-2406-43f6-ac5a-5407a437f5b8.png)

实在不行的话考虑退版本了，手头有一个虚拟机的快照

**Comment by yanluoli** [comment]
pip install nb-cli 把nonebot2升到b5

**Comment by XKaguya** [comment]
> pip install nb-cli 把nonebot2升到b5

还是这样，我pip install nb-cli了还是没有metadata

**Comment by XKaguya** [comment]
> pip install nb-cli 把nonebot2升到b5

找到解决办法了，不是pip install nb-cli 而是 pip install nonebot2==2.0.0b5
