### ISSUE TITLE
新电脑按照教程全部弄完后启动出现错误

### ISSUE THREAD

**Issue by Tukimi777** [HibiKier/zhenxun_bot#1047]
### 错误截图
08-28 10:01:20 [INFO] utils | 已成功加载 5 个Cd限制.
08-28 10:01:20 [INFO] utils | 已成功加载 12 个Block限制.
08-28 10:01:20 [INFO] utils | 已成功加载 1 个Count限制.
08-28 10:01:21 [INFO] basic_plugins | 五分钟后将进行配置数据替换，请注意...
08-28 10:01:21 [WARNING] basic_plugins | 插件 upload_image 加载失败...，资源控制未加载...
08-28 10:01:21 [INFO] basic_plugins | 初始化数据完成...
08-28 10:01:21 [INFO] plugins | 开始迁移词条 纯文本 数据
08-28 10:01:21 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\go\zhenxun_bot-0.1.6.3\plugins\word_bank\_data_source.py", line 190, in _
    word_list = await OldWordBank.get_all()
  File "C:\Users\Administrator\Desktop\go\zhenxun_bot-0.1.6.3\plugins\word_bank\_old_model.py", line 19, in get_all
    return await cls.query.gino.all()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\gino\api.py", line 127, in all
    return await self._query.bind.all(self._query, *multiparams, **params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\gino\engine.py", line 740, in all
    return await conn.all(clause, *multiparams, **params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\gino\engine.py", line 316, in all
    return await result.execute()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\gino\dialects\base.py", line 214, in execute
    rows = await cursor.async_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\asyncpg\connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nOTsegEB-py3.9\lib\site-packages\asyncpg\connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedTableError: 关系 "word_bank" 不存在

08-28 10:01:21 [ERROR] uvicorn | Application startup failed. Exiting.
PS C:\Users\Administrator\Desktop\go\zhenxun_bot-0.1.6.3>

**Comment by HibiKier** [comment]
删掉word_bank里的old_model继续
