### ISSUE TITLE
真寻无法启动

### ISSUE THREAD

**Issue by Otakusprpr** [HibiKier/zhenxun_bot#1069]
### 错误截图
![image](https://user-images.githubusercontent.com/106815793/189038013-038d1536-1b19-4fcc-af67-f7342bf4102a.png)

[img]

### 日志截图
09-08 12:56:50 [ERROR] nonebot | Failed to import "parse_bilibili_json"
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
    │       └ <function load_plugins at 0x0000004CD894DDC0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot--1-ZcKUM-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x0000004CD89499D0>
           └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x0000004CD89498B0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>
                  │    │           │         └ 'parse_bilibili_json'
                  │    │           └ 'parse_bilibili_json'
                  │    └ <function PluginManager.load_plugin at 0x0000004CD8949940>
                  └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x0000004CD5C2B160>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.parse_bilibili_json'
           │          └ <function _gcd_import at 0x0000004CD5AC13A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'plugins.parse_bilibili_json' from 'C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\plugins\\p...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\parse_bilibili_json.py", line 17, in <module>
    from bilireq import video

ImportError: cannot import name 'video' from 'bilireq' (C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\bilireq\__init__.py)
09-08 12:56:53 [ERROR] nonebot | Failed to import "word_clouds"
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
    │       └ <function load_plugins at 0x0000004CD894DDC0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot--1-ZcKUM-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x0000004CD89499D0>
           └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x0000004CD89498B0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>
                  │    │           │         └ 'word_clouds'
                  │    │           └ 'word_clouds'
                  │    └ <function PluginManager.load_plugin at 0x0000004CD8949940>
                  └ <nonebot.plugin.manager.PluginManager object at 0x0000004CD9F02AC0>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x0000004CD5C2B160>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.word_clouds'
           │          └ <function _gcd_import at 0x0000004CD5AC13A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'plugins.word_clouds' from 'C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\plugins\\word_clou...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\word_clouds\__init__.py", line 11, in <module>
    from .data_source import draw_word_cloud, get_list_msg

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\plugins\word_clouds\data_source.py", line 10, in <module>
    from wordcloud import WordCloud, ImageColorGenerator

ModuleNotFoundError: No module named 'wordcloud'
09-08 12:56:54 [ERROR] nonebot | Failed to import "ApexLegends-QQ-Robot-master"
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x0000004CD894DDC0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot--1-ZcKUM-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x0000004CD89499D0>
           └ <nonebot.plugin.manager.PluginManager object at 0x0000004CE0EAFC10>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x0000004CD89498B0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x0000004CE0EAFC10>
                  │    │           │         └ 'ApexLegends-QQ-Robot-master'
                  │    │           └ 'ApexLegends-QQ-Robot-master'
                  │    └ <function PluginManager.load_plugin at 0x0000004CD8949940>
                  └ <nonebot.plugin.manager.PluginManager object at 0x0000004CE0EAFC10>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x0000004CD5C2B160>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.ApexLegends-QQ-Robot-master'
           │          └ <function _gcd_import at 0x0000004CD5AC13A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.ApexLegends-QQ-Robot-master' from 'C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot...

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\extensive_plugin\ApexLegends-QQ-Robot-master\__init__.py", line 2, in <module>
    from .utils import *

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\extensive_plugin\ApexLegends-QQ-Robot-master\utils.py", line 10, in <module>
    CONFIG = Config(CONFIG_PATH)
             │      └ 'C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\extensive_plugin\\ApexLegends-QQ-Robot-master\\config...
             └ <class 'extensive_plugin.ApexLegends-QQ-Robot-master.Config.Config'>

  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\extensive_plugin\ApexLegends-QQ-Robot-master\Config.py", line 7, in __init__
    self.__config = json.load(js_f)
    │               │    │    └ <_io.TextIOWrapper name='C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\extensive_plugin\\ApexLegends...
    │               │    └ <function load at 0x0000004CD8433AF0>
    │               └ <module 'json' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py'>
    └ <extensive_plugin.ApexLegends-QQ-Robot-master.Config.Config object at 0x0000004CE7D0B640>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='C:\\Users\\Administrator\\Desktop\\zhenxun_bot-main\\zhenxun_bot-main\\extensive_plugin\\ApexLegends...
           └ <function loads at 0x0000004CD8433B80>

UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 29: illegal multibyte sequence
09-08 12:56:56 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--1-ZcKUM-py3.9\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\basic_plugins\init_plugin_config\__init__.py", line 39, in _
    init_plugins_settings(DATA_PATH)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\zhenxun_bot-main\basic_plugins\init_plugin_config\init_plugins_settings.py", line 39, in init_plugins_settings
    metadata = _plugin.metadata
AttributeError: 'Plugin' object has no attribute 'metadata'

09-08 12:56:56 [ERROR] uvicorn | Application startup failed. Exiting.
[img]

### 错误说明
 
真寻突然无法使用，重启多次都显示以上报错，尝试过下载最新的scripts.py但无济于事，请问该怎么解决？

**Comment by HibiKier** [comment]
更新nb

**Comment by MobiusT** [comment]
> 更新nb

请问大佬nb是什么吖

**Comment by AF5656** [comment]
> > 更新nb
> 
> 请大佬nb是什么吖

看 #1037

**Comment by Otakusprpr** [comment]
> 

更新nb后正常了！感谢！
