### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by AF5656** [HibiKier/zhenxun_bot#1072]
### 错误截图
![截图](https://user-images.githubusercontent.com/72373899/189168401-ff4c97e9-2340-4ee5-a871-93dd766ffd65.png)
### 错误说明
貌似是B站订阅 操作数据库的报错，但是不知道如何解决

**Comment by HibiKier** [comment]
数据库爆了

**Comment by AF5656** [comment]
> 

数据库爆了，是什么意思，细说细说!!!∑(ﾟДﾟノ)ノ

**Comment by KnightKilito** [comment]
一样的情况

**Comment by AF5656** [comment]
> 一样的情况

😭😭

**Comment by AF5656** [comment]
> 数据库爆了

数据库爆了，是什么意思，细说细说!!!∑(ﾟДﾟノ)ノ

**Comment by KnightKilito** [comment]
我重启了一下数据库
```bash
 sudo systemctl restart postgresql
```
然后机器人把早上的信息一直继续处理下去（go-cqhttp那边传来的信息吧），算是恢复正常了，然后又爆炸了
```log
09-15 09:06:16 [ERROR] nonebot | Rule check failed for <Matcher from plugins.word_bank.message_handle, type=message, priority=6, temp=False>.
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 132, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 295, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/rule.py", line 70, in __call__
    results = await asyncio.gather(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/zhenxun_bot/plugins/word_bank/_rule.py", line 33, in check
    if problem and (await WordBank.check(event, problem) is not None):
  File "/home/zhenxun_bot/plugins/word_bank/_model.py", line 237, in check
    if await query.where(
  File "/usr/local/lib/python3.9/dist-packages/gino/api.py", line 137, in first
    return await self._query.bind.first(self._query, *multiparams, **params)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 747, in first
    async with self.acquire(reuse=True) as conn:
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 142, in __aenter__
    self._conn = await self._acquire()
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 702, in _acquire
    await dbapi_conn.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 39, in acquire
    return await self._acquire(timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 74, in _acquire
    self._conn = await self._pool.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/dialects/asyncpg.py", line 229, in acquire
    return await self._pool.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 826, in _acquire
    return await _acquire_impl()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 811, in _acquire_impl
    proxy = await ch.acquire()  # type: PoolConnectionProxy
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 141, in acquire
    await self.connect()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 525, in _get_new_connection
    con = await connect_utils._connect_addr(
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 691, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused
09-15 09:06:16 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
09-15 09:06:16 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 179, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/utils.py", line 138, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/zhenxun_bot/basic_plugins/hooks/auth_hook.py", line 71, in _
    or await BanUser.is_ban(event.user_id)
  File "/home/zhenxun_bot/models/ban_user.py", line 57, in is_ban
    if await cls.check_ban_time(user_qq):
  File "/home/zhenxun_bot/models/ban_user.py", line 40, in check_ban_time
    user = await query.gino.first()
  File "/usr/local/lib/python3.9/dist-packages/gino/api.py", line 137, in first
    return await self._query.bind.first(self._query, *multiparams, **params)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 747, in first
    async with self.acquire(reuse=True) as conn:
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 142, in __aenter__
    self._conn = await self._acquire()
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 702, in _acquire
    await dbapi_conn.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 39, in acquire
    return await self._acquire(timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 74, in _acquire
    self._conn = await self._pool.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/gino/dialects/asyncpg.py", line 229, in acquire
    return await self._pool.acquire(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 826, in _acquire
    return await _acquire_impl()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 811, in _acquire_impl
    proxy = await ch.acquire()  # type: PoolConnectionProxy
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 141, in acquire
    await self.connect()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 525, in _get_new_connection
    con = await connect_utils._connect_addr(
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 691, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "uvloop/loop.pyx", line 2024, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by AF5656** [comment]
> 我重启了一下数据库
> ```bash
>  sudo systemctl restart postgresql
> ```
> 然后机器人把早上的信息一直继续处理下去（go-cqhttp那边传来的信息吧），算是恢复正常了，然后又爆炸了
> ```log
> 09-15 09:06:16 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
> 09-15 09:06:16 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 179, in _run_matcher
>     await asyncio.gather(*coros)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/utils.py", line 138, in run_coro_with_catch
>     return await coro
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
>     return await self.call(**values)
>   File "/home/zhenxun_bot/basic_plugins/hooks/auth_hook.py", line 71, in _
>     or await BanUser.is_ban(event.user_id)
>   File "/home/zhenxun_bot/models/ban_user.py", line 57, in is_ban
>     if await cls.check_ban_time(user_qq):
>   File "/home/zhenxun_bot/models/ban_user.py", line 40, in check_ban_time
>     user = await query.gino.first()
>   File "/usr/local/lib/python3.9/dist-packages/gino/api.py", line 137, in first
>     return await self._query.bind.first(self._query, *multiparams, **params)
>   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 747, in first
>     async with self.acquire(reuse=True) as conn:
>   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 142, in __aenter__
>     self._conn = await self._acquire()
>   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 702, in _acquire
>     await dbapi_conn.acquire(timeout=timeout)
>   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 39, in acquire
>     return await self._acquire(timeout)
>   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 74, in _acquire
>     self._conn = await self._pool.acquire(timeout=timeout)
>   File "/usr/local/lib/python3.9/dist-packages/gino/dialects/asyncpg.py", line 229, in acquire
>     return await self._pool.acquire(timeout=timeout)
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 826, in _acquire
>     return await _acquire_impl()
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 811, in _acquire_impl
>     proxy = await ch.acquire()  # type: PoolConnectionProxy
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 141, in acquire
>     await self.connect()
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 133, in connect
>     self._con = await self._pool._get_new_connection()
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 525, in _get_new_connection
>     con = await connect_utils._connect_addr(
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
>     return await __connect_addr(params, timeout, True, *args)
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
>     tr, pr = await compat.wait_for(connector, timeout=timeout)
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/compat.py", line 66, in wait_for
>     return await asyncio.wait_for(fut, timeout)
>   File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 691, in _create_ssl_connection
>     tr, pr = await loop.create_connection(
>   File "uvloop/loop.pyx", line 2024, in create_connection
>     raise exceptions[0]
>   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
>     await waiter
> ConnectionRefusedError: [Errno 111] Connection refused
> ```

重启了，后面触发一些定时任务，还会这样的

**Comment by KnightKilito** [comment]
> > 我重启了一下数据库
> > ```shell
> >  sudo systemctl restart postgresql
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后机器人把早上的信息一直继续处理下去（go-cqhttp那边传来的信息吧），算是恢复正常了，然后又爆炸了
> > ```
> > 09-15 09:06:16 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
> > 09-15 09:06:16 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
> >     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > > File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 179, in _run_matcher
> >     await asyncio.gather(*coros)
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/utils.py", line 138, in run_coro_with_catch
> >     return await coro
> >   File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
> >     return await self.call(**values)
> >   File "/home/zhenxun_bot/basic_plugins/hooks/auth_hook.py", line 71, in _
> >     or await BanUser.is_ban(event.user_id)
> >   File "/home/zhenxun_bot/models/ban_user.py", line 57, in is_ban
> >     if await cls.check_ban_time(user_qq):
> >   File "/home/zhenxun_bot/models/ban_user.py", line 40, in check_ban_time
> >     user = await query.gino.first()
> >   File "/usr/local/lib/python3.9/dist-packages/gino/api.py", line 137, in first
> >     return await self._query.bind.first(self._query, *multiparams, **params)
> >   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 747, in first
> >     async with self.acquire(reuse=True) as conn:
> >   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 142, in __aenter__
> >     self._conn = await self._acquire()
> >   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 702, in _acquire
> >     await dbapi_conn.acquire(timeout=timeout)
> >   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 39, in acquire
> >     return await self._acquire(timeout)
> >   File "/usr/local/lib/python3.9/dist-packages/gino/engine.py", line 74, in _acquire
> >     self._conn = await self._pool.acquire(timeout=timeout)
> >   File "/usr/local/lib/python3.9/dist-packages/gino/dialects/asyncpg.py", line 229, in acquire
> >     return await self._pool.acquire(timeout=timeout)
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 826, in _acquire
> >     return await _acquire_impl()
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 811, in _acquire_impl
> >     proxy = await ch.acquire()  # type: PoolConnectionProxy
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 141, in acquire
> >     await self.connect()
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 133, in connect
> >     self._con = await self._pool._get_new_connection()
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/pool.py", line 525, in _get_new_connection
> >     con = await connect_utils._connect_addr(
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
> >     return await __connect_addr(params, timeout, True, *args)
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
> >     tr, pr = await compat.wait_for(connector, timeout=timeout)
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/compat.py", line 66, in wait_for
> >     return await asyncio.wait_for(fut, timeout)
> >   File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
> >     return fut.result()
> >   File "/usr/local/lib/python3.9/dist-packages/asyncpg/connect_utils.py", line 691, in _create_ssl_connection
> >     tr, pr = await loop.create_connection(
> >   File "uvloop/loop.pyx", line 2024, in create_connection
> >     raise exceptions[0]
> >   File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
> >     await waiter
> > ConnectionRefusedError: [Errno 111] Connection refused
> > ```
> 
> 重启了，后面触发一些定时任务，还会这样的

是啊

**Comment by KnightKilito** [comment]
我现在只能一直重启数据库一直重启，我删了GitHub sub插件后涉及数据库的都失效，早安晚安还是自动发。

**Comment by AF5656** [comment]
> 我现在只能一直重启数据库一直重启，我删了GitHub sub插件后涉及数据库的都失效，早安晚安还是自动发。

不知道啊 咋办 @HibiKier 佬救救

**Comment by KnightKilito** [comment]
哭死

**Comment by AF5656** [comment]
> 哭死

好兄弟，你的修好没有

**Comment by KnightKilito** [comment]
是存储空间爆了，之前解决了忘了来说一下，进机器人目录里把本地色图删了，把数据库里的色图表清空，就好了
