### ISSUE TITLE
安装完成之后启动报错

### ISSUE THREAD

**Issue by Coisini-H** [HibiKier/zhenxun_bot#1078]
### 错误截图

![QQ图片20220911175021](https://user-images.githubusercontent.com/52484657/189521490-22642b18-306a-4c7f-8bf1-cbfe4983ef9d.png)

![QQ截图20220911175456](https://user-images.githubusercontent.com/52484657/189521589-44e3ca21-2176-413e-8db2-5861322f6f82.jpg)
![QQ截图20220911175531](https://user-images.githubusercontent.com/52484657/189521595-6b48a7a2-1b11-484e-a727-2d1132e5e0f5.jpg)
![QQ截图20220911175556](https://user-images.githubusercontent.com/52484657/189521596-c0ee7db1-5ba0-4e7b-9f4d-1a998b768e42.jpg)

### 错误说明

看不太懂

我本来想加群的问的，发现群的问题不会，也没怎么用过github，希望有人能帮忙解答一下

`
C:\Users\Administrator\Desktop\bot\zhenxun>poetry run python bot.py
09-11 22:40:57 [SUCCESS] nonebot | NoneBot is initializing...
09-11 22:40:57 [INFO] nonebot | Current Env: prod
09-11 22:40:58 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-11 22:40:58 [SUCCESS] nonebot | Succeeded to import "hooks"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "group_handle"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "nickname"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "scripts"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "apscheduler"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "switch_rule"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "admin_config"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "timing_task"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "rule"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "use"
09-11 22:41:00 [SUCCESS] nonebot | Succeeded to import "shop_handle"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "gold"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "buy"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "use"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "my_props"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "shop"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "chat_message"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "chat_history"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "reload_setting"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "exec_sql"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "clear_data"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "manager_group"
09-11 22:41:01 [SUCCESS] nonebot | Succeeded to import "super_cmd"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "ban"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "super_help"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "help"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "broadcast"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "invite_manager"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "plugin_shop"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "admin_help"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "update_info"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "check"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "comments_163"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "jitang"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "cover"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "poetry"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "alapi"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "luxun"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "about"
09-11 22:41:02 [SUCCESS] nonebot | Succeeded to import "epic"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "weather"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "white2black_image"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "wbtop"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "russian"
09-11 22:41:03 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "word_clouds"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "word_handle"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "message_handle"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "word_bank"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "mute"
09-11 22:41:04 [SUCCESS] nonebot | Succeeded to import "dialogue"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "draw_card"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "one_friend"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "fake_msg"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "yiqing"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "coser"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "fudu"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "update_setu"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "send_setu"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "send_setu_"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "black_word"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "search_image"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "search_anime"
09-11 22:41:05 [SUCCESS] nonebot | Succeeded to import "what_anime"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "open_cases"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "move_image"
09-11 22:41:06 [ERROR] nonebot | Failed to import "upload_image"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\zhenxun\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\image_management\__init__.py", line 61, in <module>
    nonebot.load_plugins("plugins/image_management")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\image_management\upload_image\__init__.py", line 60, in <module>
    + "\n- ".join(Config.get_config("image_management", "IMAGE_DIR_LIST")),
TypeError: can only join an iterable
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "delete_image"
09-11 22:41:06 [ERROR] nonebot | Failed to import "send_image"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\zhenxun\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\image_management\__init__.py", line 61, in <module>
    nonebot.load_plugins("plugins/image_management")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\image_management\send_image\__init__.py", line 37, in <module>
    "cmd": ["发送图片"] + Config.get_config("image_management", "IMAGE_DIR_LIST"),
TypeError: can only concatenate list (not "NoneType") to list
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "image_management"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "ai"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "aconfig"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "music"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "poke"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "translate"
09-11 22:41:06 [SUCCESS] nonebot | Succeeded to import "web_ui"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix_update"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "update_picture"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "withdraw"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "quotations"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "my_info"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
09-11 22:41:07 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "bt"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "roll"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "statistics"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "pid_search"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "material_remind"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "almanac"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "query_memo"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "resin_remind"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "query_role"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "mihoyobbs_sign"
09-11 22:41:08 [SUCCESS] nonebot | Succeeded to import "query_memo"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "bind"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "query_user"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "genshin"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "sign_in"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "ban_hook"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "other_hook"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "task_hook"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "auth_hook"
09-11 22:41:09 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
09-11 22:41:09 [SUCCESS] nonebot | Running NoneBot...
09-11 22:41:09 [INFO] uvicorn | Started server process [4180]
09-11 22:41:09 [INFO] uvicorn | Waiting for application startup.
09-11 22:41:09 [INFO] services | Database loaded successfully!
09-11 22:41:09 [INFO] nonebot_plugin_apscheduler | Scheduler Started
09-11 22:41:10 [INFO] basic_plugins | 已成功加载 64 个非限制插件.
09-11 22:41:10 [INFO] utils | 已成功加载 5 个Cd限制.
09-11 22:41:10 [INFO] utils | 已成功加载 12 个Block限制.
09-11 22:41:10 [INFO] utils | 已成功加载 1 个Count限制.
09-11 22:41:10 [INFO] basic_plugins | 五分钟后将进行配置数据替换，请注意...
09-11 22:41:10 [WARNING] basic_plugins | 插件 upload_image 加载失败...，资源控制未加载...
09-11 22:41:10 [INFO] basic_plugins | 初始化数据完成...
09-11 22:41:10 [INFO] plugins | 开始迁移词条 纯文本 数据
09-11 22:41:10 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\word_bank\_data_source.py", line 190, in _
    word_list = await OldWordBank.get_all()
  File "C:\Users\Administrator\Desktop\bot\zhenxun\plugins\word_bank\_old_model.py", line 19, in get_all
    return await cls.query.gino.all()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\gino\api.py", line 127, in all
    return await self._query.bind.all(self._query, *multiparams, **params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\gino\engine.py", line 740, in all
    return await conn.all(clause, *multiparams, **params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\gino\engine.py", line 316, in all
    return await result.execute()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\gino\dialects\base.py", line 214, in execute
    rows = await cursor.async_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\asyncpg\connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-0xMhanga-py3.9\lib\site-packages\asyncpg\connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedTableError: 关系 "word_bank" 不存在

09-11 22:41:10 [ERROR] uvicorn | Application startup failed. Exiting.

C:\Users\Administrator\Desktop\bot\zhenxun>`

**Comment by wulikanhua778899** [comment]
我一开始直接下载release，然后解压运行，也遇到这个错误了。用git clone拉取库运行就好了。
