### ISSUE TITLE
chromium启动失败

### ISSUE THREAD

**Issue by Nthing734** [HibiKier/zhenxun_bot#1080]
centos7.9

> 09-12 15:14:12 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-12 15:14:12 [WARNING] apscheduler | Run time of job "_ (trigger: interval[0:00:30], next run at: 2022-09-12 15:14:27 CST)" was missed by 0:00:14.201867
09-12 15:14:43 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 38, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 55, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1005/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-lhXtYr --remote-debugging-pipe --no-startup-window
<launched> pid=48742
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 59, in get_browser
    return _browser or await init(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 41, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 55, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1005/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-XAY36H --remote-debugging-pipe --no-startup-window
<launched> pid=48921

**Comment by HibiKier** [comment]
超时了
