### ISSUE TITLE
真寻bot问答插件调用时报错

### ISSUE THREAD

**Issue by Evilshadowruin** [HibiKier/zhenxun_bot#1132]
### 错误截图
机器人 没有任何报错提示 提示添加词条成功 但没有实际生效，我查询了历史的反馈找到了一个九月的同类型报错信息。
已一并提交给nonebot  ，目前该问题还未解决   
这是 那边的链接 ：https://github.com/nonebot/adapter-onebot/issues/32 
[img]

### 日志截图
10-12 16:28:30 [INFO] plugins | (USER 1979318585, GROUP private) 添加词条 修改数据 成功！
10-12 16:28:30 [INFO] nonebot | Matcher <Matcher from plugins.word_bank.word_handle, type=message, priority=5, temp=False> running complete
10-12 16:28:30 [ERROR] nonebot | Error when running RunPostProcessors
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\message.py", line 222, in _run_matcher
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
    return await coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 188, in solve
    await checker._solve(**params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\internal\params.py", line 210, in _solve
    return check_field_type(field, event)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\dependencies\utils.py", line 51, in check_field_type
    _, errs_ = field.validate(value, {}, loc=())
  File "pydantic\fields.py", line 857, in pydantic.fields.ModelField.validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "pydantic\fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "pydantic\fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "pydantic\class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
    return lambda cls, v, values, field, config: validator(v)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\internal\adapter\event.py", line 23, in validate
    raise TypeError(f"{value} is incompatible with Event type {cls}")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\internal\adapter\event.py", line 42, in __str__
    return f"[{self.get_event_name()}]: {self.get_event_description()}"
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 185, in get_event_description
    + "".join(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Y33bbWyJ-py3.9\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 188, in <lambda>
    if x.is_text()
AttributeError: 'str' object has no attribute 'is_text'
[img]

### 错误说明
词条添加提示成功缺并不生效。

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/195987384-5fbb9143-cb94-4055-adb0-6cd46faea6e8.png)
无法复现？

**Comment by Evilshadowruin** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/195987384-5fbb9143-cb94-4055-adb0-6cd46faea6e8.png)无法复现？

固定触发 很奇怪  无论是重启过真寻 还是重新安装过环境

**Comment by Evilshadowruin** [comment]
![K}V(19E@22N0{0JCY%7(CXK](https://user-images.githubusercontent.com/114408306/195987914-793b3f9b-8ff0-4ba8-8627-511056d68d0f.png)
我可以尝试一下 重新替换这个 问答插件的全部文件  看看

**Comment by Evilshadowruin** [comment]
替换文件 重新载入配置后还是一样 有点头疼 不知道具体原因

**Comment by HibiKier** [comment]
有第三方插件吗，先别加载第三方插件试试

**Comment by Evilshadowruin** [comment]
> 有第三方插件吗，先别加载第三方插件试试

没有第三方插件 很奇怪这个问题 最开始的时候 就是真寻的原始包 部署后就这样了，后面才有调试过其他BOT ，也许模块差异导致的但是如果是实在解决不了也米有办法了。

**Comment by HibiKier** [comment]
不知道，试试更新nonebot2
