### ISSUE TITLE
b站订阅和解析插件在启动时无法import，已更新至最新版本的代码

### ISSUE THREAD

**Issue by Judp28** [HibiKier/zhenxun_bot#1160]
### 错误截图
10-29 16:06:30 [ERROR] nonebot | Failed to import "bilibili_sub"
Traceback (most recent call last):
  File "C:\zhenxun_bot-main\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_pl
ugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin

    module = importlib.import_module(
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in impor
t_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module

    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\zhenxun_bot-main\plugins\bilibili_sub\__init__.py", line 7, in <modul
e>
    from .data_source import (
  File "C:\zhenxun_bot-main\plugins\bilibili_sub\data_source.py", line 12, in <m
odule>
    from bilireq.user import get_videos
 ImportError: cannot import name 'video' from 'bilireq' (C:\Users\Administrator\A
ppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-py3.9\lib\site-packages\bili
req_init_.py)
### 错误说明

奇怪的是，我从backup文件夹里提取九月份版本的代码可以正常使用

**Comment by Judp28** [comment]
bilibili phase的报错类似
10-29 16:06:31 [ERROR] nonebot | Failed to import "parse_bilibili_json"
Traceback (most recent call last):
  File "C:\zhenxun_bot-main\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_pl
ugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin

    module = importlib.import_module(
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in impor
t_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module

    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\zhenxun_bot-main\plugins\parse_bilibili_json.py", line 19, in <module
>
    from bilireq import video
ImportError: cannot import name 'video' from 'bilireq' (C:\Users\Administrator\A
ppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-py3.9\lib\site-packages\bili
req\__init__.py)

**Comment by HibiKier** [comment]
更新bilireq
