### ISSUE TITLE
webui无法获取群组列表

### ISSUE THREAD

**Issue by Disappear9** [HibiKier/zhenxun_bot#1195]
### 错误截图

![img](https://cdn.staticaly.com/gh/Disappear9/image-hosting@master/20221125/Snipaste_2022-11-25_14-29-39.3siy1l7vetw0.png)

### 日志截图

webui打开群组列表：
```
11-25 14:29:32 [INFO] uvicorn | 172.20.0.5:43496 - "GET /webui/group HTTP/1.0" 500
11-25 14:29:32 [ERROR] uvicorn | Exception in ASGI application
Traceback (most recent call last):
  File "/bot/bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/bot/plugins/web_ui/api/group.py", line 22, in _
    for group_id in group_data["group_manager"]:
TypeError: 'BaseData' object is not subscriptable
```
### 错误说明

机器人无回复消息，且webui无法获取群组列表

**Comment by MWTJC** [comment]
，报错现象及日志位置一致，前来报到。
运行环境：WinServer2022+Python3.8
真寻版本：1.6.5+11月17日手动下载zip源码覆盖basic_plugins和plugins文件夹

附图：
![image](https://user-images.githubusercontent.com/74529082/204197988-a4a17ffa-5510-4841-a4c5-5c739e246326.png)

**Comment by HibiKier** [comment]
994484f3b0ad5ca302b8b3d9a0c47c48b15549d3
