### ISSUE TITLE
重载配置失效

### ISSUE THREAD

**Issue by 917017420** [HibiKier/zhenxun_bot#120]
02-17 15:06:12 [ERROR] nonebot | Running matcher <Matcher from reload_setting, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 21, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "basic_plugins/super_cmd/reload_setting.py", line 59, in _
    Config.reload()
AttributeError: 'ConfigsManager' object has no attribute 'reload'

**Comment by HibiKier** [comment]
configs/utils忘记更新了，将在下次更新补上
