### ISSUE TITLE
从webui更改插件设置导致bot重载时不能正常加载插件及个人排查说明

### ISSUE THREAD

**Issue by MWTJC** [HibiKier/zhenxun_bot#1200]
### 错误截图

![image](https://user-images.githubusercontent.com/74529082/204359991-471bd5d7-a824-4e5c-aba4-7206bcb8e62a.png)

![image](https://user-images.githubusercontent.com/74529082/204359708-d64877c5-313d-4e36-95de-f2b3e91f6d04.png)

### 日志

```
11-29 03:06:10 [ERROR] nonebot | Failed to import "reload_setting"
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    nonebot.load_plugins("basic_plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\BOT\zhenxun_bot\basic_plugins\super_cmd\__init__.py", line 4, in <module>
    nonebot.load_plugins('basic_plugins/super_cmd')
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\BOT\zhenxun_bot\basic_plugins\super_cmd\reload_setting.py", line 4, in <module>
    from utils.manager import (
  File "F:\BOT\zhenxun_bot\utils\manager\__init__.py", line 34, in <module>
    plugins2settings_manager: Optional[Plugins2settingsManager] = Plugins2settingsManager(
  File "F:\BOT\zhenxun_bot\utils\manager\plugins2settings_manager.py", line 18, in __init__
    self.__load_file()
  File "F:\BOT\zhenxun_bot\utils\manager\plugins2settings_manager.py", line 133, in __load_file
    self._data[k] = PluginSetting.parse_obj(v)
  File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for PluginSetting
cmd
  value is not a valid list (type=type_error.list)
```

### 错误说明

偶然发现一次bot重启报错如上，大多数插件不能加载且报错相同，报错片段之一见日志说明。

经排查发现通过webui更改插件设置会导致位于：真寻bot\data\configs的plugins2settings.yaml文件格式改变，进而导致bot重载时不能正常加载插件，更改示意图及格式对比图示见错误截图。

webui为0.1.0.4版，nginx+dist文件夹运行。

**Comment by HibiKier** [comment]
994484f3b0ad5ca302b8b3d9a0c47c48b15549d3

**Comment by MWTJC** [comment]
感谢大佬修复，手动覆盖之后实测已经解决。
