### ISSUE TITLE
访问webui后bot运行出错

### ISSUE THREAD

**Issue by Disappear9** [HibiKier/zhenxun_bot#1210]
### 日志
```

！！！正常运行 ！！！

12-13 17:42:15 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message  from @[群:] "关闭早晚安"
12-13 17:42:15 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
12-13 17:42:15 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
12-13 17:42:15 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
12-13 17:42:15 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
12-13 17:42:15 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
12-13 17:42:15 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
12-13 17:42:15 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
12-13 17:42:15 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
12-13 17:42:15 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.admin_bot_manage.switch_rule)
12-13 17:42:16 [INFO] switch_rule | USER  GROUP  使用群功能管理命令 关闭早晚安
12-13 17:42:16 [INFO] nonebot | Matcher(type='message', module=basic_plugins.admin_bot_manage.switch_rule) running complete

！！！ 使用webui访问任意地址 ！！！

12-13 17:42:45 [INFO] uvicorn | 172.18.0.4:38294 - "POST /webui/auth HTTP/1.0" 200
12-13 17:42:45 [INFO] uvicorn | 172.18.0.4:38302 - "POST /webui/auth HTTP/1.0" 200
12-13 17:42:45 [INFO] uvicorn | 172.18.0.4:38312 - "GET /webui/plugins?type_=normal HTTP/1.0" 200
12-13 17:42:48 [INFO] uvicorn | 172.18.0.4:38318 - "POST /webui/auth HTTP/1.0" 200
12-13 17:42:48 [INFO] uvicorn | 172.18.0.4:38334 - "GET /webui/plugins?type_=normal HTTP/1.0" 200

！！！向bot发送任意消息！！！

12-13 17:43:31 [SUCCESS] nonebot | OneBot V11  | [message.private.friend]: Message  from  "关于"
12-13 17:43:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
12-13 17:43:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
12-13 17:43:31 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/bot/plugins/web_ui/__init__.py", line 27, in _
    plugins2settings_manager.set_module_data(
  File "/bot/utils/manager/data_class.py", line 43, in set_module_data
    self._data[module][key] = value
TypeError: 'PluginSetting' object does not support item assignment
12-13 17:43:31 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/bot/plugins/web_ui/__init__.py", line 27, in _
    plugins2settings_manager.set_module_data(
  File "/bot/utils/manager/data_class.py", line 43, in set_module_data
    self._data[module][key] = value
TypeError: 'PluginSetting' object does not support item assignment
12-13 17:43:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
12-13 17:43:31 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/bot/plugins/web_ui/__init__.py", line 27, in _
    plugins2settings_manager.set_module_data(
  File "/bot/utils/manager/data_class.py", line 43, in set_module_data
    self._data[module][key] = value
TypeError: 'PluginSetting' object does not support item assignment
12-13 17:43:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.about)
12-13 17:43:31 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/bot/plugins/web_ui/__init__.py", line 27, in _
    plugins2settings_manager.set_module_data(
  File "/bot/utils/manager/data_class.py", line 43, in set_module_data
    self._data[module][key] = value
TypeError: 'PluginSetting' object does not support item assignment
12-13 17:43:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
12-13 17:43:31 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/bot/plugins/web_ui/__init__.py", line 27, in _
    plugins2settings_manager.set_module_data(
  File "/bot/utils/manager/data_class.py", line 43, in set_module_data
    self._data[module][key] = value
TypeError: 'PluginSetting' object does not support item assignment
```

### 错误说明

https://github.com/HibiKier/zhenxun_bot/blob/b9d08855d013cdaaa006d968115421acc0d57f7d/plugins/web_ui/__init__.py#L19

😂目前只要不访问webui就没事

**Comment by HibiKier** [comment]
更新代码

**Comment by Disappear9** [comment]
> 更新代码

已经是master上的版本了

**Comment by HibiKier** [comment]
0dc11b7edb693d36593cdbf6e2946d4d48b8be10
