### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by xingling2020** [HibiKier/zhenxun_bot#1220]
### 错误截图

![image](https://user-images.githubusercontent.com/118526814/209131259-374c2435-6106-4e26-9dad-225c95d26c73.png)
`Traceback (most recent call last):
  File "E:\qqbot\zhbot\zhenxun_bot\bot.py", line 13, in <module>
    nonebot.load_plugins("basic_plugins")
  File "E:\qqbot\zhbot\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "E:\qqbot\zhbot\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "E:\qqbot\zhbot\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\qqbot\zhbot\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "E:\qqbot\zhbot\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\qqbot\zhbot\zhenxun_bot\basic_plugins\help\__init__.py", line 12, in <module>
    from ._data_source import create_help_img, get_plugin_help
  File "E:\qqbot\zhbot\zhenxun_bot\basic_plugins\help\_data_source.py", line 2, in <module>
    from ._utils import HelpImageBuild
  File "E:\qqbot\zhbot\zhenxun_bot\basic_plugins\help\_utils.py", line 2, in <module>
    from nonebot_plugin_htmlrender import template_to_pic
ModuleNotFoundError: No module named 'nonebot_plugin_htmlrender'
`

### 日志截图

![image](https://user-images.githubusercontent.com/118526814/209131344-66f93929-82e2-4895-8505-48ef6c83c77a.png)

### 错误说明

菜单组件无法正常工作

**Comment by xingling2020** [comment]
已更新依赖，并重置了数据库，但该问题依旧存在

**Comment by HibiKier** [comment]
83dc29a5622a4358088496597cbd5c6966e89b87 用最新的toml

**Comment by xingling2020** [comment]
已解觉，感谢
