### ISSUE TITLE
导入插件失败

### ISSUE THREAD

**Issue by Yql66** [HibiKier/zhenxun_bot#1229]
### 日志截图

![Q8S OZJ3}P15OI### 系统版本：Ubuntu 20.04
### 日志截图

[img]
G9`}ER](https://user-images.githubusercontent.com/111969738/211191116-a5f47bc1-4962-41b1-aa69-58312fa1763e.png)

### 错误说明

发生了xx错误...

**Comment by Yql66** [comment]
01-08 18:21:07 [ERROR] nonebot | Failed to import "zhenxun_plugin_DouyinShare"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 39
, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\extensive_plugin\zhenxun_plugin_DouyinShare\__init__.py", lin
e 106
    if res.['code'] != 201:
           ^
SyntaxError: invalid syntax

**Comment by HibiKier** [comment]
zhenxun_plugin_DouyinShare插件问题
