### ISSUE TITLE
疫情模块问题

### ISSUE THREAD

**Issue by sakuno214** [HibiKier/zhenxun_bot#123]
02-22 10:20:03 [ERROR] nonebot | Running matcher <Matcher from plugins.yiqing, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    nonebot.run()
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/ubuntu/zhenxun_bot/plugins/yiqing/__init__.py", line 42, in _
    result = await get_yiqing_data(msg)
  File "/home/ubuntu/zhenxun_bot/plugins/yiqing/data_source.py", line 73, in get_yiqing_data
    return image(b64=(await text2image(
  File "/home/ubuntu/zhenxun_bot/utils/image_utils.py", line 1420, in text2image
    A = BuildImage(
  File "/home/ubuntu/zhenxun_bot/utils/image_utils.py", line 182, in __init__
    self.font = ImageFont.truetype(str(FONT_PATH / font), int(font_size))
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 844, in truetype
    return freetype(font)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 841, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/ubuntu/zhenxun_bot/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource

不知道什么原因造成的，是因为我从0.0.6.1直接升级还有更新了nb2beta2的原因吗

**Comment by HibiKier** [comment]
很早前的版本升级看看这个https://github.com/HibiKier/zhenxun_bot/issues/112
