### ISSUE TITLE
在@bot与私聊时bot出现奇怪报错

### ISSUE THREAD

**Issue by hatsusakuramiku** [HibiKier/zhenxun_bot#1232]
### 错误说明
在群聊里@bot与私聊时出现奇怪报错，bot能对部分指令（如’帮助‘等）做出正确回复，不过在私聊里无法执行‘重启’ ‘exec’ ‘检查更新真寻’等命令

### 错误截图
![截图](https://user-images.githubusercontent.com/112763271/212033006-2bb38597-9a60-4f7f-a45b-629fc6634f0d.png)

### 以下是日志内容

01-12 17:12:35 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7eff1b17f310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7eff1c3b4ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7eff199a0670>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7eff199a0820>
    └ <uvicorn.server.Server object at 0x7eff00573400>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7eff199a08b0>
           │       │   └ <uvicorn.server.Server object at 0x7eff00573400>
           │       └ <function run at 0x7eff1c00a040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7eff00564a40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x7efeffe050c0>, <coroutine object run_coro_with_catch at 0x7efeffe051c0>, <corouti...
          │       └ <function gather at 0x7eff1bb4ae50>
          └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7efeffe05440>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1825822752'), 'matcher': Matcher(type='message', module=plugins.black_word), 'event':...
                 │    │             │         │    │    └ <function _ at 0x7eff0127ad30>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7eff1c133b80>

  File "/root/zhenxun_bot/plugins/black_word/__init__.py", line 167, in _
    if await black_word_manager.check(user_id, group_id, msg) and Config.get_config(
             │                  │     │        │         │        │      └ <function ConfigsManager.get_config at 0x7eff1ba303a0>
             │                  │     │        │         │        └ <configs.utils.ConfigsManager object at 0x7eff1a086970>
             │                  │     │        │         └ '贴贴'
             │                  │     │        └ 437775955
             │                  │     └ 1827723098
             │                  └ <function BlackWordManager.check at 0x7eff01353a60>
             └ <plugins.black_word.utils.BlackWordManager object at 0x7eff012e0b50>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 100, in check
    await send_msg(
          └ <function send_msg at 0x7eff0133cee0>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 294, in send_msg
    user_id = int(list(bot.config.superusers)[0])
                       │   └ <property object at 0x7eff1b3cea40>
                       └ Bot(type='OneBot V11', self_id='1825822752')

ValueError: invalid literal for int() with base 10: ''
01-12 17:23:30 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"
Traceback (most recent call last):

  File "bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x7f27626b0430>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f27626a8ca0>
           └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
                  │    │           │         │       │    └ <property object at 0x7f27626a93b0>
                  │    │           │         │       └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
                  │    │           │         └ 'nonebot-plugin-chatgpt'
                  │    │           └ 'nonebot-plugin-chatgpt'
                  │    └ <function PluginManager.load_plugin at 0x7f27626a8c10>
                  └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f2763bcc8b0>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.nonebot-plugin-chatgpt'
           │          └ <function _gcd_import at 0x7f2763ce9430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.nonebot-plugin-chatgpt' from '/root/zhenxun_bot/extensive_plugin/nonebot-plugin-chatgpt/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/root/zhenxun_bot/extensive_plugin/nonebot-plugin-chatgpt/__init__.py", line 22, in <module>
    require("nonebot_plugin_htmlrender")
    └ <function require at 0x7f2762633040>

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 165, in require
    plugin = load_plugin(name)
             │           └ 'nonebot_plugin_htmlrender'
             └ <function load_plugin at 0x7f27626ab820>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
           │       │           └ 'nonebot_plugin_htmlrender'
           │       └ <function PluginManager.load_plugin at 0x7f27626a8c10>
           └ PluginManager(plugins={'nonebot_plugin_htmlrender'}, search_path=set())
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 155, in load_plugin
    raise RuntimeError(

RuntimeError: Module nonebot_plugin_htmlrender is not loaded as a plugin! Make sure not to import it before loading.
01-12 17:23:30 [ERROR] nonebot | Failed to import "nonebot-plugin-chatgpt"
Traceback (most recent call last):

  File "bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x7f27626b0430>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f27626a8ca0>
           └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
                  │    │           │         │       │    └ <property object at 0x7f27626a93b0>
                  │    │           │         │       └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
                  │    │           │         └ 'nonebot-plugin-chatgpt'
                  │    │           └ 'nonebot-plugin-chatgpt'
                  │    └ <function PluginManager.load_plugin at 0x7f27626a8c10>
                  └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f2763bcc8b0>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.nonebot-plugin-chatgpt'
           │          └ <function _gcd_import at 0x7f2763ce9430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.nonebot-plugin-chatgpt' from '/root/zhenxun_bot/extensive_plugin/nonebot-plugin-chatgpt/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/root/zhenxun_bot/extensive_plugin/nonebot-plugin-chatgpt/__init__.py", line 22, in <module>
    require("nonebot_plugin_htmlrender")
    └ <function require at 0x7f2762633040>

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 167, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')

RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!
01-12 17:28:09 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f8d8f65e310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f8d90894ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f8d8de81670>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f8d8de81820>
    └ <uvicorn.server.Server object at 0x7f8d749f1a00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f8d8de818b0>
           │       │   └ <uvicorn.server.Server object at 0x7f8d749f1a00>
           │       └ <function run at 0x7f8d904ea040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8d749e4ac0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x7f8d60dde0c0>, <coroutine object run_coro_with_catch at 0x7f8d60dde940>, <corouti...
          │       └ <function gather at 0x7f8d9002ae50>
          └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f8d60ddedc0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1825822752'), 'matcher': Matcher(type='message', module=plugins.black_word), 'event':...
                 │    │             │         │    │    └ <function _ at 0x7f8d786363a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f8d90613b80>

  File "/root/zhenxun_bot/plugins/black_word/__init__.py", line 167, in _
    if await black_word_manager.check(user_id, group_id, msg) and Config.get_config(
             │                  │     │        │         │        │      └ <function ConfigsManager.get_config at 0x7f8d8ff103a0>
             │                  │     │        │         │        └ <configs.utils.ConfigsManager object at 0x7f8d8e565940>
             │                  │     │        │         └ 'exec UPDATE "bag_users" SET gold=(520) WHERE user_qq=(2835321240) AND group_id=(579137415)'
             │                  │     │        └ None
             │                  │     └ 792408751
             │                  └ <function BlackWordManager.check at 0x7f8d78642940>
             └ <plugins.black_word.utils.BlackWordManager object at 0x7f8d78619850>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 100, in check
    await send_msg(
          └ <function send_msg at 0x7f8d78642b80>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 294, in send_msg
    user_id = int(list(bot.config.superusers)[0])
                       │   └ <property object at 0x7f8d8f8afa90>
                       └ Bot(type='OneBot V11', self_id='1825822752')

ValueError: invalid literal for int() with base 10: ''
01-12 17:28:43 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f8d8f65e310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f8d90894ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f8d8de81670>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f8d8de81820>
    └ <uvicorn.server.Server object at 0x7f8d749f1a00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f8d8de818b0>
           │       │   └ <uvicorn.server.Server object at 0x7f8d749f1a00>
           │       └ <function run at 0x7f8d904ea040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8d749e4ac0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x7f8d5322b0c0>, <coroutine object run_coro_with_catch at 0x7f8d5322b340>, <corouti...
          │       └ <function gather at 0x7f8d9002ae50>
          └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f8d5322bdc0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1825822752'), 'matcher': Matcher(type='message', module=plugins.black_word), 'event':...
                 │    │             │         │    │    └ <function _ at 0x7f8d786363a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f8d90613b80>

  File "/root/zhenxun_bot/plugins/black_word/__init__.py", line 167, in _
    if await black_word_manager.check(user_id, group_id, msg) and Config.get_config(
             │                  │     │        │         │        │      └ <function ConfigsManager.get_config at 0x7f8d8ff103a0>
             │                  │     │        │         │        └ <configs.utils.ConfigsManager object at 0x7f8d8e565940>
             │                  │     │        │         └ '帮助'
             │                  │     │        └ 579137415
             │                  │     └ 792408751
             │                  └ <function BlackWordManager.check at 0x7f8d78642940>
             └ <plugins.black_word.utils.BlackWordManager object at 0x7f8d78619850>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 100, in check
    await send_msg(
          └ <function send_msg at 0x7f8d78642b80>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 294, in send_msg
    user_id = int(list(bot.config.superusers)[0])
                       │   └ <property object at 0x7f8d8f8afa90>
                       └ Bot(type='OneBot V11', self_id='1825822752')

ValueError: invalid literal for int() with base 10: ''
01-12 17:29:40 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f8d8f65e310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f8d90894ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f8d8de81670>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f8d8de81820>
    └ <uvicorn.server.Server object at 0x7f8d749f1a00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f8d8de818b0>
           │       │   └ <uvicorn.server.Server object at 0x7f8d749f1a00>
           │       └ <function run at 0x7f8d904ea040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8d749e4ac0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x7f8d5327d840>, <coroutine object run_coro_with_catch at 0x7f8d5327d140>, <corouti...
          │       └ <function gather at 0x7f8d9002ae50>
          └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f8d60e5fac0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1825822752'), 'matcher': Matcher(type='message', module=plugins.black_word), 'event':...
                 │    │             │         │    │    └ <function _ at 0x7f8d786363a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f8d90613b80>

  File "/root/zhenxun_bot/plugins/black_word/__init__.py", line 167, in _
    if await black_word_manager.check(user_id, group_id, msg) and Config.get_config(
             │                  │     │        │         │        │      └ <function ConfigsManager.get_config at 0x7f8d8ff103a0>
             │                  │     │        │         │        └ <configs.utils.ConfigsManager object at 0x7f8d8e565940>
             │                  │     │        │         └ 'test'
             │                  │     │        └ 579137415
             │                  │     └ 792408751
             │                  └ <function BlackWordManager.check at 0x7f8d78642940>
             └ <plugins.black_word.utils.BlackWordManager object at 0x7f8d78619850>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 100, in check
    await send_msg(
          └ <function send_msg at 0x7f8d78642b80>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 294, in send_msg
    user_id = int(list(bot.config.superusers)[0])
                       │   └ <property object at 0x7f8d8f8afa90>
                       └ Bot(type='OneBot V11', self_id='1825822752')

ValueError: invalid literal for int() with base 10: ''
01-12 17:31:09 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f8d8f65e310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f8d90894ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f8d8de81670>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f8d8de81820>
    └ <uvicorn.server.Server object at 0x7f8d749f1a00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f8d8de818b0>
           │       │   └ <uvicorn.server.Server object at 0x7f8d749f1a00>
           │       └ <function run at 0x7f8d904ea040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8d749e4ac0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x7f8d60e504c0>, <coroutine object run_coro_with_catch at 0x7f8d60e508c0>, <corouti...
          │       └ <function gather at 0x7f8d9002ae50>
          └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f8d60e50140>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='1825822752'), 'matcher': Matcher(type='message', module=plugins.black_word), 'event':...
                 │    │             │         │    │    └ <function _ at 0x7f8d786363a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f8d90613b80>

  File "/root/zhenxun_bot/plugins/black_word/__init__.py", line 167, in _
    if await black_word_manager.check(user_id, group_id, msg) and Config.get_config(
             │                  │     │        │         │        │      └ <function ConfigsManager.get_config at 0x7f8d8ff103a0>
             │                  │     │        │         │        └ <configs.utils.ConfigsManager object at 0x7f8d8e565940>
             │                  │     │        │         └ '自我介绍'
             │                  │     │        └ 579137415
             │                  │     └ 792408751
             │                  └ <function BlackWordManager.check at 0x7f8d78642940>
             └ <plugins.black_word.utils.BlackWordManager object at 0x7f8d78619850>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 100, in check
    await send_msg(
          └ <function send_msg at 0x7f8d78642b80>

  File "/root/zhenxun_bot/plugins/black_word/utils.py", line 294, in send_msg
    user_id = int(list(bot.config.superusers)[0])
                       │   └ <property object at 0x7f8d8f8afa90>
                       └ Bot(type='OneBot V11', self_id='1825822752')

ValueError: invalid literal for int() with base 10: ''

**Comment by HibiKier** [comment]
你没有设置超级用户
