### ISSUE TITLE
指定的网络名不再可用

### ISSUE THREAD

**Issue by ReYuawa** [HibiKier/zhenxun_bot#1241]
系统版本：win11
 真寻版本：0.1.6.6
错误说明
在输入python bot.py后显示 "C:\Users\27684\.conda\envs\qqbot\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\27684\.conda\envs\qqbot\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "C:\Users\27684\.conda\envs\qqbot\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\27684\.conda\envs\qqbot\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\win10备份\zhenxun_bot-main\zhenxun_bot-main\services\db_context.py", line 19, in init
    await db.set_bind(i_bind)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\pool.py", line 409, in _async__init__
    await self._initialize()
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\pool.py", line 437, in _initialize
    await first_ch.connect()
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\pool.py", line 129, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\pool.py", line 507, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\asyncpg\compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "C:\Users\27684\.conda\envs\qqbot\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\27684\.conda\envs\qqbot\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "E:\win10备份\zhenxun_bot-main\zhenxun_bot-main\services\db_context.py", line 23, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.ConnectionDoesNotExistError'>: connection was closed in the middle of operation

01-24 22:26:51 [ERROR] uvicorn | Application startup failed. Exiting.
![Desktop Screenshot 2023 01 24 - 22 52 39 07](https://user-images.githubusercontent.com/89035082/214327715-f3a49b18-0265-4ee3-bc61-15ff86522c9f.png)
config
![Desktop Screenshot 2023 01 24 - 22 56 05 03](https://user-images.githubusercontent.com/89035082/214328044-9336ad1d-43cd-4f6f-b6f7-5e962166617d.png)
数据库
![Desktop Screenshot 2023 01 24 - 22 56 40 90](https://user-images.githubusercontent.com/89035082/214328202-92d581ba-6c1e-4be1-a551-9ae0857b438c.png)

**Comment by HibiKier** [comment]
你密码是对的吗

**Comment by ReYuawa** [comment]
> 

密码是zhenxun_bot 是对的

**Comment by ReYuawa** [comment]
> 你密码是对的吗

密码是zhenxun_bot 是对的

**Comment by kswag72** [comment]
相同问题在windows sever 2022

**Comment by NathanSummer** [comment]
要不你们试试用Linux？目前来说没有遇到问题

**Comment by HibiKier** [comment]
这个错误一般是数据库没创建，但看你好像是创建 了
