### ISSUE TITLE
启动时报错[ERROR] uvicorn | Application startup failed. Exiting.

### ISSUE THREAD

**Issue by BingBingBro** [HibiKier/zhenxun_bot#1245]
用的conda构建环境，重试几次还是这样
01-28 13:40:21 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\ProgramData\miniconda3\envs\qqbot\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "D:\ProgramData\miniconda3\envs\qqbot\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "D:\ProgramData\miniconda3\envs\qqbot\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "D:\zhenxun_bot\zhenxun_bot-main\basic_plugins\init_plugin_config\__init__.py", line 44, in _
    init_plugins_config()
  File "D:\zhenxun_bot\zhenxun_bot-main\basic_plugins\init_plugin_config\init_plugins_config.py", line 61, in init_plugins_config
    default_value=plugin_configs[key]["default_value"],
  File "D:\ProgramData\miniconda3\envs\qqbot\lib\site-packages\ruamel\yaml\comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'default_value'

01-28 13:40:21 [ERROR] uvicorn | Application startup failed. Exiting.
![屏幕截图 2023-01-28 134257](https://user-images.githubusercontent.com/123795008/215248506-59968702-a031-4132-96f2-90364ea55ed2.png)

**Comment by HibiKier** [comment]
配置文件写坏了，保留config.yaml，删除data/configs/plugin2config.yaml

**Comment by BingBingBro** [comment]
> 配置文件写坏了，保留config.yaml，删除data/configs/plugin2config.yaml

可以用了，谢谢
