### ISSUE TITLE
使用Docker启动时循环报错

### ISSUE THREAD

**Issue by narwhrl** [HibiKier/zhenxun_bot#1259]
### 错误截图

![image](https://user-images.githubusercontent.com/78220282/218300601-0410ecf1-cdc2-4f84-ba7b-44b418ba6c7d.png)

### 日志截图

```
ZhenXun-bot  | 02-12 16:22:36 [SUCCESS] nonebot | NoneBot is initializing...
ZhenXun-bot  | Traceback (most recent call last):
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/config.py", line 78, in __call__
ZhenXun-bot  |     env_val = settings.__config__.json_loads(env_val)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
ZhenXun-bot  |     return _default_decoder.decode(s)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
ZhenXun-bot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
ZhenXun-bot  |   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
ZhenXun-bot  |     obj, end = self.scan_once(s, idx)
ZhenXun-bot  | json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2 (char 1)
ZhenXun-bot  | 
ZhenXun-bot  | The above exception was the direct cause of the following exception:
ZhenXun-bot  | 
ZhenXun-bot  | Traceback (most recent call last):
ZhenXun-bot  |   File "/home/zhenxun_bot/bot.py", line 5, in <module>
ZhenXun-bot  |     nonebot.init()
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 230, in init
ZhenXun-bot  |     config = Config(
ZhenXun-bot  |   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
ZhenXun-bot  |   File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/config.py", line 80, in __call__
ZhenXun-bot  |     raise SettingsError(
ZhenXun-bot  | pydantic.env_settings.SettingsError: error parsing JSON for "superusers"
ZhenXun-bot exited with code 1
```

### 错误说明

启动容器时发生错误

**Comment by HibiKier** [comment]
你超级用户填的格式不对吧
