### ISSUE TITLE
搜索番剧错误

### ISSUE THREAD

**Issue by WhitePaper233** [HibiKier/zhenxun_bot#126]
命令：搜番魔女之旅
正常回复：开始搜番 魔女之旅
然后报错:
```
02-27 18:51:40 [ERROR] plugins | Timeout!
02-27 18:51:40 [INFO] nonebot | Matcher <Matcher from plugins.search_anime, type=message, priority=5, temp=False> running complete
02-27 18:51:40 [ERROR] nonebot | Running matcher <Matcher from plugins.search_anime, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    nonebot.run()
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/homeserver/.cache/pypoetry/virtualenvs/zhenxun-bot-xfbITNpN-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/homeserver/QQBot/Potato/zhenxun_bot/plugins/search_anime/__init__.py", line 47, in _
    anime_report = await from_anime_get_info(
  File "/home/homeserver/QQBot/Potato/zhenxun_bot/plugins/search_anime/data_source.py", line 18, in from_anime_get_info
    repass.insert(0, f"搜索 {key_word} 结果（耗时 {int(time.time() - s_time)} 秒）：\n")
AttributeError: 'str' object has no attribute 'insert'
```

**Comment by HibiKier** [comment]
一般是网络访问失败有这问题
