### ISSUE TITLE
求助 发送签到指令没有成功发送签到消息

### ISSUE THREAD

**Issue by Sevent017** [HibiKier/zhenxun_bot#1264]
### 错误说明

发生了xx错误...
2-17 17:28:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
02-17 17:28:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
02-17 17:28:16 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
02-17 17:28:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
02-17 17:28:16 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
02-17 17:28:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
02-17 17:28:16 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
02-17 17:28:17 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
02-17 17:28:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.sign_in)
02-17 17:28:17 [INFO] sign_in | (USER 3254155589, GROUP 1062547543) CHECKED IN successfully. score: 0.05 (+0.05).获取金币：53
02-17 17:28:17 [INFO] nonebot | Matcher(type='message', module=plugins.sign_in) running complete
02-17 17:28:17 [ERROR] nonebot | Running Matcher(type='message', module=plugins.sign_in) failed.
Traceback (most recent call last):
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\zhenxun\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\zhenxun\plugins\sign_in\__init__.py", line 94, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
  File "D:\zhenxun\plugins\sign_in\group_user_checkin.py", line 39, in group_user_check_in
    return await _handle_check_in(nickname, user_qq, group, present)  # ok
  File "D:\zhenxun\plugins\sign_in\group_user_checkin.py", line 93, in _handle_check_in
    return await get_card(user, nickname, impression_added, gold, gift)
  File "D:\zhenxun\plugins\sign_in\utils.py", line 74, in get_card
    ava = BytesIO(await get_user_avatar(user_id))
  File "D:\zhenxun\utils\utils.py", line 377, in get_user_avatar
    return (await client.get(url)).content
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\17\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\17\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-CPPiluQ5-py3.10\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

**Comment by HibiKier** [comment]
httpx.ReadError   网络问题，发送消息的时候网络错误了，多试几次试试

**Comment by Sevent017** [comment]
请问lxml依赖没有安装成功会有什么影响吗

**Comment by HibiKier** [comment]
对应依赖的功能用不了
