### ISSUE TITLE
Unknown DB scheme: postgresql连不上啊

### ISSUE THREAD

**Issue by Xiaojack1026** [HibiKier/zhenxun_bot#1267]
02-20 14:27:14 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\zhenxun\zhenxun_bot\services\db_context.py", line 50, in init
    await Tortoise.init(db_url=i_bind, modules={"models": MODELS})
  File "C:\Program Files\Python310\lib\site-packages\tortoise\__init__.py", line 533, in init
    config = generate_config(db_url, modules)
  File "C:\Program Files\Python310\lib\site-packages\tortoise\backends\base\config_generator.py", line 189, in generate_config
    "connections": {_connection_label: expand_db_url(db_url, testing)},
  File "C:\Program Files\Python310\lib\site-packages\tortoise\backends\base\config_generator.py", line 130, in expand_db_url
    raise ConfigurationError(f"Unknown DB scheme: {url.scheme}")
tortoise.exceptions.ConfigurationError: Unknown DB scheme: postgresql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Program Files\Python310\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Program Files\Python310\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\Documents\zhenxun\zhenxun_bot\services\db_context.py", line 54, in init
    raise Exception(f"数据库连接错误.... {type(e)}: {e}")
Exception: 数据库连接错误.... <class 'tortoise.exceptions.ConfigurationError'>: Unknown DB scheme: postgresql

02-20 14:27:14 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by q56535** [comment]
将`configs/config.py`里的`sql_name`内容改成`"postgres"`

**Comment by Xiaojack1026** [comment]
透不过的夜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] Unknown DB scheme: postgresql连不上啊 (Issue #1267)





 
将configs/config.py里的sql_name内容改成"postgres"

**Comment by Xiaojack1026** [comment]
谢谢大佬

**Comment by Xiaojack1026** [comment]
大佬好，能再问大佬一个问题么
到



卡住了，然后也不生成配置文件了


透不过的夜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] Unknown DB scheme: postgresql连不上啊 (Issue #1267)





 
将configs/config.py里的sql_name内容改成"postgres"
