### ISSUE TITLE
tortoise.exceptions.OperationalError: no such table: ban_users

### ISSUE THREAD

**Issue by Nenot233** [HibiKier/zhenxun_bot#1276]
### 错误截图
![62CPF)%M3%R{(68%N4JBYYV](https://user-images.githubusercontent.com/108965579/220849906-3a2aaec3-1e8b-41b4-9d33-b3b134be09a5.png)

错误文字
02-23 15:53:43 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 141, in execute_query
    rows = await connection.execute_fetchall(query, values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 203, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: ban_users

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\auth_hook.py", line 21, in _
    await AuthChecker().auth(matcher, bot, event)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\_utils.py", line 150, in auth
    await self.auth_basic(plugin_name, bot, event)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\_utils.py", line 467, in auth_basic
    or await BanUser.is_ban(event.user_id)
  File "D:\BOT\zhenxun_bot\models\ban_user.py", line 72, in is_ban
    if await cls.check_ban_time(user_qq):
  File "D:\BOT\zhenxun_bot\models\ban_user.py", line 52, in check_ban_time
    if user := await cls.filter(user_qq=user_qq).first():
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: no such table: ban_users

更新了新版本的真寻后出现错误

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/220850432-e223f568-9510-48bc-b22f-0c0415598634.png)
数据库配置

**Comment by HibiKier** [comment]
用命令行和或pgadmin看看

**Comment by Nenot233** [comment]
![K1YEX3P 9WD62M$(@7{ 6 H](https://user-images.githubusercontent.com/108965579/220939272-ca11f384-b4a6-4cd9-affc-a661f5225203.png)

**Comment by A1oneR** [comment]
ubuntu 20.04 从0.1.6.3版本升级至0.1.6.6版本有相同问题

**Comment by Nenot233** [comment]
已解决，是带有数据库的插件导致无法读取
新建数据库并删除该插件大概率能解决

**Comment by MWTJC** [comment]
本人win10，从0.1.6.6升级到0.1.6.7版本有相同问题，特征与1楼相同，即带有`\site-packages\tortoise\backends\sqlite\`字样且不能从错误信息判断具体报错插件，经排查，是本人自行添加的“learning_chat”插件引起，此插件确实带有sqlite数据库。另：本人删除插件后即恢复正常，未手动变更数据库。
