### ISSUE TITLE
求助！词库问答出现问题

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1280]
### 错误截取

02-26 02:47:03 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=plugins.word_bank.message_handle).Traceback (most recent call last):
  File "F:\zhenxun\zhenxun_bot\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever    super().run_forever()
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\message.py", line 131, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 296, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\internal\rule.py", line 73, in __call__
    results = await asyncio.gather(
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\zhenxun\zhenxun_bot\plugins\word_bank\_rule.py", line 45, in check
    if problem and (await WordBank.check_problem(event, problem) is not None):
  File "F:\zhenxun\zhenxun_bot\plugins\word_bank\_model.py", line 256, in check_problem
    if data_list := await query.filter(
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\queryset.py", line 1000, in __await__
    self._make_query()
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\expressions.py", line 360, in resolve
    return self._resolve_children(model, table)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\expressions.py", line 336, in _resolve_children
    node_modifier = node.resolve(model, table)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "C:\Users\X\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-XmZVBs2Q-py3.10\lib\site-packages\tortoise\expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'cword_scope'. Allowed base values are ['answer', 'create_time', 'group_id', 'id', 'image_path', 'placeholder', 'problem', 'status', 'to_me', 'update_time', 'user_qq', 'word_scope', 'word_type']

### 错误说明

正常聊天就会报错，发送指令却不会出现

**Comment by NathanSummer** [comment]
建议日志发成图片形式

**Comment by Huang1932539** [comment]
> 建议日志发成图片形式

啊这，我试试

**Comment by Huang1932539** [comment]
<img width="1274" alt="屏幕截图 2023-03-01 234323" src="https://user-images.githubusercontent.com/122792813/222190151-3007567b-65b2-4daa-b385-c14ccb1252fc.png">
###看到了没？

**Comment by HibiKier** [comment]
更新

**Comment by Huang1932539** [comment]
> 更新

更新出现这个错误是咋回事？
<img width="860" alt="屏幕截图 2023-03-03 020542" src="https://user-images.githubusercontent.com/122792813/222513937-62506018-0e57-428b-ace5-72f1196b7a51.png">

**Comment by HibiKier** [comment]
网络问题，手动换文件夹吧

**Comment by Huang1932539** [comment]
啊这，是把除了额外插件以外的文件夹都替换吗？

**Comment by HibiKier** [comment]
你想更新哪个插件就换哪个文件夹
