### ISSUE TITLE
开箱命令反回未抽取到任何皮肤...

### ISSUE THREAD

**Issue by ARCHERXTY** [HibiKier/zhenxun_bot#1284]
### 错误截图

![image](https://user-images.githubusercontent.com/59302439/221713131-54a3a55e-8bdd-44ab-b0fb-5cc7ebc1be4d.png)

### 日志截图

![image](https://user-images.githubusercontent.com/59302439/221713237-cc955025-d3cc-4a4f-b392-a4cdc0d6dc85.png)

### 错误说明

好像是没找到skin_list

**Comment by HibiKier** [comment]
嗯，现在开箱完全依赖数据库，允许更新任何一种箱子，每日更新的话可以查看饰品价格趋势

**Comment by dong2005923** [comment]
> 嗯，现在开箱完全依赖数据库，允许更新任何一种箱子，每日更新的话可以查看饰品价格趋势

现在又提示未收录任何武器箱，但是我用更新开箱图片的命令，又没有任何提示，包括控制台也没有相关提示
![0U2 QKL V{OE}17@(}G 3Y6](https://user-images.githubusercontent.com/109427426/222190205-d6061595-122a-48d3-8a20-35b69afe2e5c.png)
![LD8NT2 ND1ECM0RLI_6RS1R](https://user-images.githubusercontent.com/109427426/222190423-ab65e0e5-68aa-4fa7-907b-75a80189ab07.png)

**Comment by dong2005923** [comment]
> 未指定武器箱， 当前已包含武器箱 1.变革 [已更新] 2.反冲 3.梦魇 4.激流 5.蛇噬 6.狂牙大行动 [已更新] 7.裂空 8.棱彩2号 9.CS20 10.裂网大行动 11.棱彩 12.头号特训 13.地平线 14.命悬一线 15.光谱2号 16.九头蛇大行动 17.光谱 18.手套武器箱 19.伽玛2号 20.伽玛 21.幻彩3号 22.野火大行动 23.左轮武器箱 24.暗影 25.弯曲猎手 26.幻彩2号 27.幻彩 28.先锋 29.电竞2014夏季 30.突围大行动 31.猎杀者 32.凤凰 33.电竞2013冬季 34.冬季攻势 35.军火交易3号 36.英勇 37.电竞2013 38.军火交易2号 39.军火交易
> 
> 更新武器箱 + 武器箱名称

现在开箱必须单次开箱后才可使用多连开箱命令，否则报错
错误日志
03-02 21:32:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.open_cases)
Resetting connection with an active transaction <asyncpg.connection.Connection object at 0x000001ADB54F3E60>
03-02 21:32:33 [INFO] nonebot | Matcher(type='message', module=plugins.open_cases) running complete
03-02 21:32:33 [ERROR] nonebot | Running Matcher(type='message', module=plugins.open_cases) failed.
Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\tortoise\models.py", line 1059, in get_or_create
    await cls.select_for_update().filter(**kwargs).using_db(connection).get(),
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\tortoise\queryset.py", line 1020, in _execute
    raise DoesNotExist("Object does not exist")
tortoise.exceptions.DoesNotExist: Object does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\tortoise\models.py", line 1064, in get_or_create
    return await cls.create(using_db=connection, **defaults, **kwargs), True
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\tortoise\backends\asyncpg\client.py", line 86, in _translate_exceptions
    raise IntegrityError(exc)
tortoise.exceptions.IntegrityError: null value in column "open_cases_time_last" of relation "open_cases_users" violates not-null constraint
DETAIL:  失败, 行包含(354, 3079372395, 662835755, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1906, in _run_once
  File "asyncio\events.py", line 80, in _run
03-02 21:32:33 [INFO] nonebot | Matcher(type='message', module=plugins.open_cases) running complete
03-02 21:32:34 [SUCCESS] nonebot | OneBot V11 3078557961 | [message.group.normal]: Message 1866519934 from 3302470148@[群:952613149] "十连开箱"

![`%@6FET%( DJYS$YH}2S{E](https://user-images.githubusercontent.com/109427426/222443659-4c5f12dd-f796-4c73-a77d-a8a8c950c45a.png)

![A3LYXC{E7Q{{0SFWYB3 ~MA](https://user-images.githubusercontent.com/109427426/222443727-0f5d16b1-f757-4032-827b-6c5413e9ee2b.jpg)
