### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1294]
### 日志截图

![-71b8ea763473cfe6](https://user-images.githubusercontent.com/109641391/222920856-0b15f169-075a-4dcd-bf16-7a9941498615.png)

**Comment by JiaHuann** [comment]
同样
```shell
 Traceback (most recent call last):
ZhenXun-bot  |   File "/home/zhenxun_bot/bot.py", line 22, in <module>
ZhenXun-bot  |     nonebot.run()
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
ZhenXun-bot  |     get_driver().run(*args, **kwargs)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
ZhenXun-bot  |     uvicorn.run(
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
ZhenXun-bot  |     server.run()
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
ZhenXun-bot  |     return asyncio.run(self.serve(sockets=sockets))
ZhenXun-bot  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
ZhenXun-bot  |     return loop.run_until_complete(main)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
ZhenXun-bot  |     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
ZhenXun-bot  | > File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
ZhenXun-bot  |     await matcher.run(bot, event, state, stack, dependency_cache)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
ZhenXun-bot  |     await self.simple_run(bot, event, state, stack, dependency_cache)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
ZhenXun-bot  |     await handler(
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
ZhenXun-bot  |     return await self.call(**values)
ZhenXun-bot  |   File "/home/zhenxun_bot/basic_plugins/help/__init__.py", line 55, in _
ZhenXun-bot  |     msg = get_plugin_help(msg, is_super)
ZhenXun-bot  |   File "/home/zhenxun_bot/basic_plugins/help/data_source.py", line 341, in get_plugin_help
ZhenXun-bot  |     module = plugins2settings_manager.get_plugin_module(msg)
ZhenXun-bot  |   File "/home/zhenxun_bot/utils/manager/plugins2settings_manager.py", line 88, in get_plugin_module
ZhenXun-bot  |     if cmd in self._data[key]["cmd"]:
ZhenXun-bot  | TypeError: argument of type 'NoneType' is not iterable
ZhenXun-bot  | 03-09 00:55:14 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
```
