### ISSUE TITLE
更新已收录的武器箱发生报错

### ISSUE THREAD

**Issue by zyima** [HibiKier/zhenxun_bot#1300]
### 错误截图
![报错](https://user-images.githubusercontent.com/66709758/223284515-1ceb8831-a536-487c-b042-aef84372837d.png)
![不替换](https://user-images.githubusercontent.com/66709758/223284527-e9c82f35-8b3d-4df2-813d-6d6dd66def8f.png)

### 错误说明
更新已收录的武器箱会发生报错"All bulk_update() objects must have a primary key set."(如图1，更新变革失败) 但是更新没有收录的武器箱则正常(如图2，更新裂空成功，裂空此前尚未收录)
![`6`$EIL2%SMW_2AZ5GW2 2H](https://user-images.githubusercontent.com/66709758/223285106-e248d61d-918e-43ce-b2e9-36217798273c.png)

**Comment by HibiKier** [comment]
更新

**Comment by zyima** [comment]
> 更新

是指更新真寻还是更新开箱，如果是更新开箱的话这已经是更新后的了

**Comment by dong2005923** [comment]
> 更新

我更新了真寻，但是更新武器箱也有报错导致不能更新。更新没有收录的武器箱会有报错

03-10 18:04:21 [SUCCESS] nonebot | OneBot V11 3078557961 | [message_sent]: {'time': 1678442660, 'self_id': 3078557961, 'post_type': 'message_sent', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': '云崽&真寻&nonebot2', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 3078557961}, 'message_seq': 10278, 'group_id': 662835755, 'font': 0, 'user_id': 3078557961, 'message_id': 358361573, 'message_type': 'group', 'raw_message': '开始更新武器箱: 变革, 请稍等', 'anonymous': None, 'message': '开始更新武器箱: 变革, 请稍等', 'sub_type': 'normal'}
03-10 18:04:21 [INFO] nonebot | Event will be handled by Matcher(type='message_sent', module=plugins.self_message)
03-10 18:04:21 [INFO] nonebot | Matcher(type='message_sent', module=plugins.self_message) running complete
03-10 18:04:21 [INFO] nonebot | Matcher(type='message', module=plugins.open_cases) running complete
03-10 18:04:21 [ERROR] nonebot | Running Matcher(type='message', module=plugins.open_cases) failed.
Traceback (most recent call last):
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\Zhenxun\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-TAFDvVrX-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-TAFDvVrX-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-TAFDvVrX-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-TAFDvVrX-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1906, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "C:\msys64\home\Administrator\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-TAFDvVrX-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher

**Comment by zyima** [comment]
手动更新最新真寻(0.1.6.7)里关于开箱的代码就可以了
