### ISSUE TITLE
商品显示未注册使用方法

### ISSUE THREAD

**Issue by Nenot233** [HibiKier/zhenxun_bot#1324]
### 真寻版本：0.1.6.7

购买正常
除了好感度双倍加持卡Ⅰ可以正常使用，其他商品显示未注册使用方法

### 错误说明
03-12 10:37:59 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):

  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
    │       └ <function run at 0x0000021C841EAB80>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-l9AehN_x-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x0000021C83E5FB80>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x0000021C8551EAF0>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-l9AehN_x-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x0000021C8551ECA0>
    └ <uvicorn.server.Server object at 0x0000021CC72FE280>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x0000021C8551ED30>
           │       │   └ <uvicorn.server.Server object at 0x0000021CC72FE280>
           │       └ <function run at 0x0000021C81E4BF70>
           └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x0000021CC72BBE40>
           │    └ <function BaseEventLoop.run_until_complete at 0x0000021C8374ECA0>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000021C837DCB80>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000021C83751790>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000021C836EA670>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000021CC798F400>(<_GatheringFu... is closing')>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000021CC798F400>(<_GatheringFu... is closing')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000021CC798F400>(<_GatheringFu... is closing')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000021CC798F400>(<_GatheringFu... is closing')>)>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object run_coro_with_catch at 0x0000021CC7A9F940>, <coroutine object run_coro_with_catch at 0x0000021CC7A9F0C0>, ...
          │       └ <function gather at 0x0000021C83740E50>
          └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x0000021CC7A9F440>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='463899398')}
                 │    │             │         │    │    └ <function _ at 0x0000021C98E0BDC0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x0000021C819A2C10>

  File "D:\BOT\zhenxun_bot\basic_plugins\scripts.py", line 152, in _
    if not await GroupInfo.get_or_none(group_id=114514):
                 │         └ <classmethod object at 0x0000021C846B87F0>
                 └ <class 'models.group_info.GroupInfo'>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
                          │    └ <member '_db' of 'QuerySet' objects>
                          └ <tortoise.queryset.QuerySet object at 0x0000021CC781A8C0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
                           │    │  │             │     └ <function PostgreSQLQueryBuilder.get_sql at 0x0000021C8458EDC0>
                           │    │  │             └ SELECT "group_flag","member_count","max_member_count","group_id","group_name" FROM "group_info" WHERE "group_id"=114514 LIMIT 2
                           │    │  └ <function AsyncpgDBClient.execute_query at 0x0000021CC74073A0>
                           │    └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x0000021CC73D1880>
                           └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x0000021CC7A3C400>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
                 │    │                     │      │       └ {}
                 │    │                     │      └ ('SELECT "group_flag","member_count","max_member_count","group_id","group_name" FROM "group_info" WHERE "group_id"=114514 LIM...
                 │    │                     └ <function AsyncpgDBClient.execute_query at 0x0000021CC7407310>
                 │    └ <function AsyncpgDBClient._translate_exceptions at 0x0000021CC7401E50>
                 └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x0000021CC73D1880>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
                 │    │      │       └ {}
                 │    │      └ ('SELECT "group_flag","member_count","max_member_count","group_id","group_name" FROM "group_info" WHERE "group_id"=114514 LIM...
                 │    └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x0000021CC73D1880>
                 └ <function AsyncpgDBClient.execute_query at 0x0000021CC7407310>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\asyncpg\client.py", line 129, in execute_query
    async with self.acquire_connection() as connection:
               │    └ <function AsyncpgDBClient.acquire_connection at 0x0000021CC7401F70>
               └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x0000021CC73D1880>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\client.py", line 328, in __aenter__
    self.connection = await self.pool.acquire()
    │    │                  │    │    └ <function Pool.acquire at 0x0000021C98FA9940>
    │    │                  │    └ <asyncpg.pool.Pool object at 0x0000021CC726F5F0>
    │    │                  └ <tortoise.backends.base.client.PoolConnectionWrapper object at 0x0000021CCA17FFD0>
    │    └ None
    └ <tortoise.backends.base.client.PoolConnectionWrapper object at 0x0000021CCA17FFD0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\asyncpg\pool.py", line 838, in _acquire
    raise exceptions.InterfaceError('pool is closing')
          │          └ <class 'asyncpg.exceptions._base.InterfaceError'>
          └ <module 'asyncpg.exceptions' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-l9AehN...

asyncpg.exceptions._base.InterfaceError: pool is closing
03-12 10:37:59 [INFO] services | register_use 成功注册商品：好感度双倍加持卡Ⅰ 的使用函数

**Comment by MobiusT** [comment]
是否安装了方舟工具箱插件呢？
没有的话可以检查以下安装的插件中是否有使用了Tortoise.init(方法

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/225796770-458a14f7-e83a-4d0a-bc9b-7fe50385d7c7.png)
安装了方舟工具箱插件

**Comment by Nenot233** [comment]
https://github.com/NumberSir/zhenxun_arktools
安装了方舟工具箱插件

**Comment by Nenot233** [comment]
好感度双倍加持卡II 未注册使用方法
好感度双倍加持卡III 未注册使用方法
目前也无法使用，大概率是这个插件导致的(?)

**Comment by MobiusT** [comment]
这个不是真寻的问题，需要去方舟工具箱的插件仓库提交
可以提供一个临时解决办法（仅适用该插件最新版本
在zhenxun_arktools/src/utils下修改database.py
1、import asyncio
2、按下文在以下日志新写一行sleep
        logger.info("##### ARKNIGHTS-SQLITE CONNECTING ...")
        await asyncio.sleep(10)

修改前记得备份原文件

**Comment by Nenot233** [comment]
已解决，感谢群友
