### ISSUE TITLE
字段 "login_ticket" 不存在，bot无法启动

### ISSUE THREAD

**Issue by changgongz** [HibiKier/zhenxun_bot#1335]
### 错误截图

![1679821164150](https://user-images.githubusercontent.com/105897291/227765644-37aeb635-a9f7-49cb-b643-a4c9fc83e0e1.jpg)

### 日志截图

03-26 16:28:40 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\zhenxun_bot-main\services\db_context.py", line 45, in init
    raise ValueError("\n" + prompt2cn("数据库配置未填写", 28))
ValueError: 
############################
############################

03-26 16:28:40 [ERROR] uvicorn | Application startup failed. Exiting.
03-26 16:32:17 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\zhenxun_bot-main\basic_plugins\init_plugin_config\__init__.py", line 48, in _
    raise Exception("首次运行，已在configs目录下生成配置文件config.yaml，修改后重启即可...")
Exception: 首次运行，已在configs目录下生成配置文件config.yaml，修改后重启即可...

03-26 16:32:17 [ERROR] uvicorn | Application startup failed. Exiting.
03-26 16:44:27 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 620, in fetch
    return await self._execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: 字段 "stoken" 不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\zhenxun_bot-main\plugins\genshin\query_user\resin_remind\init_task.py", line 82, in _
    g_list = await Genshin.filter(resin_remind=True).all()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "stoken" 不存在

03-26 16:44:27 [ERROR] uvicorn | Application startup failed. Exiting.
03-26 16:50:02 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 620, in fetch
    return await self._execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: 字段 "login_ticket" 不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\zhenxun_bot-main\plugins\genshin\query_user\resin_remind\init_task.py", line 82, in _
    g_list = await Genshin.filter(resin_remind=True).all()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "login_ticket" 不存在

03-26 16:50:02 [ERROR] uvicorn | Application startup failed. Exiting.
03-26 16:53:18 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 620, in fetch
    return await self._execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: 字段 "login_ticket" 不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\zhenxun_bot-main\plugins\genshin\query_user\resin_remind\init_task.py", line 82, in _
    g_list = await Genshin.filter(resin_remind=True).all()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "login_ticket" 不存在

03-26 16:53:18 [ERROR] uvicorn | Application startup failed. Exiting.

### 错误说明

tortoise.exceptions.OperationalError: 字段 "login_ticket" 不存在

**Comment by HibiKier** [comment]
哪个版本升上来的

**Comment by changgongz** [comment]
> 哪个版本升上来的

0.1.5.7

**Comment by changgongz** [comment]
> 以前的script注释了，你更新到刚刚提交的代码然后重启吧

报错：

03-28 18:04:55 [ERROR] uvicorn | [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8080): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
03-28 18:05:26 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 620, in fetch
    return await self._execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: 字段 "stuid" 不存在
HINT:  也许您想要引用列"genshin.uid"。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\plugins\genshin\query_user\genshin_sign\init_task.py", line 26, in _
    g_list = await Genshin.filter(auto_sign=True).all()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "stuid" 不存在
HINT:  也许您想要引用列"genshin.uid"。

03-28 18:05:26 [ERROR] uvicorn | Application startup failed. Exiting.
03-28 18:08:06 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 620, in fetch
    return await self._execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\asyncpg\connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: 字段 "stuid" 不存在
HINT:  也许您想要引用列"genshin.uid"。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\plugins\genshin\query_user\resin_remind\init_task.py", line 82, in _
    g_list = await Genshin.filter(resin_remind=True).all()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "stuid" 不存在
HINT:  也许您想要引用列"genshin.uid"。

03-28 18:08:06 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by changgongz** [comment]
![image](https://user-images.githubusercontent.com/105897291/228204389-5300e862-6f15-426d-9fd4-4d1f56166bed.png)

**Comment by changgongz** [comment]
注释了这几行之后
![image](https://user-images.githubusercontent.com/105897291/228211849-4f55f532-bf39-4607-9dd8-11775bf73ab7.png)

报错：
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\basic_plugins\shop\__init__.py", line 27, in _
    await shop_register.load_register()
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\utils\decorator\shop.py", line 103, in load_register
    await register_goods(
  File "C:\Users\Administrator\Downloads\115download\zhenxun_bot-main\basic_plugins\shop\shop_handle\data_source.py", line 264, in register_goods
    if not await GoodsInfo.get_or_none(goods_name=name):
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\zhenxun\lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 字段 "icon" 不存在

**Comment by HibiKier** [comment]
更新

**Comment by changgongz** [comment]
另外报错：

03-29 17:16:59 [ERROR] services | CMD[色图] 访问页面错误 || 错误 <class 'httpx.ConnectError'>:
