### ISSUE TITLE
某些数据库密码将会阻止连接到数据库

### ISSUE THREAD

**Issue by UraraChiya** [HibiKier/zhenxun_bot#1343]
### 日志截图

```
03-31 12:31:11 [SUCCESS] nonebot | NoneBot is initializing...
03-31 12:31:11 [INFO] nonebot | Current Env: dev
03-31 12:31:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "update_info"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "broadcast"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "plugin_shop"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "hooks"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "chat_message"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "chat_history"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "nickname"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
03-31 12:31:12 [SUCCESS] nonebot | Succeeded to import "exec_sql"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "clear_data"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "reload_setting"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "manager_group"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "super_cmd"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "admin_help"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "my_props"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "use"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "buy"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "shop_handle"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "gold"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "shop"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "group_handle"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "ban"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "scripts"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "apscheduler"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "help"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "invite_manager"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "admin_config"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "switch_rule"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "timing_task"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "rule"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "super_help"
03-31 12:31:13 [SUCCESS] nonebot | Succeeded to import "update_setu"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "send_setu"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "send_setu_"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "russian"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "word_handle"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "message_handle"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "word_bank"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "epic"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "poke"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "music"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "luxun"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "send_image"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "delete_image"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "upload_image"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "move_image"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "image_management"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "web_ui"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "fake_msg"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "yiqing"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "one_friend"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "what_anime"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "dialogue"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "open_cases"
03-31 12:31:14 [SUCCESS] nonebot | Succeeded to import "sign_in"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "my_info"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "withdraw"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "mute"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "quotations"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "statistics"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "word_clouds"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "ai"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "about"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "weather"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "aconfig"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "self_message"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "pid_search"
03-31 12:31:15 [SUCCESS] nonebot | Succeeded to import "translate"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "white2black_image"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "search_anime"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "fudu"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "coser"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "roll"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "bt"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "check"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "wbtop"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "search_image"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "update_picture"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "black_word"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix_update"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
03-31 12:31:16 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
03-31 12:31:17 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
03-31 12:31:17 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "draw_card"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "bind"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "query_memo"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "resin_remind"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "query_role"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "mihoyobbs_sign"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "query_user"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "almanac"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "material_remind"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "genshin"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "jitang"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "cover"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "comments_163"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "poetry"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "alapi"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "ban_hook"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "task_hook"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "auth_hook"
03-31 12:31:18 [SUCCESS] nonebot | Succeeded to import "other_hook"
03-31 12:31:18 [SUCCESS] nonebot | Running NoneBot...
03-31 12:31:18 [INFO] uvicorn | Started server process [5884]
03-31 12:31:18 [INFO] uvicorn | Waiting for application startup.
03-31 12:31:19 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/zhenxun/zhenxun_bot/services/db_context.py", line 52, in init
    await Tortoise.generate_schemas()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 640, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/utils.py", line 31, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/base/schema_generator.py", line 448, in generate_from_string
    await self.client.execute_script(creation_string)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/base_postgres/client.py", line 150, in execute_script
    async with self.acquire_connection() as connection:
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/base/client.py", line 326, in __aenter__
    await self.ensure_connection()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 65, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 409, in _async__init__
    await self._initialize()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 437, in _initialize
    await first_ch.connect()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 129, in connect
    self._con = await self._pool._get_new_connection()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 507, in _get_new_connection
    con = await connection.connect(
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "uvloop/loop.pyx", line 1978, in create_connection
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/zhenxun/.cache/pypoetry/virtualenvs/zhenxun-bot-jK_EF8Sg-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/zhenxun/zhenxun_bot/services/db_context.py", line 55, in init
    raise Exception(f"数据库连接错误.... {type(e)}: {e}")
Exception: 数据库连接错误.... <class 'socket.gaierror'>: [Errno -2] Name or service not known
```

### 错误说明

当我将数据库密码修改为 `password: str = "9q,eT4a~@VRZpf1fHfcD,A-G%=Z{X,c#WQljcYUSuDJm,)ihE1"  # 数据库密码` 时，使用dbeaver等工具可连接到数据库，但是bot报错数据库连接错误，无法启动，修改密码后此现象消失

**Comment by gili-gili** [comment]
請不要在密碼中使用特殊字符
建議僅使用數字與字母組成的密碼

**Comment by gili-gili** [comment]
我也遇到了這個問題，通過去除密碼中的特殊字符解決了
