### ISSUE TITLE
求助，搭建真寻后启动报错

### ISSUE THREAD

**Issue by XiaoLuoLi521** [HibiKier/zhenxun_bot#1352]
### 错误截图

![image](https://user-images.githubusercontent.com/91067171/229991775-75b17fed-99d0-4824-b012-45f5ca6cec5e.png)

### 错误日志

04-05 12:08:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/zhenxun_bot/utils/browser.py", line 21, in start_browser
    _browser = await _playwright.chromium.launch()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

04-05 12:08:59 [ERROR] uvicorn | Application startup failed. Exiting.

### 错误说明

启动真寻时报错，第一次搭建，之前未启动过
启动失败报错

**Comment by HibiKier** [comment]
playwright install

**Comment by INSide-734** [comment]
使用poetry shell进入虚拟环境
再键入playwright install
