### ISSUE TITLE
在已安装playwright install chromium依然出现报错

### ISSUE THREAD

**Issue by beiyaohhhc** [HibiKier/zhenxun_bot#1360]
### 错误截图

![image](https://user-images.githubusercontent.com/98569420/230947246-cbdd6a30-9891-4e14-8226-c8ac2cd36e44.png)

### 日志截图

04-11 00:33:55 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\zhenxun_bot\utils\browser.py", line 21, in start_browser
    _browser = await _playwright.chromium.launch()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\playwright\async_api\_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1041\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

04-11 00:33:55 [ERROR] uvicorn | Application startup failed. Exiting.

### 错误说明
运行playwright install chromium后运行python bot.py 插件正常加载 最后一步出现问题 如图

**Comment by beiyaohhhc** [comment]
按照提示运行

78.5 Mb [====================] 100% 0.0s
Failed to install browsers
Error: Failed to download Firefox 107.0 (playwright build v1369), caused by
Error: ENOSPC: no space left on device, write

**Comment by HibiKier** [comment]
把你目录下playwright安装的浏览器全部删掉再安装试试

**Comment by beiyaohhhc** [comment]
> 把你目录下playwright安装的浏览器全部删掉再安装试试

谢谢 已解决

**Comment by Tobias272727** [comment]
如果是windows server 2012r2 仍然会有这个问题。google 已经停止对2016以下版本（基于win10之前内核的版本）的chrome支持。 ref: https://github.com/microsoft/playwright/issues/21490#issuecomment-1460739580
建议方便完善文档的时候，提一嘴win server 版本 > 2016@HibiKier
