### ISSUE TITLE
有没有看推特连接里的图片的插件啊？

### ISSUE THREAD

**Issue by m0eak** [HibiKier/zhenxun_bot#1378]
就是发一个链接，可以把推文里的图片都发到群里的那种

**Comment by PackageInstaller** [comment]
[倒是有个nb插件，不过可能会合真寻自带的解析有冲突](https://github.com/zhiyu1998/nonebot-plugin-resolver)

**Comment by m0eak** [comment]
> [倒是有个nb插件，不过可能会合真寻自带的解析有冲突](https://github.com/zhiyu1998/nonebot-plugin-resolver)

真寻怎么使用nonebot的插件啊，直接放进去会报错

**Comment by PackageInstaller** [comment]
> > [倒是有个nb插件，不过可能会合真寻自带的解析有冲突](https://github.com/zhiyu1998/nonebot-plugin-resolver)
> 
> 真寻怎么使用nonebot的插件啊，直接放进去会报错

如果你有报错信息就更好了

**Comment by m0eak** [comment]
> 

`07-01 19:37:46 [ERROR] nonebot | Failed to import "nonebot-plugin-resolver"
Traceback (most recent call last):
  File "bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/nonebot-plugin-resolver/__init__.py", line 10, in <module>
    from .tiktok_utills import get_id_video, generate_x_bogus_url, generate_random_str
  File "/home/zhenxun_bot/extensive_plugin/nonebot-plugin-resolver/tiktok_utills.py", line 5, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'
`

**Comment by m0eak** [comment]
> > > [倒是有个nb插件，不过可能会合真寻自带的解析有冲突](https://github.com/zhiyu1998/nonebot-plugin-resolver)
> > 
> > 
> > 真寻怎么使用nonebot的插件啊，直接放进去会报错
> 
> 如果你有报错信息就更好了

07-01 19:37:46 [ERROR] nonebot | Failed to import "nonebot-plugin-resolver"
Traceback (most recent call last):
  File "bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/nonebot-plugin-resolver/__init__.py", line 10, in <module>
    from .tiktok_utills import get_id_video, generate_x_bogus_url, generate_random_str
  File "/home/zhenxun_bot/extensive_plugin/nonebot-plugin-resolver/tiktok_utills.py", line 5, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by PackageInstaller** [comment]
在虚拟环境中执行`pip install execjs` 
再不行就`pip install --upgrade nonebot-plugin-resolver`
