### ISSUE TITLE
apscheduler报错可能是bilibili_sub导致

### ISSUE THREAD

**Issue by 1294266616** [HibiKier/zhenxun_bot#1397]
### 错误截图
![image](https://user-images.githubusercontent.com/52421598/234470841-17c25edd-a123-442a-8d49-a4eae79bf139.png)
![image](https://user-images.githubusercontent.com/52421598/234470893-619d95e8-20ff-4e72-b0e1-6fd27d77a18f.png)

[img]

### 日志截图
无
[img]

### 错误说明
看起来是bilibili_sub导致的错误，后台一直报错的

04-26 12:33:39 [ERROR] apscheduler | Job "_ (trigger: interval[0:00:30], next run at: 2023-04-26 12:34:09 CST)" raised an exception,
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46),
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run,
Traceback (most recent call last):,
    nonebot.run(),
  File "/home/zhenxun_bot/bot.py", line 21, in <module>,
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run,
    get_driver().run(*args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run,
    uvicorn.run(,
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run,
    server.run(),
    return asyncio.run(self.serve(sockets=sockets)),
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run,
> File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job,
    return loop.run_until_complete(main),
    retval = await job.func(*job.args, **job.kwargs),
  File "/home/zhenxun_bot/plugins/bilibili_sub/__init__.py", line 244, in _,
    rst = await get_sub_status(sub.sub_id, sub.sub_type),
  File "/home/zhenxun_bot/plugins/bilibili_sub/data_source.py", line 204, in get_sub_status,
    return await _get_up_status(id_),
  File "/home/zhenxun_bot/plugins/bilibili_sub/data_source.py", line 253, in _get_up_status,
    video_info = await get_videos(_user.uid),
  File "/usr/local/lib/python3.9/site-packages/bilireq/user/__init__.py", line 44, in get_videos,
    return await get(url, params=params, auth=auth, reqtype=reqtype, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/bilireq/utils/__init__.py", line 98, in get,
    return await request("GET", url, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/bilireq/utils/__init__.py", line 85, in request,
    raw_json: Dict[str, Any] = (await _request(method, url, **kwargs)).json(),
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 756, in json,
    return jsonlib.loads(self.text, **kwargs),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads,
    return _default_decoder.decode(s),
  File "/usr/local/lib/python3.9/json/decoder.py", line 340, in decode,
    raise JSONDecodeError("Extra data", s, end)
发生了xx错误...

**Comment by ReactXS** [comment]
+1
插眼

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/235418647-70b92df2-c852-4750-a6ff-c1fd6b9ce8e2.png)
不知道我这个跟楼上是不是同一个问题，也发一下吧

**Comment by NathanSummer** [comment]
是一直报错，停不下来

**Comment by 1717tian** [comment]
插眼 问题同样 重装httpx首次订阅报401 参照之前帖子改了请求头 然后添加订阅正常了 apscheduler报错还是如上

**Comment by Terli** [comment]
同样的报错，数据库删过表bilibili_sub，请求头也是改过，这报错会导致进程卡死所以我先移除使用了

**Comment by zhx79513** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/5063357/7638b129-69c8-4114-aef6-75c0539abdb3)

我也是这样不停报错，等一个修复。
