### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1403]
### 日志截图

```
05-02 20:33:26 [ERROR] uvicorn | Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/root/zhenxun_bot/plugins/sign_in/utils.py", line 38, in init_image
    if not await GroupInfoUser.get_or_none(user_qq=114514):
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1000, in __await__
    self._make_query()
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_qq'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_id', 'user_join_time', 'user_name']

05-02 20:33:26 [ERROR] uvicorn | Application startup failed. Exiting.
```

### 错误说明

启动时报错

**Comment by INSide-734** [comment]
已自行解决

**Comment by INSide-734** [comment]
> > 已自行解决
> 
> 怎么解决的大佬

重新pull后安装依赖
