### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1409]
### 日志

```

2023/05/06 22:24:15
05-06 22:24:15 [ERROR] nonebot | Running Matcher(type='notice', module=basic_plugins.group_handle) failed.
2023/05/06 22:24:15
Traceback (most recent call last):
2023/05/06 22:24:15
  File "/root/zhenxun_bot/bot.py", line 22, in <module>
2023/05/06 22:24:15
    nonebot.run()
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
2023/05/06 22:24:15
    get_driver().run(*args, **kwargs)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
2023/05/06 22:24:15
    uvicorn.run(
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
2023/05/06 22:24:15
    server.run()
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
2023/05/06 22:24:15
    return asyncio.run(self.serve(sockets=sockets))
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023/05/06 22:24:15
    return loop.run_until_complete(main)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
2023/05/06 22:24:15
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
2023/05/06 22:24:15
> File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
2023/05/06 22:24:15
    await matcher.run(bot, event, state, stack, dependency_cache)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
2023/05/06 22:24:15
    await self.simple_run(bot, event, state, stack, dependency_cache)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
2023/05/06 22:24:15
    await handler(
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
2023/05/06 22:24:15
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
2023/05/06 22:24:15
  File "/root/zhenxun_bot/basic_plugins/group_handle/__init__.py", line 209, in _
2023/05/06 22:24:15
    if user := await GroupInfoUser.get_or_none(
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1000, in __await__
2023/05/06 22:24:15
    self._make_query()
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 962, in _make_query
2023/05/06 22:24:15
    self.resolve_filters(
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 134, in resolve_filters
2023/05/06 22:24:15
    modifier &= node.resolve(model, model._meta.basetable)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 359, in resolve
2023/05/06 22:24:15
    return self._resolve_kwargs(model, table)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 317, in _resolve_kwargs
2023/05/06 22:24:15
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
2023/05/06 22:24:15
  File "/usr/local/lib/python3.10/site-packages/tortoise/expressions.py", line 311, in _get_actual_filter_params
2023/05/06 22:24:15
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
2023/05/06 22:24:15
tortoise.exceptions.FieldError: Unknown filter param 'user_qq'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_id', 'user_join_time', 'user_name']
```

**Comment by yajiwa** [comment]
`/basic_plugins/group_handle/__init__.py`第210行`user_qq`改成`user_id` 
`user_id=str(event.user_id), group_id=str(event.group_id)`

**Comment by PackageInstaller** [comment]
> `/basic_plugins/group_handle/__init__.py`第210行`user_qq`改成`user_id` `user_id=str(event.user_id), group_id=str(event.group_id)`
修改后还是上面的报错

**Comment by PackageInstaller** [comment]
```
05-09 08:33:05 [ERROR] logging | Traceback (most recent call last):
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/home/Neko/Bot/zhenxun_bot/plugins/sign_in/utils.py", line 38, in init_image
    if not await GroupInfoUser.get_or_none(user_id="114514"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 1000, in __await__
    self._make_query()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_id'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_join_time', 'user_name', 'user_qq']

2023-05-09 08:33:05,630-ERROR: Traceback (most recent call last):
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/home/Neko/Bot/zhenxun_bot/plugins/sign_in/utils.py", line 38, in init_image
    if not await GroupInfoUser.get_or_none(user_id="114514"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 1000, in __await__
    self._make_query()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/tortoise/expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_id'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_join_time', 'user_name', 'user_qq']

```

**Comment by PackageInstaller** [comment]
回溯之前的版本了

**Comment by INSide-734** [comment]
还没修？👀

**Comment by HibiKier** [comment]
848de7f4fe4600fa7f99d9f9f9c2b9c957ce6025
