### ISSUE TITLE
添加自定义插件后报错

### ISSUE THREAD

**Issue by xharaut** [HibiKier/zhenxun_bot#1416]
root@ubuntu:/home/xharaut/zhenxun_bot-0.1.6.7# poetry shell
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Spawning shell within /root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8
root@ubuntu:/home/xharaut/zhenxun_bot-0.1.6.7# . /root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/bin/activate
(zhenxun-bot-py3.8) root@ubuntu:/home/xharaut/zhenxun_bot-0.1.6.7# python3 bot.py
05-11 22:53:25 [INFO] services.log | 加载配置完成，共加载 42 个配置组及对应 128 个配置项
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from services.db_context import init, disconnect
  File "/home/xharaut/zhenxun_bot-0.1.6.7/services/__init__.py", line 1, in <module>
    from .db_context import *
  File "/home/xharaut/zhenxun_bot-0.1.6.7/services/db_context.py", line 8, in <module>
    from configs.config import address, bind, database, password, port, sql_name, user
  File "/home/xharaut/zhenxun_bot-0.1.6.7/configs/config.py", line 36, in <module>
    Config = ConfigsManager(Path() / "data" / "configs" / "plugins2config.yaml")
  File "/home/xharaut/zhenxun_bot-0.1.6.7/configs/utils/__init__.py", line 70, in __init__
    self._simple_data = _yaml.load(f)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-GNjphRZr-py3.8/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 612, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "configs/config.yaml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "configs/config.yaml", line 277, column 3
(zhenxun-bot-py3.8) root@ubuntu:/home/xharaut/zhenxun_bot-0.1.6.7# 

之前就因为这个整个虚拟机删了重装了一遍

**Comment by HibiKier** [comment]
你config.yaml配置文件填坏了
