### ISSUE TITLE
群权限问题

### ISSUE THREAD

**Issue by Nenot233** [HibiKier/zhenxun_bot#1432]
WIN10系统，最新版本重启后导致权限重置
![image](https://github.com/HibiKier/zhenxun_bot/assets/108965579/769f4b02-0ce6-4d16-b5e6-c9a3afa9f434)
![image](https://github.com/HibiKier/zhenxun_bot/assets/108965579/f8fd0012-98b4-417a-acde-5be4f5910242)
重启后导致所有群权限重置，包括休息吧，也会醒来
![image](https://github.com/HibiKier/zhenxun_bot/assets/108965579/9465c5d8-d680-4df6-b69f-436c0ac603c5)

**Comment by Nenot233** [comment]
包括群被动状态，在私聊关闭后群无法全局关闭

**Comment by Nenot233** [comment]
05-29 08:50:56 [ERROR] services | CMD[HOOK] TaskHook ERROR || 错误 <class 'KeyError'>: 'message'
05-29 08:51:13 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 173, in _run_matcher
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\auth_hook.py", line 21, in _
    await AuthChecker().auth(matcher, bot, event)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\_utils.py", line 157, in auth
    await self.auth_basic(plugin_name, bot, event)
  File "D:\BOT\zhenxun_bot\basic_plugins\hooks\_utils.py", line 518, in auth_basic
    or await BanUser.is_ban(user_id)
  File "D:\BOT\zhenxun_bot\models\ban_user.py", line 72, in is_ban
    if await cls.check_ban_time(str(user_id)):
  File "D:\BOT\zhenxun_bot\models\ban_user.py", line 52, in check_ban_time
    if user := await cls.filter(user_id=str(user_id)).first():
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\executor.py", line 131, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\asyncpg\client.py", line 129, in execute_query
    async with self.acquire_connection() as connection:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\client.py", line 328, in __aenter__
    self.connection = await self.pool.acquire()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\asyncpg\pool.py", line 839, in _acquire
    self._check_init()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\asyncpg\pool.py", line 964, in _check_init
    raise exceptions.InterfaceError('pool is closed')
asyncpg.exceptions._base.InterfaceError: pool is closed
更新新版本的一些报错
