### ISSUE TITLE
群内识图功能会报错，私聊识图功能正常

### ISSUE THREAD

**Issue by Erlla** [HibiKier/zhenxun_bot#1433]
### 错误截图
![微信截图_20230526201247](https://github.com/HibiKier/zhenxun_bot/assets/49445907/717fd322-3c55-4a9d-89b8-fe4f44ebab0b)

### 日志截图

`05-26 04:07:31 [SUCCESS] nonebot | OneBot V11 3428645112 | [message.group.normal]: Message -728764993 from 11111111@[群:-------] "识图"                                                                 
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.group_handle)                                                                                          
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.group_handle)                                                                                          
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.admin_bot_manage.update_group_member_info)                                                             
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)                                                                                                 
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)                                                                                                       
05-26 04:07:31 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete                                                                                                         
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=basic_plugins.group_handle) running complete                                                                                                  
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=basic_plugins.group_handle) running complete                                                                                                  
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=basic_plugins.admin_bot_manage.update_group_member_info) running complete                                                                     
05-26 04:07:31 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete                                                                                                               
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)                                                                            
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)                                                                                        
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.admin_bot_manage.admin_config)                                                                         
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=plugins.poke)                                                                                                        
05-26 04:07:31 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete                                                                                                
05-26 04:07:31 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete                                                                                    
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=basic_plugins.admin_bot_manage.admin_config) running complete                                                                                 
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=plugins.poke) running complete                                                                                                                
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=plugins.gold_redbag)                                                                                                 
05-26 04:07:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.search_image)                                                                                               
05-26 04:07:31 [INFO] nonebot | Matcher(type='notice', module=plugins.gold_redbag) running complete                                                                                                         
05-26 04:07:36 [SUCCESS] nonebot | OneBot V11 3428645112 | [notice.group_card]: {'time': 1685102856, 'self_id': 3428645112, 'post_type': 'notice', 'notice_type': 'group_card', 'card_new': '热热热', 'user_
id': 1274560014, 'group_id': 544046117, 'card_old': ''}                                                                                                                                                     
05-26 04:07:36 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.group_handle)                                                                                          
05-26 04:07:36 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.group_handle)                                                                                          
05-26 04:07:36 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=basic_plugins.admin_bot_manage.update_group_member_info)                                                             
05-26 04:07:36 [INFO] nonebot | Matcher(type='message', module=plugins.search_image) running complete                                                                                                       
05-26 04:07:36 [ERROR] nonebot | Running Matcher(type='message', module=plugins.search_image) failed.                                                                                                       
Traceback (most recent call last):                                                                                                                                                                          
  File "bot.py", line 21, in <module>                                                                                                                                                                       
    nonebot.run()                                                                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run                                                                     
    get_driver().run(*args, **kwargs)  
  get_driver().run(*args, **kwargs)                                                                                                                                                                       
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run                                                              
    uvicorn.run(                                                                                                                                                                                            
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run                                                                         
    server.run()                                                                                                                                                                                            
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run                                                                        
    return asyncio.run(self.serve(sockets=sockets))                                                                                                                                                         
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run                                                                                                                                             
    return loop.run_until_complete(main)                                                                                                                                                                    
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 188, in _run_matcher                                                             
    await matcher.run(bot, event, state, stack, dependency_cache)                                                                                                                                           
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run                                                     
    await self.simple_run(bot, event, state, stack, dependency_cache)                                                                                                                                       
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run                                              
    await handler(                                                                                                                                                                                          
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 104, in __call__                                                   
    values = await self.solve(**kwargs)                                                                                                                                                                     
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 216, in solve                                                      
    await param._solve(**params)                                                                                                                                                                            
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/params.py", line 144, in _solve                                                           
    return await task                                                                                                                                                                                       
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 418, in _key_getter                                             
    await matcher.reject(prompt)                                                                                                                                                                            
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 509, in reject                                                  
    await cls.send(prompt, **kwargs)                                                                                                                                                                        
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 461, in send                                                    
    return await bot.send(event=event, message=_message, **kwargs)                                                                                                                                          
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 220, in send                                                     
    return await self.__class__.send_handler(self, event, message, **kwargs)                                                                                                                                
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 174, in send                                                     
    return await bot.send_msg(**params)                                                                                                                                                                     
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api                                                    
    raise exception                                                                                                                                                                                         
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api                                                     
    result = await self.adapter._call_api(self, api, **data)                                                                                                                                                
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api                                            
    return handle_api_result(await self._result_store.fetch(seq, timeout))                                                                                                                                  
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-3Q5VN4zz-py3.8/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result                                       
    raise ActionFailed(**result)                                                                                                                                                                            
nonebot.adapters.onebot.v11.exception.ActionFailed`
### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
可能风控
