### ISSUE TITLE
输入“查看词条”无效

### ISSUE THREAD

**Issue by SVIPNB** [HibiKier/zhenxun_bot#1438]
### 日志截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/105286806/70ad0d82-a864-4702-a647-348c2600398f)
![image](https://github.com/HibiKier/zhenxun_bot/assets/105286806/32978333-5282-4191-a86f-5e0da52d049d)
![image](https://github.com/HibiKier/zhenxun_bot/assets/105286806/b9775e12-561f-4b48-9913-7fd6835d06f3)

 nonebot | OneBot V11 2175859082 | [message.group.normal]: Message -1895177235 from 1612744136@[群:1098828852] "查看词条"
05-31 22:56:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
05-31 22:56:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
05-31 22:56:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
05-31 22:56:51 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
05-31 22:56:51 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
05-31 22:56:51 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
05-31 22:56:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.word_bank.word_handle)
05-31 22:56:57 [INFO] nonebot | Matcher(type='message', module=plugins.word_bank.word_handle) running complete
05-31 22:56:57 [ERROR] nonebot | Running Matcher(type='message', module=plugins.word_bank.word_handle) failed.
Traceback (most recent call last):
  File "/home/zhenxun/zhenxun_bot-0.1.6.6/bot.py", line 21, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/zhenxun/zhenxun_bot-0.1.6.6/plugins/word_bank/word_handle.py", line 278, in _
    await bot.send_group_forward_msg(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-2aAlpDgE-py3.10/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed

### 错误说明
在QQ输入“查看词条”，QQ上没反应，系统报错如上

**Comment by HibiKier** [comment]
大概率风控
