### ISSUE TITLE
真寻签到没有任何群内返图

### ISSUE THREAD

**Issue by tangtangebusi** [HibiKier/zhenxun_bot#1449]
### 错误截图
真寻签到没有任何群内返图
![image](https://github.com/HibiKier/zhenxun_bot/assets/67052443/9d25933a-0c78-499e-9594-782b0ccd510a)

### 日志截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/67052443/fcdcd351-b2dd-466e-a961-c852e477548c)
![image](https://github.com/HibiKier/zhenxun_bot/assets/67052443/6a6532f1-be57-445e-a631-1efe2974cd9e)

[img]

### 错误说明
06-10 15:13:08 [SUCCESS] nonebot | OneBot V11 1831646747 | [message.group.normal]: Message 1792915765 from 473893141@[群:767559597] "签到"
06-10 15:13:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
06-10 15:13:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
06-10 15:13:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
06-10 15:13:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
06-10 15:13:08 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
06-10 15:13:08 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
06-10 15:13:08 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
06-10 15:13:08 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
06-10 15:13:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.sign_in)
06-10 15:13:09 [INFO] nonebot | Matcher(type='message', module=plugins.sign_in) running complete
06-10 15:13:09 [ERROR] nonebot | Running Matcher(type='message', module=plugins.sign_in) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Bot\Zhenxun\zhenxun_bot-main\plugins\sign_in\__init__.py", line 117, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
  File "D:\Bot\Zhenxun\zhenxun_bot-main\plugins\sign_in\group_user_checkin.py", line 41, in group_user_check_in
    return await get_card(user, nickname, -1, gold, "")
  File "D:\Bot\Zhenxun\zhenxun_bot-main\plugins\sign_in\utils.py", line 92, in get_card
    return await asyncio.get_event_loop().run_in_executor(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Bot\Zhenxun\zhenxun_bot-main\plugins\sign_in\utils.py", line 128, in _generate_card
    ava = BuildImage(102, 102, background=ava_bytes)
  File "D:\Bot\Zhenxun\zhenxun_bot-main\utils\image_utils.py", line 228, in __init__
    self.markImg = Image.open(background).resize(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-MsiqYiYG-py3.9\lib\site-packages\PIL\Image.py", line 3186, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F9E018ED60>
06-10 15:13:28 [ERROR] services | Id：401742377 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
06-10 15:13:58 [ERROR] services | Id：401742377 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -401, 信息: 非法访问

**Comment by HibiKier** [comment]
应该是签到背景图损坏了
