### ISSUE TITLE
Failed to import "statistics_hook" ImportError: cannot import name 'Optional' from 'nonebot.typing'  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by youyi0218** [HibiKier/zhenxun_bot#1519]
### 日志截图

[img]
![image](https://github.com/HibiKier/zhenxun_bot/assets/135406843/99ad4dd5-0db1-4439-8fa0-0f8a6ab3a922)
![image](https://github.com/HibiKier/zhenxun_bot/assets/135406843/33886248-e159-4f26-bec3-cc861e2d6714)
![image](https://github.com/HibiKier/zhenxun_bot/assets/135406843/3b6f5e17-3b9d-4fce-a33a-0995c90d0a51)

### 错误说明

如标题和图

**Comment by youyi0218** [comment]
后面的日志
  File "D:\Program\zhenxun_bot\services\db_context.py", line 56, in init
    await Tortoise.generate_schemas()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\__init__.py", line 640, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\utils.py", line 31, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\base\schema_generator.py", line 448, in generate_from_string
    await self.client.execute_script(creation_string)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\base_postgres\client.py", line 150, in execute_script
    async with self.acquire_connection() as connection:
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\base\client.py", line 326, in __aenter__
    await self.ensure_connection()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\base\client.py", line 322, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\asyncpg\client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\tortoise\backends\asyncpg\client.py", line 65, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\pool.py", line 403, in _async__init__
    await self._initialize()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\pool.py", line 430, in _initialize
    await first_ch.connect()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\pool.py", line 128, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\pool.py", line 502, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connection.py", line 2329, in connect
    return await connect_utils._connect(
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\asyncpg\connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "D:\python\3.10.11\lib\asyncio\base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "D:\python\3.10.11\lib\asyncio\base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "D:\python\3.10.11\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "D:\python\3.10.11\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\starlette\routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\python\3.10.11\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 152, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 41, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\youyi\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-R0qD1gnV-py3.10\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 35, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\Program\zhenxun_bot\services\db_context.py", line 59, in init
    raise Exception(f"数据库连接错误.... {type(e)}: {e}")
Exception: 数据库连接错误.... <class 'socket.gaierror'>: [Errno 11001] getaddrinfo failed

02-10 21:34:58 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by fuyang0811** [comment]
我也遇见了，通过降低nonebot2版本到2.0.0rc3解决了。
