### ISSUE TITLE
发生签到会报错

### ISSUE THREAD

**Issue by yake1145141** [HibiKier/zhenxun_bot#1544]
### 错误截图

![QQ20240802-011535](https://github.com/user-attachments/assets/5234386e-6974-4574-8e91-ac2e1e660895)

### 日志截图

![QQ20240802-011535](https://github.com/user-attachments/assets/e2d73592-a03e-4a0e-9372-7769bc9fd70f)

### 错误说明

Traceback (most recent call last):
  File "/root/zhenxun_bot-main/bot.py", line 21, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/zhenxun_bot-main/plugins/sign_in/__init__.py", line 117, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
  File "/root/zhenxun_bot-main/plugins/sign_in/group_user_checkin.py", line 31, in group_user_check_in
    user, is_create = await SignGroupUser.get_or_create(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/models.py", line 1059, in get_or_create
    await cls.select_for_update().filter(**kwargs).using_db(connection).get(),
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/queryset.py", line 1008, in _execute
    instance_list = await self._db.executor_class(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 139, in execute_select
    instance: "Model" = self.model._init_from_db(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/models.py", line 742, in _init_from_db
    setattr(self, model_field, field.to_python_value(kwargs[key]))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/fields/data.py", line 365, in to_python_value
    value = timezone.make_aware(value, get_timezone())
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/tortoise/timezone.py", line 97, in make_aware
    return tz.localize(value, is_dst=is_dst)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-8W611JwV-py3.9/lib/python3.9/site-packages/pytz/tzinfo.py", line 323, in localize
    loc_dt = dt + delta
OverflowError: date value out of range

**Comment by yake1145141** [comment]
windows server 2016安装也会出现这个问题

**Comment by HibiKier** [comment]
是新安装的项目吗，如果是的话，可以试试dev里的最新版本
