### ISSUE TITLE
新版DEV进群退群报错

### ISSUE THREAD

**Issue by Nenot233** [HibiKier/zhenxun_bot#1661]
### 错误说明
```
09-30 10:32:15 [ERROR] nonebot | Running Matcher(type='notice', module=zhenxun.builtin_plugins.platform.qq.group_handle, lineno=87) failed.
Traceback (most recent call last):
File "D:\BOT\zhenxun_bot-dev\bot.py", line 32, in <module>
nonebot.run()
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\__init__.py", line 335, in run
get_driver().run(*args, **kwargs)
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
uvicorn.run(
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\uvicorn\main.py", line 577, in run
server.run()
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\uvicorn\server.py", line 65, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
self.run_forever()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
self._run_once()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
handle._run()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
await _run_matcher(
> File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
await matcher.run(bot, event, state, stack, dependency_cache)
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
await self.simple_run(bot, event, state, stack, dependency_cache)
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
await handler(
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
return await cast(Callable[..., Awaitable[R]], self.call)(**values)
File "D:\BOT\zhenxun_bot-dev\zhenxun\builtin_plugins\platform\qq\group_handle\__init__.py", line 122, in _
if result and not await CommonUtils.task_is_block(
File "D:\BOT\zhenxun_bot-dev\zhenxun\utils\common_utils.py", line 21, in task_is_block
if task := await TaskInfo.get_or_none(module=module):
File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\tortoise\queryset.py", line 1022, in _execute
raise MultipleObjectsReturned("Multiple objects returned, expected exactly one")
tortoise.exceptions.MultipleObjectsReturned: Multiple objects returned, expected exactly one
```

**Comment by HibiKier** [comment]
将数据库task_info中的重复数据删掉

**Comment by Nenot233** [comment]
感谢已修复
