### ISSUE TITLE
Bug: 出现异常 web_ui启动报错

### ISSUE THREAD

**Issue by Readedd** [HibiKier/zhenxun_bot#1786]
### 操作系统

Windows

### Python 版本

3.11.0

### zhenxun_bot 版本

0.2.4

### 适配器

onebotv11

### 协议端

4.2.37

### 描述问题

环境，Windows Server 2022 Datacenter 21H2，最新版ntqq通过liteloder加载napcatt，zhenxun最新0.2.4，python版本3.11，bot文件夹为C:\Program Files\zhenxun，在此之前，已经尝试按照文档方法一部署webui，config.yaml已配置，每次启动后都会重置，.env.dev已修改0.0.0.0，启动报错
Failed to import "web_ui"
Traceback (most recent call last):
  File "C:\Program Files\zhenxun\bot.py", line 23, in <module>
    nonebot.load_plugins("zhenxun/builtin_plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-LlnxzTok-py3.11\Lib\site-packages\nonebot\plugin\load.py", line 53, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-LlnxzTok-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 205, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-LlnxzTok-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-LlnxzTok-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 171, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-LlnxzTok-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\zhenxun\zhenxun\builtin_plugins\web_ui\__init__.py", line 25, in <module>
    from .auth import router as auth_router
  File "C:\Program Files\zhenxun\zhenxun\builtin_plugins\web_ui\auth\__init__.py", line 11, in <module>
    from ....base_model import Result
ModuleNotFoundError: No module named 'zhenxun.base_mod

除此之外，bot其他一切正常，

### 复现步骤

启动时发生

### 截图或日志（请勿包含敏感信息如密码、令牌等）

![image](https://github.com/user-attachments/assets/517b822b-113b-4b0c-a17b-4918a23a1671)

**Comment by molanp** [comment]
问题为代码相对路径引导错误，不是很复杂

**Comment by HibiKier** [comment]
更新最新代码
