### ISSUE TITLE
Bug:商店购买的物品无法使用

### ISSUE THREAD

**Issue by ATTomatoo** [HibiKier/zhenxun_bot#1788]
### 操作系统

Linux

### Python 版本

3.10.10

### zhenxun_bot 版本

v0.2.4-e363d29

### 适配器

nonebot v11 2.1.3

### 协议端

NapCat 4.1.5

### 描述问题

zhenxun_bot 的 [feature/refactor-base](https://github.com/HibiKier/zhenxun_bot/tree/feature/refactor-base) 分支中，商店购买的道具无法使用

### 复现步骤

1，更新到feature/refactor-base分支
2，使用道具即可

将shop更新回v0.2.4-c7c759f 中的shop 可以正常使用

### 截图或日志（请勿包含敏感信息如密码、令牌等）
`
12-20 20:45:02 [ERROR] nonebot | Running AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) failed.
Traceback (most recent call last):
  File "/opt/zhenxun_bot-dev/bot.py", line 32, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/__init__.py", line 176, in _
    result = await ShopManage.use(
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 314, in use
    user = await UserConsole.get_user(user_id=session.user.id)
AttributeError: 'Session' object has no attribute 'user'
`

**Comment by HibiKier** [comment]
2c4611fb4664f3df7e526550668d880013e578b1 更新分支

**Comment by ATTomatoo** [comment]
`12-20 21:03:12 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1056894151 from 1126160939@[群:933264645] '使用道具 2'
12-20 21:03:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
12-20 21:03:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-20 21:03:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-20 21:03:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
12-20 21:03:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
12-20 21:03:13 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52)
12-20 21:03:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
12-20 21:03:13 [INFO] nonebot | AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) running complete
12-20 21:03:13 [ERROR] nonebot | Running AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) failed.
Traceback (most recent call last):
  File "/opt/zhenxun_bot-dev/bot.py", line 32, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/__init__.py", line 172, in _
    result = await ShopManage.use(
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 335, in use
    await UserConsole.use_props(session.id1, goods_info.uuid, num, session.platform)  # type: ignore
AttributeError: 'Session' object has no attribute 'id1'. Did you mean: 'id'?
`
还是报错

**Comment by HibiKier** [comment]
在更新试试

**Comment by ATTomatoo** [comment]
可以正常使用了，辛苦作者大大

**Comment by ATTomatoo** [comment]
又出现该问题了，一开始群友签到，指令无反应，跟https://github.com/HibiKier/zhenxun_bot/issues/1769 现象差不多，之后关闭BOT，重新启动之后报错如下

`12-21 00:11:08 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1799806798 from 1126160939@[群:602632179] '使用道具2'
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
12-21 00:11:08 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
12-21 00:11:08 [INFO] nonebot | AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) running complete
12-21 00:11:08 [ERROR] nonebot | Running AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) failed.
Traceback (most recent call last):
  File "/opt/zhenxun_bot-dev/bot.py", line 32, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/__init__.py", line 172, in _
    result = await ShopManage.use(
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 334, in use
    result = await cls.__run(goods, param, session, **kwargs)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 276, in __run
    await goods.func(*cls.__parse_args(args, param, session, **kwargs))
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/sign_in/goods_register.py", line 45, in _
    if session.id1:
AttributeError: 'Session' object has no attribute 'id1'. Did you mean: 'id'?
`

**Comment by ATTomatoo** [comment]
又出现该问题了，一开始群友签到，指令无反应，跟https://github.com/HibiKier/zhenxun_bot/issues/1769 现象差不多，之后关闭BOT，重新启动之后报错如下

`12-21 00:11:08 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1799806798 from 1126160939@[群:602632179] '使用道具2'
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
12-21 00:11:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
12-21 00:11:08 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52)
12-21 00:11:08 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
12-21 00:11:08 [INFO] nonebot | AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) running complete
12-21 00:11:08 [ERROR] nonebot | Running AlconnaMatcher(type='', module=zhenxun.builtin_plugins.shop, lineno=52) failed.
Traceback (most recent call last):
  File "/opt/zhenxun_bot-dev/bot.py", line 32, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-aHa4dPee-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/__init__.py", line 172, in _
    result = await ShopManage.use(
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 334, in use
    result = await cls.__run(goods, param, session, **kwargs)
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/shop/_data_source.py", line 276, in __run
    await goods.func(*cls.__parse_args(args, param, session, **kwargs))
  File "/opt/zhenxun_bot-dev/zhenxun/builtin_plugins/sign_in/goods_register.py", line 45, in _
    if session.id1:
AttributeError: 'Session' object has no attribute 'id1'. Did you mean: 'id'?
`

**Comment by ATTomatoo** [comment]
[2024-12-20.log](https://github.com/user-attachments/files/18212924/2024-12-20.log)
这是无反应时的日志以及在关闭BOT之后一直在报错

**Comment by HibiKier** [comment]
> goods_register

看你这个是旧代码不是分支最新的

**Comment by ATTomatoo** [comment]
我的疏忽，我把之前的导入进去了，现在商店正常了。
无反应应该不是这个照成的把，那个时间我也改了，现在还在观察
