### ISSUE TITLE
pyproject.toml中漏了aiomysql

### ISSUE THREAD

**Issue by kmizmal** [HibiKier/zhenxun_bot#1799]
### 描述问题或主题

Traceback (most recent call last):
  File "/zmal/Poetry/venvs/zhenxun-bot-wY7s-9n3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/zmal/Poetry/venvs/zhenxun-bot-wY7s-9n3-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "/zmal/Poetry/venvs/zhenxun-bot-wY7s-9n3-py3.10/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/zmal/Poetry/venvs/zhenxun-bot-wY7s-9n3-py3.10/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/zmal/zhenxun_bot/zhenxun/services/db_context.py", line 80, in init
    raise DbConnectError(f"数据库连接错误... e:{e}") from e
zhenxun.services.db_context.DbConnectError: 数据库连接错误... e:No module named 'aiomysql'

12-25 02:56:51 [ERROR] uvicorn | Application startup failed. Exiting.

### 需做出的修改

[tool.poetry.dependencies]
aiomysql = "^0.1.0"  # 添加此行

**Comment by BalconyJH** [comment]
感谢您的建议！不过，这个设计是有意为之——项目特意将 `tortoise-orm[asyncpg]` 作为默认的数据库后端。

尽管我们尽量避免依赖特定数据库的独有特性以支持多种数据库类型，但仍决定将非 PostgreSQL 的数据库引擎设置为可选依赖。这样可以保持核心依赖简洁，避免安装不必要的数据库驱动，同时为用户提供选择偏好数据库的灵活性。

如果您需要 MySQL 的支持，可以通过以下命令轻松添加 `aiomysql`：
```bash
pip install aiomysql
```
