### ISSUE TITLE
调用 get_group_list API 时发生超时

### ISSUE THREAD

**Issue by Chang-Tao** [HibiKier/zhenxun_bot#1803]
### 操作系统

Linux

### Python 版本

3.10

### zhenxun_bot 版本

0.2.4

### 适配器

LLOneBot 4.6.1

### 协议端

LLOneBot 4.6.1

### 描述问题

调用 get_group_list API 时发生超时

### 复现步骤

原本机器人运行正常, 突然QQ下线, 要强制更新版本, 
于是我下载最新版NTQQ, QQ安装完成后, 插件加载器无法运行, 一顿操作后, 插件加载器工作正常
然后开始启动机器人, 开始提示API超时, 
我开始重新拉取最新的源代码到本地, 然后更新依赖, 再次启动, 仍然提示API超时

### 期望的结果

希望能够正常运行,  然后和群友愉快的玩耍

### 截图或日志（请勿包含敏感信息如密码、令牌等）

(zhenxun_env310) root@ubuntu:/home/ubuntu/Downloads/zhenxun_bot# python3 bot.py
12-27 14:25:18 [SUCCESS] nonebot | NoneBot is initializing...
12-27 14:25:18 [INFO] nonebot | Current Env: dev
12-27 14:25:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
12-27 14:25:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
12-27 14:25:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
12-27 14:25:20 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
12-27 14:25:20 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
12-27 14:25:20 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
12-27 14:25:20 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
12-27 14:25:20 [INFO] zhenxun | 加载配置完成，共加载 31 个配置组及对应 91 个配置项
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "chat_history:chat_message_handle" from "zhenxun.builtin_plugins.chat_history.chat_message_handle"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "chat_history:chat_message" from "zhenxun.builtin_plugins.chat_history.chat_message"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "chat_history" from "zhenxun.builtin_plugins.chat_history"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "help_help" from "zhenxun.builtin_plugins.help_help"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "check" from "zhenxun.builtin_plugins.check"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "hooks:chkdsk_hook" from "zhenxun.builtin_plugins.hooks.chkdsk_hook"
12-27 14:25:21 [SUCCESS] nonebot | Succeeded to load plugin "hooks:call_hook" from "zhenxun.builtin_plugins.hooks.call_hook"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "hooks:auth_hook" from "zhenxun.builtin_plugins.hooks.auth_hook"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "hooks:ban_hook" from "zhenxun.builtin_plugins.hooks.ban_hook"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "hooks:withdraw_hook" from "zhenxun.builtin_plugins.hooks.withdraw_hook"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "hooks" from "zhenxun.builtin_plugins.hooks"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "withdraw" from "zhenxun.builtin_plugins.withdraw"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "scheduler:auto_update_group" from "zhenxun.builtin_plugins.scheduler.auto_update_group"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "scheduler:chat_check" from "zhenxun.builtin_plugins.scheduler.chat_check"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "scheduler:auto_backup" from "zhenxun.builtin_plugins.scheduler.auto_backup"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "scheduler:morning" from "zhenxun.builtin_plugins.scheduler.morning"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "scheduler" from "zhenxun.builtin_plugins.scheduler"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "nickname" from "zhenxun.builtin_plugins.nickname"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "about" from "zhenxun.builtin_plugins.about"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "statistics:statistics_handle" from "zhenxun.builtin_plugins.statistics.statistics_handle"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "statistics:statistics_hook" from "zhenxun.builtin_plugins.statistics.statistics_hook"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "statistics" from "zhenxun.builtin_plugins.statistics"
12-27 14:25:22 [SUCCESS] nonebot | Succeeded to load plugin "plugin_store" from "zhenxun.builtin_plugins.plugin_store"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "web_ui" from "zhenxun.builtin_plugins.web_ui"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "platform:exception" from "zhenxun.builtin_plugins.platform.qq.exception"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "platform:group_handle" from "zhenxun.builtin_plugins.platform.qq.group_handle"
12-27 14:25:23 [WARNING] zhenxun | 未安装 qq-adapter，无法加载QQ官平台专用插件...
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "platform" from "zhenxun.builtin_plugins.platform"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "plugin_store" from "zhenxun.builtin_plugins.plugin_store"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "info" from "zhenxun.builtin_plugins.info"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "help" from "zhenxun.builtin_plugins.help"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:exec_sql" from "zhenxun.builtin_plugins.superuser.exec_sql"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:bot_manage" from "zhenxun.builtin_plugins.superuser.bot_manage"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:group_manage" from "zhenxun.builtin_plugins.superuser.group_manage"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:request_manage" from "zhenxun.builtin_plugins.superuser.request_manage"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:set_admin" from "zhenxun.builtin_plugins.superuser.set_admin"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:reload_setting" from "zhenxun.builtin_plugins.superuser.reload_setting"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:super_help" from "zhenxun.builtin_plugins.superuser.super_help"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:fg_manage" from "zhenxun.builtin_plugins.superuser.fg_manage"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:broadcast" from "zhenxun.builtin_plugins.superuser.broadcast"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:update_fg_info" from "zhenxun.builtin_plugins.superuser.update_fg_info"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser:clear_data" from "zhenxun.builtin_plugins.superuser.clear_data"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "superuser" from "zhenxun.builtin_plugins.superuser"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "init:init_config" from "zhenxun.builtin_plugins.init.init_config"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "init:init_plugin" from "zhenxun.builtin_plugins.init.init_plugin"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "init:manager" from "zhenxun.builtin_plugins.init.manager"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "init" from "zhenxun.builtin_plugins.init"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "catchphrase" from "zhenxun.builtin_plugins.catchphrase"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "restart" from "zhenxun.builtin_plugins.restart"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "shop" from "zhenxun.builtin_plugins.shop"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "record_request" from "zhenxun.builtin_plugins.record_request"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "auto_update" from "zhenxun.builtin_plugins.auto_update"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "sign_in" from "zhenxun.builtin_plugins.sign_in"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:plugin_switch" from "zhenxun.builtin_plugins.admin.plugin_switch"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:welcome_message" from "zhenxun.builtin_plugins.admin.welcome_message"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:admin_watch" from "zhenxun.builtin_plugins.admin.admin_watch"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:group_update" from "zhenxun.builtin_plugins.admin.group_update"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:admin_help" from "zhenxun.builtin_plugins.admin.admin_help"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:group_member_update" from "zhenxun.builtin_plugins.admin.group_member_update"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin:ban" from "zhenxun.builtin_plugins.admin.ban"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "admin" from "zhenxun.builtin_plugins.admin"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "scripts" from "zhenxun.builtin_plugins.scripts"
/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot_plugin_alconna/matcher.py:208: UserWarning: Shortcut Key should not start with '^', otherwise it will ignore the prefix automatically.
  cls.command().shortcut(key, args, **kwargs)  # type: ignore
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "one_friend" from "zhenxun.plugins.one_friend"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "coser" from "zhenxun.plugins.coser"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "zhenxun_plugin_niuniu" from "zhenxun.plugins.zhenxun_plugin_niuniu"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "quotations" from "zhenxun.plugins.quotations"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "pid_search" from "zhenxun.plugins.pid_search"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word:black_word" from "zhenxun.plugins.black_word.black_word"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word:utils" from "zhenxun.plugins.black_word.utils"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word:black_watch" from "zhenxun.plugins.black_word.black_watch"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word:model" from "zhenxun.plugins.black_word.model"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word:data_source" from "zhenxun.plugins.black_word.data_source"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "black_word" from "zhenxun.plugins.black_word"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "nbnhhsh" from "zhenxun.plugins.nbnhhsh"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "epic" from "zhenxun.plugins.epic"
12-27 14:25:23 [SUCCESS] nonebot | Succeeded to load plugin "group_welcome_msg" from "zhenxun.plugins.group_welcome_msg"
12-27 14:25:23 [SUCCESS] nonebot | Running NoneBot...
12-27 14:25:23 [INFO] uvicorn | Started server process [7662]
12-27 14:25:23 [INFO] uvicorn | Waiting for application startup.
12-27 14:25:23 [INFO] nonebot_plugin_apscheduler | Scheduler Started
12-27 14:25:24 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
12-27 14:25:24 [INFO] nonebot_plugin_htmlrender | Browser Started.
12-27 14:25:24 [INFO] zhenxun | Database loaded successfully!
12-27 14:25:24 [INFO] zhenxun | CMD[WebUi] API启动成功
12-27 14:25:25 [INFO] zhenxun | 已经加载 2 个插件限制.
12-27 14:25:35 [INFO] zhenxun | 开始迁移群欢迎消息数据...
12-27 14:25:35 [SUCCESS] zhenxun | []: 迁移群欢迎消息数据完成! | 参数[] 返回: []
12-27 14:25:35 [INFO] uvicorn | Application startup complete.
12-27 14:25:35 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
12-27 14:25:36 [INFO] uvicorn | ('127.0.0.1', 41970) - "WebSocket /onebot/v11/ws" [accepted]
12-27 14:25:36 [INFO] nonebot | OneBot V11 | Bot 3112013411 connected
12-27 14:25:36 [INFO] websockets | connection open
12-27 14:25:36 [INFO] zhenxun | 初始化Bot管理完成...
12-27 14:25:41 [ERROR] nonebot | Error when running WebSocketConnection hook:
Traceback (most recent call last):
> File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/utils.py", line 238, in run_coro_with_catch
    return await coro
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun/builtin_plugins/init/__init__.py", line 26, in _
    group_list, _ = await PlatformUtils.get_group_list(bot)
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun/utils/platform.py", line 362, in get_group_list
    scenes = await interface.get_scenes(SceneType.GROUP)
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot_plugin_uninfo/params.py", line 79, in get_scenes
    async for scene in self.iter_scenes(scene_type, parent_scene_id=parent_scene_id):
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot_plugin_uninfo/params.py", line 98, in iter_scenes
    async for scene in self.fetcher.query_scenes(self.bot, scene_type, parent_scene_id=parent_scene_id):
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot_plugin_uninfo/adapters/onebot11/main.py", line 162, in query_scenes
    groups = await bot.get_group_list()
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 176, in call_api
    raise exception
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 128, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 175, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/home/ubuntu/Downloads/zhenxun_bot/zhenxun_env310/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []', wording='ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []', echo='1')
12-27 14:30:28 [ERROR] zhenxun | Bot: 3112013411 自动更新群组信息 || 错误 <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>: ActionFailed(status='failed', retcode=1200, data=None, message='ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []', wording='ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []', echo='2')

**Comment by Chang-Tao** [comment]
> ![图片](https://private-user-images.githubusercontent.com/45528451/398871317-860c1548-06b2-41b6-95d8-0630cd179974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTA0MDUsIm5iZiI6MTczNTI5MDEwNSwicGF0aCI6Ii80NTUyODQ1MS8zOTg4NzEzMTctODYwYzE1NDgtMDZiMi00MWI2LTk1ZDgtMDYzMGNkMTc5OTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA5MDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZjliMTQ0YmY5ODc0OTFjODAxMmRlY2YzZjJhM2JiZWI2MmY4MzI5OTdhM2U2ZTkwYTgwOTM5MjBlODA2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gNQME9B76noBBLlJJxUMhxGCYt0HVF8N37w7jgINbcg)

可以啦, 谢谢大佬.
