### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by Pan-Biao** [HibiKier/zhenxun_bot#194]
windows
pythoin3.9
控制台打印如下：

05-17 21:39:13 [ERROR] uvicorn | Traceback (most recent call last):
  File "c:\users\administrator.desktop-3n3qdue\appdata\local\programs\python\python39\lib\asyncio\selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Y:\zhenxun_bot-0.1.5.3\services\db_context.py", line 16, in init
    await db.set_bind(i_bind)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\pool.py", line 413, in _async__init__
    await self._initialize()
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\pool.py", line 441, in _initialize
    await first_ch.connect()
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\asyncpg\compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "c:\users\administrator.desktop-3n3qdue\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "Y:\zhenxun_bot-0.1.5.3\services\db_context.py", line 20, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.ConnectionDoesNotExistError'>: connection was closed in the middle of operation

05-17 21:39:13 [ERROR] uvicorn | Application startup failed. Exiting.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-3N3QDUE\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-IoXdawxR-py3.9\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "c:\users\administrator.desktop-3n3qdue\appdata\local\programs\python\python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

数据库的配置、安装和zhenxun_bot的配置、安装都是按照教程弄的
configs内的配置文件也没有生成

**Comment by Pan-Biao** [comment]
> 



> Windows的话检查下防火墙试试？

关闭了防火墙也是一样的控制台提示

**Comment by Nova-Noir** [comment]
ConnectionDoesNotExistError
推荐再次查看一下数据库是否正常安装，以及数据库的连接是否正确。

**Comment by SIxLonGun** [comment]
我之前也是连不上数据库，但我重新创建了一个用户，给了权限就好了。

![image](https://user-images.githubusercontent.com/23234933/168842653-7e7d1007-9118-4e07-ae5c-394ded33626e.png)

不过我的数据库版本是10.21，服务器系统是windows server 2012 r2

**Comment by Pan-Biao** [comment]
> 我之前也是连不上数据库，但我重新创建了一个用户，给了权限就好了。
> 
> ![image](https://user-images.githubusercontent.com/23234933/168842653-7e7d1007-9118-4e07-ae5c-394ded33626e.png)
> 
> 不过我的数据库版本是10.21，服务器系统是windows server 2012 r2

谢谢！问题解决了，我重新创建了用户，并把权限都给上了，现在已经运行成功！
