### ISSUE TITLE
检查chromium内核后一直报错

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#21]
NotImplementsErr
我都不知道是发生了什么，日志没写

**Comment by yusana213214** [comment]
`Task exception was never retrieved
future: <Task finished name='Task-36' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py:163> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 166, in run
    await self._transport.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 57, in run
    self._proc = proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError`

**Comment by yusana213214** [comment]
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py:163> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 166, in run
    await self._transport.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 57, in run
    self._proc = proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by HibiKier** [comment]
win10系统的问题，建议换成linux，或者删除这个功能 --> 删除/utils/browsers.py和plugins/genshin/material_remind文件夹，并在/plugins/help/config.py中删除键为material_remind的一行
