### ISSUE TITLE
这次是nonebot.log……

### ISSUE THREAD

**Issue by Noob-in-computers** [HibiKier/zhenxun_bot#211]
```
Traceback (most recent call last):
  File "D:\QQBOT研究中\zhenxun_bot-main\bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\adapters\__init__.py", line 25, in <module>
    from nonebot.internal.adapter import Bot as Bot
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\adapter\__init__.py", line 1, in <module>
    from .bot import Bot as Bot
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\adapter\bot.py", line 7, in <module>
    from nonebot.log import logger
ModuleNotFoundError: No module named 'nonebot.log'
```
有没有大佬能帮帮……几乎全都是照着文档写的（捂脸）

===2022-5-18 10:42编辑===
坏了，跟着requirements.txt的配置重整了包，结果……
```
Traceback (most recent call last):
  File "D:\QQBOT研究中\zhenxun_bot-main\bot.py", line 1, in <module>
    import nonebot
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 5, in <module>
    import aiocqhttp
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\__init__.py", line 7, in <module>
    from .app import Quart
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 46, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\debug.py", line 6, in <module>
    from jinja2 import Template
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\markupsafe\__init__.py)
```

**Comment by HibiKier** [comment]
你同时安装了nb1和nb2，卸载nb1，并且现在已经不需要requirements.txt了

**Comment by Noob-in-computers** [comment]
> 你同时安装了nb1和nb2，并且卸载nb1，现在已经不需要requirements.txt了

坏事……卸载了nb1以后又重回ModuleNotFoundError: No module named 'nonebot.log'里
（大悲

**Comment by HibiKier** [comment]
把虚拟环境文件夹删了重新poetry install

**Comment by Noob-in-computers** [comment]
> 把虚拟环境文件夹删了重新poetry install

```
[32m05-18 13:50:37[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | NoneBot is initializing...
[32m05-18 13:50:37[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Current [33m[1mEnv: dev[0m[33m[0m
[32m05-18 13:50:37[0m [[31m[1mERROR[0m] [36m[4mnonebot[0m[36m[0m | [31m[48;2;248;187;208mFailed to import "nonebot_plugin_apscheduler"[0m[31m[0m
[33m[1mTraceback (most recent call last):[0m
  File "<string>", line 1, in <module>
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\idlelib\[0m[32m[1mrun.py[0m", line [33m155[0m, in [35mmain[0m
    [1mret[0m [35m[1m=[0m [1mmethod[0m[1m([0m[35m[1m*[0m[1margs[0m[1m,[0m [35m[1m**[0m[1mkwargs[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\idlelib\[0m[32m[1mrun.py[0m", line [33m548[0m, in [35mruncode[0m
    [1mexec[0m[1m([0m[1mcode[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mlocals[0m[1m)[0m
  File "[32mD:\QQBOT研究中\zhenxun_bot-main\[0m[32m[1mbot.py[0m", line [33m12[0m, in [35m<module>[0m
    [1mnonebot[0m[35m[1m.[0m[1mload_plugin[0m[1m([0m[36m"nonebot_plugin_apscheduler"[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\[0m[32m[1mload.py[0m", line [33m28[0m, in [35mload_plugin[0m
    [35m[1mreturn[0m [1mmanager[0m[35m[1m.[0m[1mload_plugin[0m[1m([0m[1mmodule_path[0m[1m)[0m
> File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\[0m[32m[1mmanager.py[0m", line [33m104[0m, in [35mload_plugin[0m
    [1mmodule[0m [35m[1m=[0m [1mimportlib[0m[35m[1m.[0m[1mimport_module[0m[1m([0m[1mname[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\importlib\[0m[32m[1m__init__.py[0m", line [33m127[0m, in [35mimport_module[0m
    [35m[1mreturn[0m [1m_bootstrap[0m[35m[1m.[0m[1m_gcd_import[0m[1m([0m[1mname[0m[1m[[0m[1mlevel[0m[1m:[0m[1m][0m[1m,[0m [1mpackage[0m[1m,[0m [1mlevel[0m[1m)[0m
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[31m[1mModuleNotFoundError[0m:[1m No module named 'nonebot_plugin_apscheduler'[0m
[32m05-18 13:50:38[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mnickname[0m"
[32m05-18 13:50:39[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmy_props[0m"
[32m05-18 13:50:40[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mshop[0m"
[32m05-18 13:50:41[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mupdate_info[0m"
[32m05-18 13:50:42[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33madmin_config[0m"
[32m05-18 13:50:42[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33madmin_bot_manage[0m"
[32m05-18 13:50:43[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mexec_sql[0m"
[32m05-18 13:50:44[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msuper_cmd[0m"
[32m05-18 13:50:44[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mchat_message[0m"
[32m05-18 13:50:45[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mchat_history[0m"
[32m05-18 13:50:45[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mhooks[0m"
[32m05-18 13:50:46[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mgroup_welcome_msg[0m"
[32m05-18 13:50:46[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mstatistics[0m"
[32m05-18 13:50:47[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mabout[0m"
[32m05-18 13:50:47[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mwithdraw[0m"
[32m05-18 13:50:48[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mimage_management[0m"
[32m05-18 13:50:49[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mroll[0m"
[32m05-18 13:50:50[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msend_dinggong_voice[0m"
[32m05-18 13:50:51[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33malapi[0m"
[32m05-18 13:50:51[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mpix_gallery[0m"
[32m05-18 13:50:53[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mquery_user[0m"
[32m05-18 13:50:54[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mgenshin[0m"
[32m05-18 13:50:54[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmodel[0m"
[32m05-18 13:50:55[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mword_bank[0m"
[32m05-18 13:50:56[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmy_info[0m"
[32m05-18 13:50:56[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msend_setu_[0m"
[32m05-18 13:50:57[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Running NoneBot...
[32m05-18 13:50:57[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Started server process [33172]
[32m05-18 13:50:58[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Waiting for application startup.
[32m05-18 13:50:58[0m [[31m[1mERROR[0m] [36m[4muvicorn[0m[36m[0m | Application startup failed. Exiting.
```

感谢您的解答，那请问，出现这种情况是正常的吗？

**Comment by MingxuanGame** [comment]
>   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
�[31m�[1mModuleNotFoundError�[0m:�[1m No module named 'nonebot_plugin_apscheduler'�[0m

@Noob-in-computers 你没装定时任务 

```bash
poetry install
# 或者
poetry shell
pip install nonebot_plugin_apscheduler
```

**Comment by Noob-in-computers** [comment]
> > File "", line 973, in _find_and_load_unlocked
> > �[31m�[1mModuleNotFoundError�[0m:�[1m No module named 'nonebot_plugin_apscheduler'�[0m
> 
> @Noob-in-computers 你没装定时任务
> 
> ```shell
> poetry install
> # 或者
> poetry shell
> pip install nonebot_plugin_apscheduler
> ```

我尝试用了poetry shell + pip install nonebot_plugin_apscheduler，但是……
```
[32m05-18 14:58:51[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | NoneBot is initializing...
[32m05-18 14:58:51[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Current [33m[1mEnv: dev[0m[33m[0m
[32m05-18 14:58:52[0m [[31m[1mERROR[0m] [36m[4mnonebot[0m[36m[0m | [31m[48;2;248;187;208mFailed to import "nonebot_plugin_apscheduler"[0m[31m[0m
[33m[1mTraceback (most recent call last):[0m
  File "<string>", line 1, in <module>
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\idlelib\[0m[32m[1mrun.py[0m", line [33m155[0m, in [35mmain[0m
    [1mret[0m [35m[1m=[0m [1mmethod[0m[1m([0m[35m[1m*[0m[1margs[0m[1m,[0m [35m[1m**[0m[1mkwargs[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\idlelib\[0m[32m[1mrun.py[0m", line [33m548[0m, in [35mruncode[0m
    [1mexec[0m[1m([0m[1mcode[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mlocals[0m[1m)[0m
  File "[32mD:\QQBOT研究中\zhenxun_bot-main\[0m[32m[1mbot.py[0m", line [33m12[0m, in [35m<module>[0m
    [1mnonebot[0m[35m[1m.[0m[1mload_plugin[0m[1m([0m[36m"nonebot_plugin_apscheduler"[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\[0m[32m[1mload.py[0m", line [33m28[0m, in [35mload_plugin[0m
    [35m[1mreturn[0m [1mmanager[0m[35m[1m.[0m[1mload_plugin[0m[1m([0m[1mmodule_path[0m[1m)[0m
> File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\[0m[32m[1mmanager.py[0m", line [33m104[0m, in [35mload_plugin[0m
    [1mmodule[0m [35m[1m=[0m [1mimportlib[0m[35m[1m.[0m[1mimport_module[0m[1m([0m[1mname[0m[1m)[0m
  File "[32mC:\Users\天选初号机\AppData\Local\Programs\Python\Python38\lib\importlib\[0m[32m[1m__init__.py[0m", line [33m127[0m, in [35mimport_module[0m
    [35m[1mreturn[0m [1m_bootstrap[0m[35m[1m.[0m[1m_gcd_import[0m[1m([0m[1mname[0m[1m[[0m[1mlevel[0m[1m:[0m[1m][0m[1m,[0m [1mpackage[0m[1m,[0m [1mlevel[0m[1m)[0m
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[31m[1mModuleNotFoundError[0m:[1m No module named 'nonebot_plugin_apscheduler'[0m
[32m05-18 14:58:53[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mupdate_info[0m"
[32m05-18 14:58:54[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mhooks[0m"
[32m05-18 14:58:54[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmy_props[0m"
[32m05-18 14:58:55[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mshop[0m"
[32m05-18 14:58:56[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33madmin_config[0m"
[32m05-18 14:58:57[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33madmin_bot_manage[0m"
[32m05-18 14:58:57[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mexec_sql[0m"
[32m05-18 14:58:58[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msuper_cmd[0m"
[32m05-18 14:58:58[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mchat_message[0m"
[32m05-18 14:58:59[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mchat_history[0m"
[32m05-18 14:58:59[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mnickname[0m"
[32m05-18 14:59:00[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msend_setu_[0m"
[32m05-18 14:59:01[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mabout[0m"
[32m05-18 14:59:01[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmodel[0m"
[32m05-18 14:59:02[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mword_bank[0m"
[32m05-18 14:59:02[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mgroup_welcome_msg[0m"
[32m05-18 14:59:03[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mpix_gallery[0m"
[32m05-18 14:59:04[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mstatistics[0m"
[32m05-18 14:59:04[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmy_info[0m"
[32m05-18 14:59:06[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33malapi[0m"
[32m05-18 14:59:06[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mwithdraw[0m"
[32m05-18 14:59:06[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mimage_management[0m"
[32m05-18 14:59:07[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33msend_dinggong_voice[0m"
[32m05-18 14:59:08[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mroll[0m"
[32m05-18 14:59:09[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mquery_user[0m"
[32m05-18 14:59:09[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mgenshin[0m"
[32m05-18 14:59:11[0m [[32m[1mSUCCESS[0m] [36m[4mnonebot[0m[36m[0m | Running NoneBot...
[32m05-18 14:59:11[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Started server process [28580]
[32m05-18 14:59:11[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Waiting for application startup.
[32m05-18 14:59:12[0m [[31m[1mERROR[0m] [36m[4muvicorn[0m[36m[0m | Application startup failed. Exiting.
```

**Comment by Noob-in-computers** [comment]
对了，顺便我想问一下，在我运行go-cqhttp的时候一直会弹出[2022-05-18 15:51:07] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: websocket: bad handshake，请问这是怎么回事……

**Comment by HibiKier** [comment]
> 对了，顺便我想问一下，在我运行go-cqhttp的时候一直会弹出[2022-05-18 15:51:07] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: websocket: bad handshake，请问这是怎么回事……

你bot没开

**Comment by Noob-in-computers** [comment]
> > 对了，顺便我想问一下，在我运行go-cqhttp的时候一直会弹出[2022-05-18 15:51:07] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: websocket: bad handshake，请问这是怎么回事……
> 
> 你bot没开

![image](https://user-images.githubusercontent.com/105729522/169185678-aa5f6155-f2f8-43ee-914f-0b0149f94d2f.png)
![image](https://user-images.githubusercontent.com/105729522/169185943-b3331336-3538-4385-b481-e8a1a3050f4a.png)
您可以看看为什么会出现这些情况吗？我这次开了个新的副本，重新配置了虚拟环境，将gohttp和真寻合并在根目录，但是还是不太行……

**Comment by MingxuanGame** [comment]
不要使用 IDLE

请使用终端，例如 `cmd` 或 `powershell`

**Comment by Noob-in-computers** [comment]
> 不要使用 IDLE
> 
> 请使用终端，例如 `cmd` 或 `powershell`
> 
> 然后重新上传日志

![image](https://user-images.githubusercontent.com/105729522/169187049-7e8f04ba-d5d7-4788-a01b-fbad8b854212.png)
是这样吗？

**Comment by Noob-in-computers** [comment]
> > > 不要使用 IDLE
> > > 请使用终端，例如 `cmd` 或 `powershell`
> > > 然后重新上传日志
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/105729522/169187049-7e8f04ba-d5d7-4788-a01b-fbad8b854212.png) 是这样吗？
> 
> python bot.py 即可

![image](https://user-images.githubusercontent.com/105729522/169187238-638268bd-c25d-4534-a518-96b5c41c1df5.png)
变成了这样……

**Comment by HibiKier** [comment]
python shell
python bot.py

**Comment by Noob-in-computers** [comment]
> python shell python bot.py

![image](https://user-images.githubusercontent.com/105729522/169262291-4cd151fd-3d8e-4c75-b709-5b6bed766901.png)
谢谢，但是我尝试了一下，好像动不了……

**Comment by HibiKier** [comment]
> > python shell python bot.py
> 
> ![image](https://user-images.githubusercontent.com/105729522/169262291-4cd151fd-3d8e-4c75-b709-5b6bed766901.png) 谢谢，但是我尝试了一下，好像动不了……

你输的什么，python shell都出来了

**Comment by H3d9** [comment]
> > 你同时安装了nb1和nb2，并且卸载nb1，现在已经不需要requirements.txt了
> 
> 坏事……卸载了nb1以后又重回ModuleNotFoundError: No module named 'nonebot.log'里 （大悲

在虚拟环境执行pip3 uninstall nonebot2，然后退出虚拟环境再执行poetry install，然后再进虚拟环境开机器人就可以了。
