### ISSUE TITLE
加载不了

### ISSUE THREAD

**Issue by himenekocn** [HibiKier/zhenxun_bot#22]
看了下文件存在，但是加载不了

E:\bot\pythonbot\zhenxun>python bot.py
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from services.db_context import init, disconnect
ModuleNotFoundError: No module named 'services.db_context'

**Comment by HibiKier** [comment]
试试在services文件夹下新建__init__.py
```python
from .db_context import *
from .log import *
from .service_config import *
```

**Comment by himenekocn** [comment]
> 试试在services文件夹下新建__init__.py
> 
> ```python
> from .db_context import *
> from .log import *
> from .service_config import *
> ```

08-04 16:44:30 [ERROR] nonebot | Failed to import "draw_card"
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    nonebot.load_plugins("plugins")
  File "E:\python\lib\site-packages\nonebot\plugin\__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "E:\python\lib\site-packages\nonebot\plugin\__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "E:\python\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "E:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "E:\python\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\bot\pythonbot\zhenxun\plugins\draw_card\__init__.py", line 5, in <module>
    from .genshin_handle import genshin_draw, update_genshin_info, reset_count, reload_genshin_pool
  File "E:\python\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "E:\bot\pythonbot\zhenxun\plugins\draw_card\genshin_handle.py", line 5, in <module>
    from .update_game_info import update_info
  File "E:\python\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "E:\bot\pythonbot\zhenxun\plugins\draw_card\update_game_info.py", line 7, in <module>
    from .util import download_img
  File "E:\python\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "E:\bot\pythonbot\zhenxun\plugins\draw_card\util.py", line 13, in <module>
    from utils.image_utils import CreateImg
  File "E:\bot\pythonbot\zhenxun\utils\image_utils.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "E:\python\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "E:\python\lib\site-packages\matplotlib\rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "E:\python\lib\site-packages\matplotlib\colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "E:\python\lib\site-packages\matplotlib\scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "E:\python\lib\site-packages\matplotlib\ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "E:\python\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: 找不到指定的模块。

**Comment by HibiKier** [comment]
环境问题？试试下载 https://www.microsoft.com/zh-CN/download/details.aspx?id=48145

**Comment by himenekocn** [comment]
> 环境问题？试试下载 https://www.microsoft.com/zh-CN/download/details.aspx?id=48145

好了，谢谢
