### ISSUE TITLE
原神插件问题

### ISSUE THREAD

**Issue by himenekocn** [HibiKier/zhenxun_bot#23]
08-04 18:32:00 [ERROR] uvicorn | Traceback (most recent call last):
  File "E:\python\lib\site-packages\starlette\routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "E:\python\lib\site-packages\starlette\routing.py", line 467, in default_lifespan
    await self.startup()
  File "E:\python\lib\site-packages\starlette\routing.py", line 502, in startup
    await handler()
  File "E:\bot\pythonbot\zhenxun\plugins/genshin\query_resource_points\query_resource.py", line 89, in init
    await download_map_init(session, semaphore, MAP_RATIO, flag)
  File "E:\bot\pythonbot\zhenxun\plugins/genshin\query_resource_points\query_resource.py", line 156, in download_map_init
    if os.path.getsize(_map) > 1024 * 1024 * 30:
  File "E:\python\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'E:\\bot\\pythonbot\\zhenxun\\resources\\img\\genshin\\map\\map.png'

**Comment by HibiKier** [comment]
收到，已修

**Comment by himenekocn** [comment]
为什么有一些群管才能做到的开关，普通群员可以用

**Comment by himenekocn** [comment]
> 收到，已修

而且我设置cookie显示我不是管理

**Comment by HibiKier** [comment]
设置cookie需要超级用户才能做触发，是否在env.dev中配置了自己的QQ？开关的话是需要2级权限的，如果有问题的话我今晚查看

**Comment by himenekocn** [comment]
> 设置cookie需要超级用户才能做触发，是否在env.dev中配置了自己的QQ？开关的话是需要2级权限的，如果有问题的话我今晚查看

设置了，但是显示不是管理

**Comment by HibiKier** [comment]
能否提供一下日志和聊天截图？非超级用户调用 更新cookie 是不会有任何提示和回复（因为根本不会触发），超级用户调用 更新cookie 是可以直接设置的

**Comment by himenekocn** [comment]
> 能否提供一下日志和聊天截图？非超级用户调用 更新cookie 是不会有任何提示和回复（因为根本不会触发），超级用户调用 更新cookie 是可以直接设置的
https://cdn.himeneko.cn/get/1/image/QQ%E5%9B%BE%E7%89%8720210805180549.png
https://cdn.himeneko.cn/get/1/image/QQ%E6%88%AA%E5%9B%BE20210805180533.png

**Comment by HibiKier** [comment]
。。。。。。你这是ai对话啊，，命令是 ‘更新cookie’
