### ISSUE TITLE
识图功能报错

### ISSUE THREAD

**Issue by Slinet6056** [HibiKier/zhenxun_bot#254]
用的树莓派4B，系统是Ubuntu Server 22.04 64位，Python版本3.9.12，SauceNAO的API也填了
错误日志：
```
05-18 19:02:02 [SUCCESS] nonebot | ONEBOT V11 1492737112 | [message.group.normal]: Message -1670527931 from 492829253@[群:1064413464] "识图"
05-18 19:02:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-18 19:02:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-18 19:02:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-18 19:02:02 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-18 19:02:02 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-18 19:02:02 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-18 19:02:02 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-18 19:02:02 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-18 19:02:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.search_image, type=message, priority=5, temp=False>
05-18 19:02:02 [INFO] nonebot | Matcher <Matcher from plugins.search_image, type=message, priority=5, temp=False> running complete
05-18 19:02:09 [SUCCESS] nonebot | ONEBOT V11 1492737112 | [message.group.normal]: Message 1919133033 from 492829253@[群:1064413464] "[CQ:image,file=2d4cc4ff28b47295e28ef3f71bd61498.image,url=https://gchat.qpic.cn/gchatpic_new/492829253/1064413464-2953015650-2D4CC4FF28B47295E28EF3F71BD61498/0?term=3,subType=0]"
05-18 19:02:09 [INFO] nonebot | Event will be handled by <Matcher from plugins.search_image, type=message, priority=0, temp=True>
05-18 19:02:09 [INFO] nonebot | Matcher <Matcher from plugins.search_image, type=message, priority=0, temp=True> running complete
05-18 19:02:09 [ERROR] nonebot | Running matcher <Matcher from plugins.search_image, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "/home/pi/Projects/zhenxun_bot/bot.py", line 20, in <module>
    nonebot.run()
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/pi/.pyenv/versions/3.9.12/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/__init__.py", line 77, in _
    msg = await get_image_info(mod, img)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/__init__.py", line 43, in get_image_info
    return await get_saucenao_image(url)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/saucenao.py", line 26, in get_saucenao_image
    data = (await AsyncHttpx.post(API_URL_SAUCENAO, params=params)).json()
  File "/home/pi/Projects/zhenxun_bot/utils/http_utils.py", line 99, in post
    return await client.post(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1820, in post
    return await self.request(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 72, in start_tls
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 63, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 100, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 108, in _call_sslobject_method
    result = func(*args)
  File "/home/pi/.pyenv/versions/3.9.12/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
```
请问下是怎么回事呢

**Comment by Coder-Sakura** [comment]
openssl旧版本的问题吧，之前有遇过类似的，试试更新

查看openssl版本
```
ssl.OPENSSL_VERSION
```

**Comment by 181860143** [comment]
借问一下，SauceNAO的API在哪里填，要填什么？

**Comment by Slinet6056** [comment]
> 借问一下，SauceNAO的API在哪里填，要填什么？

第一次运行以后生成的配置文件，`configs/config.yaml` 里面，大概300多行
申请地址[https://saucenao.com/user.php?page=search-api](https://saucenao.com/user.php?page=search-api)

**Comment by Slinet6056** [comment]
我把系统换成了Ubuntu Server 20.04，OpenSSL版本1.1.1f
现在错误变了，我在路由器上挂了代理，但试了下不管开关都会报错
```
05-19 17:59:51 [INFO] nonebot | Event will be handled by <Matcher from plugins.search_image, type=message, priority=0, temp=True>
05-19 17:59:52 [INFO] nonebot | Matcher <Matcher from plugins.search_image, type=message, priority=0, temp=True> running complete
05-19 17:59:52 [ERROR] nonebot | Running matcher <Matcher from plugins.search_image, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/anyio/streams/tls.py", line 108, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 72, in start_tls
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 63, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/anyio/streams/tls.py", line 100, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/anyio/streams/tls.py", line 129, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 72, in start_tls
    raise exc
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    nonebot.run()
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/__init__.py", line 77, in _
    msg = await get_image_info(mod, img)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/__init__.py", line 43, in get_image_info
    return await get_saucenao_image(url)
  File "/home/pi/Projects/zhenxun_bot/plugins/search_image/saucenao.py", line 26, in get_saucenao_image
    data = (await AsyncHttpx.post(API_URL_SAUCENAO, params=params)).json()
  File "/home/pi/Projects/zhenxun_bot/utils/http_utils.py", line 99, in post
    return await client.post(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1820, in post
    return await self.request(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pi/.cache/pypoetry/virtualenvs/zhenxun-bot-AIrsr75c-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
```

**Comment by Slinet6056** [comment]
应该还是网络问题，我加了规则，让 `pixiv.re` 和 `saucenao.com` 两个域名走代理，就没问题了
之前 Ubuntu22.04 装依赖会提示有的包找不到，可能是有兼容问题
