### ISSUE TITLE
在虚拟环境，数据库、go-cqhttp也连接成功，但是启动失败，操作系统是Ubuntu  20.04 64位，求解

### ISSUE THREAD

**Issue by CaZcz** [HibiKier/zhenxun_bot#261]
![image](https://user-images.githubusercontent.com/101175748/169034661-29b8cc24-fe59-4e66-9888-1317d0a68945.png)
![image](https://user-images.githubusercontent.com/101175748/169034190-5fc92a04-8ad5-493c-99ea-a55dfb9273ca.png)

**Comment by woaoaj** [comment]
同问这个uvicon，整了一天了，顺便问下楼主数据库是怎么弄的？

**Comment by MingxuanGame** [comment]
如果您已经解决了问题

恳请点击一下这个按钮将此 issue 关闭

![image](https://user-images.githubusercontent.com/68982190/169042615-c6b1148f-5cb7-4af1-a27a-66d75d6220ef.png)

**Comment by CaZcz** [comment]
我发现我在config.yaml添加了alapi的token才报错，是为什么呢？
05-18 21:11:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 600, in startup
    handler()
  File "/root/zhenxun_bot-0.1.5.3/basic_plugins/init_plugin_config/__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "/root/zhenxun_bot-0.1.5.3/basic_plugins/init_plugin_config/init_plugins_config.py", line 99, in init_plugins_config
    if _data.get(plugin) and k in _data[plugin].keys():
AttributeError: 'str' object has no attribute 'keys'

![image](https://user-images.githubusercontent.com/101175748/169048164-6ad8368a-28ad-4799-b47a-373fc3532665.png)

**Comment by CaZcz** [comment]
莫名奇妙又好了（
*注意，填api、token的时候:冒号后面要接一个空格
