### ISSUE TITLE
运行bot的时候出现下面错误怎么搞

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#268]
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "D:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\python\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\bot\.\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
  File "F:\bot\.\services\__init__.py", line 1, in <module>
    from .db_context import *
  File "F:\bot\.\services\db_context.py", line 4, in <module>
    from configs.config import bind, sql_name, user, password, address, port, database
  File "F:\bot\.\configs\config.py", line 3, in <module>
    from .utils import ConfigsManager
  File "F:\bot\.\configs\utils\__init__.py", line 3, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'

**Comment by MingxuanGame** [comment]
你依赖没有装全

```bash
pip install poetry
poetry install
poetry shell
playwright install chromium
python bot.py
```

**Comment by 80546033** [comment]
> 
第四个
'playwright' 不是内部或外部命令，也不是可运行的程序
或批处理文件

**Comment by 80546033** [comment]
> 你没有装全
> 
> ```shell
> pip install poetry
> poetry install
> poetry shell
> playwright install chromium
> python bot.py
> ```

第四个装的时候提示
D:\python\Scripts>playwright install chromium
'playwright' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by MingxuanGame** [comment]
使用 `python -m playwright` 替代 `playwright`

**Comment by 80546033** [comment]
> 

还是不行，说没有这个东西
D:\python\python.exe: No module named playwright

**Comment by 80546033** [comment]
> > > 
> > 
> > 
> > 还是不行，说没有这个东西 D:\python\python.exe: No module named playwright
> 
> 那你的环境应该是没进去
> 
> ```shell
> poetry shell
> ```

![image](https://user-images.githubusercontent.com/67412155/169046433-53f5e377-d475-4e90-aabc-60994cf1bc5a.png)
这样的

**Comment by MingxuanGame** [comment]
> > > > 
> > > 
> > > 
> > > 还是不行，说没有这个东西 D:\python\python.exe: No module named playwright
> > 
> > 
> > 那你的环境应该是没进去
> > ```shell
> > poetry shell
> > ```
> 
> ![image](https://user-images.githubusercontent.com/67412155/169046433-53f5e377-d475-4e90-aabc-60994cf1bc5a.png) 这样的

前往机器人所在的文件夹

重新执行下面的命令 

> 你依赖没有装全
> 
> ```shell
> pip install poetry
> poetry install
> poetry shell
> playwright install chromium
> python bot.py
> ```
