### ISSUE TITLE
更新到0.0.2-x以后出现的admin_bot_manage问题

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#27]
08-11 16:20:28 [ERROR] nonebot | Failed to import "admin_bot_manage"
Traceback (most recent call last):
  File "C:\zhenxun_bot\bot.py", line 12, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\zhenxun_bot\plugins\admin_bot_manage\__init__.py", line 10, in <module>
    export = export()
TypeError: __call__() missing 1 required positional argument: 'func'

OS windows server 2019

**Comment by HibiKier** [comment]
nonebot2版本是？

**Comment by HibiKier** [comment]
nonebot2版本是？

**Comment by yusana213214** [comment]
> nonebot2版本是？

20.0.0a13-post1

**Comment by HibiKier** [comment]
无法复现，试试在admin_bot_manage文件夹下新建一个__init__.py

**Comment by yusana213214** [comment]
> 无法复现，试试在admin_bot_manage文件夹下新建一个__init__.py

内容呢?总不能是个空文件吧

**Comment by HibiKier** [comment]
就是空文件啊

**Comment by HibiKier** [comment]
bot.py里已经用nonebot.load_plugins单独加载admin_bot_manage目录下的插件了

**Comment by yusana213214** [comment]
> 就是空文件啊

大佬有个疑问，色图每日更新总是保错

2021-08-14 04:31:07 更新 色图 完成，本地存在 100 张，实际更新 -133 张，以下为更新时未知错误：
更新色图 99.jpg 错误 <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\zhenxun_bot\\resources\\img//rar/99.jpg'

**Comment by HibiKier** [comment]
第一个问题需要报错的截图，第二个问题会在下次更新完善
