### ISSUE TITLE
识番功能报错，ValueError: Expected object or value

### ISSUE THREAD

**Issue by CaZcz** [HibiKier/zhenxun_bot#292]
05-18 23:00:53 [SUCCESS] nonebot | ONEBOT V11 3184795568 | [message.group.normal]: Message 843373298 from 1029456251@[群:974246150] "识番[CQ:image,file=07ba5fcd05b415d8eb5b424984a65398.image,url=https://gchat.qpic.cn/gchatpic_new/1029456251/974246150-2354157870-07BA5FCD05B415D8EB5B424984A65398/0?term=3,subType=0]"
05-18 23:00:53 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-18 23:00:53 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-18 23:00:53 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-18 23:00:53 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-18 23:00:53 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-18 23:00:53 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-18 23:00:53 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-18 23:00:54 [INFO] utils | 下载 https://gchat.qpic.cn/gchatpic_new/1029456251/974246150-2354157870-07BA5FCD05B415D8EB5B424984A65398/0?term=3 成功.. Path：/root/zhenxun_bot-0.1.5.3/resources/temp/mute_974246150_img.jpg
05-18 23:00:54 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-18 23:00:55 [INFO] nonebot | Event will be handled by <Matcher from plugins.what_anime, type=message, priority=5, temp=False>
05-18 23:00:55 [INFO] nonebot | Matcher <Matcher from plugins.what_anime, type=message, priority=5, temp=False> running complete
05-18 23:00:55 [ERROR] nonebot | Running matcher <Matcher from plugins.what_anime, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Myqk8QUN-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/zhenxun_bot-0.1.5.3/plugins/what_anime/__init__.py", line 42, in _
    img_url = get_message_img(img_url)
  File "/root/zhenxun_bot-0.1.5.3/utils/utils.py", line 222, in get_message_img
    data = json.loads(data)
ValueError: Expected object or value

**Comment by HibiKier** [comment]
确实是，算是适配b2忘记改了

**Comment by Li-Fish** [comment]
我也遇到了这个问题，尝试这么修改后正常了
![image](https://user-images.githubusercontent.com/25769071/169253160-e1544308-45b3-40f2-a748-f818c3a9a435.png)
