### ISSUE TITLE
更新价格时出现报错

### ISSUE THREAD

**Issue by RandomEnch** [HibiKier/zhenxun_bot#3]
07-05 18:33:36 [INFO] nonebot | CQHTTP 1395670550 | [message.private.friend]: Message 738280846 from 1048421623 "更新价 格 光谱"
07-05 18:33:36 [INFO] nonebot | Event will be handled by <Matcher from mute, type=message, priority=1, temp=False>
07-05 18:33:36 [INFO] nonebot | Event will be handled by <Matcher from open_cases, type=message, priority=1, temp=False>
07-05 18:33:36 [INFO] nonebot | Matcher <Matcher from mute, type=message, priority=1, temp=False> running complete
07-05 18:33:36 [INFO] nonebot | Matcher <Matcher from open_cases, type=message, priority=1, temp=False> running complete
07-05 18:33:36 [ERROR] nonebot | Running matcher <Matcher from open_cases, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python39\lib\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\program files\python39\lib\site-packages\nb_cli\handlers\deploy.py", line 23, in run_bot
    nonebot.run()
  File "c:\program files\python39\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\program files\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\program files\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\program files\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\program files\python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\program files\python39\lib\site-packages\nonebot\matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "c:\program files\python39\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "plugins\open_cases\__init__.py", line 162, in _
    await update_price.send(await util_get_buff_price(str(event.get_message())))
  File "plugins\open_cases\utils.py", line 42, in util_get_buff_price
    CASE_KNIFE = eval(case + "_CASE_KNIFE")
  File "<string>", line 1, in <module>
NameError: name 'GUANGPU_CASE_KNIFE' is not defined

**Comment by HibiKier** [comment]
在plugins/open_cases/utils.py上方添加from .config import *

**Comment by RandomEnch** [comment]
解决了，顺便提一下，识番的api改格式和地址了现在不好使了

**Comment by HibiKier** [comment]
收到，明天改一改

**Comment by RandomEnch** [comment]
另外p搜功能会有ssl报错，不过我修好了

**Comment by RandomEnch** [comment]
另外p搜功能会有ssl报错，不过我修好了

**Comment by RandomEnch** [comment]
另外p搜功能会有ssl报错，不过我修好了

**Comment by HibiKier** [comment]
ssl是代理问题？我这里是正常使用的

**Comment by RandomEnch** [comment]
我加了个aiohttp.TCPConnector(verify_ssl=False)无视了

**Comment by RandomEnch** [comment]
再问一下这个上车怎么使啊，不管输入什么都是没找到

**Comment by HibiKier** [comment]
hhhhh，可以，不过buff更新没有限制频率，要小心账号api被封掉

**Comment by RandomEnch** [comment]
了解

**Comment by HibiKier** [comment]
原来是查找小黄油的，刚刚访问了一下灵梦御所，好像是网站裂开了

**Comment by RandomEnch** [comment]
网站倒是没裂开，就是多了个这玩意，密码是⑨
![A1D6392E-B119-4B05-8381-FDFF2884CFD8](https://user-images.githubusercontent.com/79776324/124503015-3cb3a980-ddf7-11eb-8a39-47607237ad6d.jpeg)

**Comment by HibiKier** [comment]
这样，我还以为是网站裂开，有空修一修
