### ISSUE TITLE
报错：好友消息发送失败: 消息为空

### ISSUE THREAD

**Issue by RealKiro** [HibiKier/zhenxun_bot#31]
- 描述:
  - 发送`coser` `cos` 指令报如下错误
    - `go-cqhttp`
      ```
      [2021-08-21 15:13:33] [INFO]: 收到好友 Kiro君(1663272573) 的消息: coser (245605030)                                                                             
      [2021-08-21 15:13:33] [WARNING]: 好友消息发送失败: 消息为空.
      ```
    - `zhenxun_bot`
      ```
            08-21 15:13:33 [INFO] nonebot | CQHTTP 180043916 | [message.private.friend]: Mes
            sage 245605030 from 1663272573 "coser"                                          
            08-21 15:13:33 [INFO] nonebot | Event will be handled by <Matcher from mute, typ
            e=message, priority=1, temp=False>                                              
            08-21 15:13:33 [INFO] nonebot | Matcher <Matcher from mute, type=message, priori
            ty=1, temp=False> running complete                                              
            08-21 15:13:33 [INFO] nonebot | Event will be handled by <Matcher from coser, ty
            pe=message, priority=5, temp=False>                                             
            [2021-08-21 15:13:33,685] - message_builder.py[line:42] - WARNING: 图片 /zhenxun
            _bot/resources/img/<html>                                                       
            <head><title>404 Not Found</title></head>                                       
            <body>                                                                          
            <center><h1>404 Not Found</h1></center>                                         
            <hr><center>nginx</center>                                                      
            </body>                                                                         
            </html>                                                                         
            .jpg缺失...                                                                     
            08-21 15:13:33 [INFO] nonebot | Matcher <Matcher from coser, type=message, prior
            ity=5, temp=False> running complete                                             
            1mapi, **data)                                                                  
              File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/cqhttp/bot.py", 
            line 346, in _call_api                                                          
                return _handle_api_result(await ResultStore.fetch(                          
              File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/cqhttp/bot.py", 
            line 187, in _handle_api_result                                                 
                raise ActionFailed(**result)                                                
            nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'
            seq': 2}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-
            cqhttp 端输出>                                                                  
            08-21 15:13:33 [ERROR] nonebot | Running matcher <Matcher from coser, type=messa
            ge, priority=5, temp=False> failed.                                             
            Traceback (most recent call last):                                              
              File "bot.py", line 21, in <module>                                           
                nonebot.run()                                                               
              File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 227, i
            n run 
            ……                                     
      ```

- 是否可复现： 是 
- 环境：
  - ubuntu（群晖Docker-Compose）
  - go-cqhttp v1.0.0-beta6
  - zhenxun_bot v0.0.3.4

- 含泪问：这种报错如何解决？

**Comment by HibiKier** [comment]
API挂了，已经找到新API，下次更新
