### ISSUE TITLE
COSER无法使用

### ISSUE THREAD

**Issue by RandomEnch** [HibiKier/zhenxun_bot#32]
08-21 17:09:03 [INFO] nonebot | Matcher <Matcher from coser, type=message, priority=5, temp=False> running complete
08-21 17:09:03 [ERROR] nonebot | Running matcher <Matcher from coser, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\10484\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\10484\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\10484\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers\deploy.py", line 23, in run_bot
    nonebot.run()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\10484\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "plugins\coser\__init__.py", line 77, in _
    await coser.send(image(img_url))
  File ".\utils\message_builder.py", line 39, in image
    if file.exists():
  File "c:\users\10484\appdata\local\programs\python\python39\lib\pathlib.py", line 1407, in exists
    self.stat()
  File "c:\users\10484\appdata\local\programs\python\python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'E:\\BOTS\\NoneBot\\resources\\img\\<html>\r\n<head><title>404 Not Found<\\title><\\head>\r\n<body>\r\n<center><h1>404 Not Found<\\h1><\\center>\r\n<hr><center>nginx<\\center>\r\n<\\body>\r\n<\\html>\r\n.jpg'

貌似是API出问题了？

**Comment by HibiKier** [comment]
API挂了，已经找到新API，下次更新

**Comment by RandomEnch** [comment]
问一下，为什么本地色图多了之后，更新的时候会出现"错误 <class 'FileExistsError'>: [WinError 183] 当文件已存在时，无法创建该文件。"的问题从而导致后面的色图都无法更新

**Comment by HibiKier** [comment]
如果这个错误是通过真寻发送给你的，是不会因为单张图片更新失败导致后面的图无法更新的，可以删除该张图片重新更新，如果是在命令行中直接报错未被捕获，可以说一下是第几行的报错嘛？

**Comment by RandomEnch** [comment]
应该是第一种情况,反正我把色图数据全删了重来了就好了
