### ISSUE TITLE
之前可以运行，然后关了再运行就出现这个错误了怎么办

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#334]
Traceback (most recent call last):
  File "F:\bot\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
  File "F:\bot\services\__init__.py", line 1, in <module>
    from .db_context import *
  File "F:\bot\services\db_context.py", line 4, in <module>
    from configs.config import bind, sql_name, user, password, address, port, database
  File "F:\bot\configs\config.py", line 24, in <module>
    Config = ConfigsManager(Path() / "data" / "configs" / "plugins2config.yaml")
  File "F:\bot\configs\utils\__init__.py", line 26, in __init__
    self._simple_data = _yaml.load(f)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\main.py", line 434, in load
    return constructor.get_single_data()
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\composer.py", line 113, in compose_node
    if self.parser.check_event(AliasEvent):
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\parser.py", line 146, in check_event
    self.current_event = self.state()
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\parser.py", line 633, in parse_block_mapping_value
    if not self.scanner.check_token(KeyToken):
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\scanner.py", line 1794, in check_token
    while self.need_more_tokens():
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\scanner.py", line 211, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\loser\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-8cBdUBmx-py3.9\lib\site-packages\ruamel\yaml\scanner.py", line 360, in stale_possible_simple_keys
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "configs\config.yaml", line 180, column 3
could not find expected ':'
  in "configs\config.yaml", line 181, column 1

**Comment by HibiKier** [comment]
你配置文件写错了，如果你不知道哪里错了，可以删除config.yaml重新生成，会生成你上一次正确保存的文件
