### ISSUE TITLE
请问修改端口的位置在哪里？

### ISSUE THREAD

**Issue by Fordzd** [HibiKier/zhenxun_bot#337]
日志如下：

```
05-19 05:30:55 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/01/08/75276545/1c4dd7692a34154dca818014931903d2_3268659946357391207.png
05-19 05:30:55 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/07/23/75379475/e5d774d916a14823b9a4b991a625b79b_3494668997173108660.png
05-19 05:30:55 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/03/29/75276545/1fdbc4d33f65a52704f119fe6ec323c3_3602860793126457274.png
05-19 05:30:56 [INFO] uvicorn | Application startup complete.
05-19 05:30:56 [ERROR] uvicorn | [Errno 98] error while attempting to bind on address ('127.0.0.1', 8080): address already in use
05-19 05:30:56 [INFO] uvicorn | Waiting for application shutdown.
05-19 05:30:56 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2020/12/02/75276545/de716a733d9691a3145581bc6f4bea54_126299787285554341.png 成功.. Path：/home/zhenxun_bot/resources/image/genshin/genshin_icon/66.png
05-19 05:30:56 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2020/11/10/75276545/c8bc224c24b8b9036b50f3d44f48b308_6549675881226177642.png 成功.. Path：/home/zhenxun_bot/resources/image/genshin/genshin_icon/68.png
05-19 05:30:56 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2020/12/02/75276545/de716a733d9691a3145581bc6f4bea54_126299787285554341.png
05-19 05:30:56 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2020/11/10/75276545/c8bc224c24b8b9036b50f3d44f48b308_6549675881226177642.png
05-19 05:30:56 [INFO] uvicorn | Application shutdown complete.
/usr/local/lib/python3.8/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/utils/network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

我观察到一句：

`05-19 05:30:56 [ERROR] uvicorn | [Errno 98] error while attempting to bind on address ('127.0.0.1', 8080): address already in use`

8080端口我搭了一个网站，可能因此导致启动失败了。请问一下修改端口的位置在哪里？

**Comment by HibiKier** [comment]
env dev

**Comment by Fordzd** [comment]
> env dev

Duplicate of #谢谢，目前已成功运行。因为偷懒用了一键脚本，找死也没找到藏在这里。
