### ISSUE TITLE
签到时报错

### ISSUE THREAD

**Issue by ardsgfcrtjhj** [HibiKier/zhenxun_bot#356]
05-19 02:31:00 [ERROR] nonebot | Running matcher <Matcher from plugins.sign_in, type=message, priority=5, temp=False> failed.
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 31, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1114, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 102, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 81, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 143, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 172, in _receive_event
    data = await self._network_stream.read(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 33, in read
    return b""
  File "/usr/local/python3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NUwrpPNM-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

**Comment by HibiKier** [comment]
看着是网络问题，签到一直这样？还是说其他功能也会有这个问题？

**Comment by ardsgfcrtjhj** [comment]
> 看着是网络问题，签到一直这样？还是说其他功能也会有这个问题？

大部分签到可以成功，少数情况会报这个错

**Comment by ardsgfcrtjhj** [comment]
> 看着是网络问题，签到一直这样？还是说其他功能也会有这个问题？

只有签到会偶尔出现这个情况，其他功能还没出现过

**Comment by HibiKier** [comment]
签到本身没有网络请求操作，大概是nb2联系gocq的时候

**Comment by ardsgfcrtjhj** [comment]
> 签到本身没有网络请求操作，大概是nb2联系gocq的时候

感谢大佬，貌似没问题了，最近几天没再出现过这个签到报错
