### ISSUE TITLE
alapi token填写位置

### ISSUE THREAD

**Issue by TiAmoJIA** [HibiKier/zhenxun_bot#361]
尝试在alapi的__init__和_dataresources_中的config填写，替换ALAPI_TOKEN，但都不管用,发起指令后一直返回101状态码，请问有大佬可以解答一下吗

**Comment by LEorEu** [comment]
configs/config.yaml

**Comment by FSYMAHCC** [comment]
> configs/config.yaml
> 
> 倾诉/指认，山姆

你好 我尝试仅在configs/config.yaml的ALAPI_TOKEN添加后运行bot.py开始闪退
err_log出现额外的报错信息
05-19 21:39:41 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\test\robot\python39\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\test\robot\python39\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\test\robot\python39\lib\site-packages\starlette\routing.py", line 600, in startup
    handler()
  File "C:\test\robot\zhenxun_bot-main\basic_plugins\init_plugin_config\__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "C:\test\robot\zhenxun_bot-main\basic_plugins\init_plugin_config\init_plugins_config.py", line 99, in init_plugins_config
    if _data.get(plugin) and k in _data[plugin].keys():
AttributeError: 'str' object has no attribute 'keys'

05-19 21:39:41 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by TiAmoJIA** [comment]
> 

会不会是python版本问题或者依赖没完全装好

**Comment by MingxuanGame** [comment]
试着删掉配置文件重新生成

**Comment by Sakuracio** [comment]
请注意 YAML 文件的格式规范 冒号的后面应该有一个空格
