### ISSUE TITLE
pip安装插件所需module后重启出现KeyError

### ISSUE THREAD

**Issue by c1amd0wn** [HibiKier/zhenxun_bot#410]
return self.timezone.normalize(next_fire_time)
05-20 12:37:45 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-20 12:37:45 [INFO] basic_plugins | 已成功加载 76 个非限制插件.
05-20 12:37:45 [INFO] utils | 已成功加载 5 个Cd限制.
05-20 12:37:45 [INFO] utils | 已成功加载 20 个Block限制.
05-20 12:37:45 [INFO] utils | 已成功加载 1 个Count限制.
05-20 12:37:46 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/kuan/.cache/pypoetry/virtualenvs/zhenxun-bot-G1sOCejO-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/home/kuan/.cache/pypoetry/virtualenvs/zhenxun-bot-G1sOCejO-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/home/kuan/.cache/pypoetry/virtualenvs/zhenxun-bot-G1sOCejO-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 600, in startup
    handler()
  File "/home/kuan/zhenxun_bot-main/basic_plugins/init_plugin_config/__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "/home/kuan/zhenxun_bot-main/basic_plugins/init_plugin_config/init_plugins_config.py", line 67, in init_plugins_config
    help_=plugin_configs[key]["help"],
KeyError: 'help'

05-20 12:37:46 [ERROR] uvicorn | Application startup failed. Exiting.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/kuan/.cache/pypoetry/virtualenvs/zhenxun-bot-G1sOCejO-py3.8/lib/python3.8/site-packages/bilibili_api/utils/network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by HibiKier** [comment]
你把help插件删了吗？

**Comment by c1amd0wn** [comment]
> 你把help插件删了吗？

没有
![image](https://user-images.githubusercontent.com/76038337/169453680-cac90503-fe9a-48df-8b5a-cf5314f36fb9.png)

**Comment by HibiKier** [comment]
你把data/configs删了重启试试

**Comment by c1amd0wn** [comment]
> 你把data/configs删了重启试试

好了,谢谢大佬orz
