### ISSUE TITLE
bilibili_Sub报错和bilireq

### ISSUE THREAD

**Issue by Su-Dream** [HibiKier/zhenxun_bot#412]
尝试过使用poetry add bilireq和pip install bilireq
启动仍然报这两个

`05-20 13:02:54 [ERROR] nonebot | Failed to import "bilibili_sub"
Traceback (most recent call last):

  File "C:\wwwroot\106.12.134.24\zhenxun_bot-0.1.5.3\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
    │       └ <function load_plugins at 0x0000029718EC4A60>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-i9xW0ubs-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-i9xW0ubs-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x0000029718EBF820>
           └ <nonebot.plugin.manager.PluginManager object at 0x000002971A4596D0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-i9xW0ubs-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-i9xW0ubs-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x0000029718EBF700>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x000002971A4596D0>
                  │    │           │         └ 'bilibili_sub'
                  │    │           └ 'bilibili_sub'
                  │    └ <function PluginManager.load_plugin at 0x0000029718EBF790>
                  └ <nonebot.plugin.manager.PluginManager object at 0x000002971A4596D0>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-i9xW0ubs-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x0000029715B7EF70>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.bilibili_sub'
           │          └ <function _gcd_import at 0x0000029715A61310>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-i9xW0ubs-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'plugins.bilibili_sub' from 'C:\\wwwroot\\106.12.134.24\\zhenxun_bot-0.1.5.3\\plugins\\bilibili_sub\\__init__.py'>

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\wwwroot\106.12.134.24\zhenxun_bot-0.1.5.3\plugins\bilibili_sub\__init__.py", line 4, in <module>
    from .data_source import (

  File "C:\wwwroot\106.12.134.24\zhenxun_bot-0.1.5.3\plugins\bilibili_sub\data_source.py", line 2, in <module>
    from bilireq.exceptions import ResponseCodeError

ModuleNotFoundError: No module named 'bilireq'
`

**Comment by HibiKier** [comment]
删除
![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png)
重新poetry install

**Comment by Su-Dream** [comment]
> 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install

好的，我试试

**Comment by MarmotSun** [comment]
> 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install

大佬，我刪了那个文件重新poetry install了还是这样
![image](https://user-images.githubusercontent.com/73126692/169501327-0e741500-e936-47c7-a27c-da0952bfca92.png)

**Comment by Su-Dream** [comment]
> 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install

 虽然但是，我删除之后poetry install 卡在准备环境变量了
有出现两行命令然后一直不动

**Comment by MarmotSun** [comment]
> > 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install
> 
> 虽然但是，我删除之后poetry install 卡在准备环境变量了 有出现两行命令然后一直不动

我也是有两行= =，但是我还是能够启动bot

**Comment by Sakuracio** [comment]
> > 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install
> 
> 虽然但是，我删除之后poetry install 卡在准备环境变量了 有出现两行命令然后一直不动

如果有计时，该过程可能超过15分钟

**Comment by Su-Dream** [comment]
> > > 删除 ![图片](https://user-images.githubusercontent.com/45528451/169455619-7f5e20ea-02ca-4736-9a2a-e5412513befd.png) 重新poetry install
> > 
> > 
> > 虽然但是，我删除之后poetry install 卡在准备环境变量了 有出现两行命令然后一直不动
> 
> 如果有计时，该过程可能超过15分钟

 没有进度条以及预计时间

**Comment by HibiKier** [comment]
已更新最新pyproject.toml
