### ISSUE TITLE
好像是环境问题

### ISSUE THREAD

**Issue by JMFANS** [HibiKier/zhenxun_bot#42]
每条错误都含有这条
’libGL.so.1: cannot open shared object file: No such file or directory‘

’09-08 09:34:17 [ERROR] nonebot | Failed to import "custom_welcome_message"
Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    nonebot.load_plugins("plugins/admin_bot_manage")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "plugins/admin_bot_manage/custom_welcome_message.py", line 5, in <module>
    from .data_source import custom_group_welcome
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "plugins/admin_bot_manage/data_source.py", line 13, in <module>
    from utils.image_utils import CreateImg
  File "/bot/zhenxun_bot-0.0.4.4/utils/image_utils.py", line 8, in <module>
    import cv2
  File "/usr/local/python3/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory‘

**Comment by HibiKier** [comment]
apt install libgl1-mesa-glx

**Comment by JMFANS** [comment]
感谢，发现安装opencv-python-headless替换opencv-python也可以解决

**Comment by JMFANS** [comment]
另外想问下您的系统环境是Ubuntu吗，还是windows？

**Comment by HibiKier** [comment]
Ubuntu

**Comment by JMFANS** [comment]
谢谢
