### ISSUE TITLE
按照大家说的解决方式做了还是这样

### ISSUE THREAD

**Issue by NMDwhy66154** [HibiKier/zhenxun_bot#420]
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from services.db_context import init, disconnect
  File "/home/zhenxun_bot/services/__init__.py", line 1, in <module>
    from .db_context import *
  File "/home/zhenxun_bot/services/db_context.py", line 4, in <module>
    from configs.config import bind, sql_name, user, password, address, port, database
  File "/home/zhenxun_bot/configs/config.py", line 3, in <module>
    from .utils import ConfigsManager
  File "/home/zhenxun_bot/configs/utils/__init__.py", line 3, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'

**Comment by MingxuanGame** [comment]
```bash
pip install ruamel_yaml
```

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169520372-cf8f29d5-7b60-44ed-9674-9c57d0f7d768.png)
