### ISSUE TITLE
启动后报错自动关闭

### ISSUE THREAD

**Issue by Tamamoimoto** [HibiKier/zhenxun_bot#43]
09-08 15:49:49 [INFO] nonebot | 自动更新城市列表完成.....
09-08 15:49:55 [INFO] nonebot | 成功获取赛马娘当前up信息...当前up池: 8月30日新角色追加 & 8月30日新角色追加
09-08 15:49:55 [ERROR] uvicorn | Traceback (most recent call last):
  File "/mnt/disk01/www/Python-3.8.6/lib/python3.8/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/mnt/disk01/www/Python-3.8.6/lib/python3.8/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/mnt/disk01/www/Python-3.8.6/lib/python3.8/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "plugins/draw_card/async_update_game_info.py", line 62, in async_update_game
    await func()
  File "plugins/draw_card/azur_handle.py", line 48, in init_azur_data
    ALL_CHAR = init_game_pool('azur', azur_dict, AzurChar)
  File "plugins/draw_card/init_card_pool.py", line 69, in init_game_pool
    if '可以建造' not in data[key]['获取途径']:
KeyError: '获取途径'

09-08 15:49:55 [ERROR] uvicorn | Application startup failed. Exiting.

这该怎么搞呢。

**Comment by HibiKier** [comment]
删除 data/draw_card/azur.json 重新更新

**Comment by Tamamoimoto** [comment]
> 删除 data/draw_card/azur.json 重新更新
删除完更新后又报错了，然后我把 azur_handle.py 里的48行里 
ALL_CHAR = init_game_pool('azur', azur_dict, AzurChar)
改成了
ALL_CHAR = init_game_pool('azur.json', azur_dict, AzurChar)
他就正常了_(:з」∠)_

**Comment by Tamamoimoto** [comment]
> 删除 data/draw_card/azur.json 重新更新

删除完更新后又报错了，然后我把 azur_handle.py 里的48行里
ALL_CHAR = init_game_pool('azur', azur_dict, AzurChar)
改成了
ALL_CHAR = init_game_pool('azur.json', azur_dict, AzurChar)
他就正常了_(:з」∠)_

**Comment by HibiKier** [comment]
啊，你这换了就等于就等于没有加载碧蓝的卡池了

**Comment by Tamamoimoto** [comment]
> 啊，你这换了就等于就等于没有加载碧蓝的卡池了

emmm，那我改回去重启试试。

**Comment by HibiKier** [comment]
[azur.zip](https://github.com/HibiKier/zhenxun_bot/files/7127519/azur.zip)

**Comment by Tamamoimoto** [comment]
> [azur.zip](https://github.com/HibiKier/zhenxun_bot/files/7127519/azur.zip)

谢谢大佬，这个放进去就正常启动了。
