### ISSUE TITLE
原神资源查询插件问题

### ISSUE THREAD

**Issue by MWTJC** [HibiKier/zhenxun_bot#450]
+ 环境：WinServer2019（管理员）（参考安装文档）及Hyperv下的UbuntuServer20.04（root）（一键部署），均存在此问题。
+ 描述（以win为例）：
* 原神资源列表（BOT端）：
````
05-20 21:51:58 [SUCCESS] nonebot | ONEBOT V11 00000000 | [message.group.normal]: Message 00000000000 from 000000000@[群:00000000] "原神资源查询甜甜花"
05-20 21:51:58 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-20 21:51:58 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-20 21:51:58 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-20 21:51:58 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-20 21:51:58 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-20 21:51:58 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-20 21:51:58 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-20 21:51:58 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-20 21:51:58 [INFO] nonebot | Event will be handled by <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False>
05-20 21:52:04 [INFO] nonebot | Matcher <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False> running complete
05-20 21:52:04 [ERROR] nonebot | Running matcher <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 30, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\py28\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\py28\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\py28\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\py28\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\py28\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\__init__.py", line 58, in _
    resource = await query_resource(resource_name)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\query_resource.py", line 56, in query_resource
    rand = await asyncio.get_event_loop().run_in_executor(
  File "c:\py28\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\map.py", line 121, in generate_resource_icon_in_map
    self.map.save(f"{IMAGE_PATH}/temp/genshin_map_{rand}.png")
  File "F:\BOT\zhenxun_bot\utils\image_utils.py", line 438, in save
    self.markImg.save(path)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\PIL\Image.py", line 2209, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'resources\\image/temp/genshin_map_8600.png'
````
* 原神资源列表（gocq端）：
````
[2022-05-20 21:51:58] [INFO]: 收到群 ？ 内 ？ 的消息: 原神资源查询甜甜花 (1855385497)
[2022-05-20 21:51:58] [INFO]: 发送群 ？ 的消息: [{"type":  ... (-140526045)  # 此处bot回复“正在生成位置”，遂无后文
````
+ 经Everything搜索，全盘没有以“genshin_map_”开头的文件，但部署过程中其下载资源步骤并没报错。
* 以上。

**Comment by MingxuanGame** [comment]
你试着重启一下

每次重启都会更新资源的

**Comment by MWTJC** [comment]
> 你试着重启一下
> 
> 每次重启都会更新资源的

+ 重启了WinServer和Bot套件，在bot的启动回馈里确实看到了“更新原神资源类型成功”的提示，
```
05-20 22:38:02 [SUCCESS] nonebot | NoneBot is initializing...
05-20 22:38:03 [INFO] nonebot | Current Env: dev
05-20 22:38:05 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\apscheduler\util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
05-20 22:38:17 [SUCCESS] nonebot | Succeeded to import "clear_data"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "exec_sql"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "reload_setting"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
05-20 22:38:18 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "manager_group"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "super_cmd"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "use"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "buy"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "gold"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "my_props"
05-20 22:38:19 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "shop"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "ban"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "super_help"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "group_handle"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "hooks"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "rule"
05-20 22:38:20 [SUCCESS] nonebot | Succeeded to import "timing_task"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "admin_config"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "switch_rule"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "broadcast"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "admin_help"
05-20 22:38:21 [SUCCESS] nonebot | Succeeded to import "chat_message"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "chat_history"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "help"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "nickname"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "invite_manager"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "update_info"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "apscheduler"
05-20 22:38:22 [SUCCESS] nonebot | Succeeded to import "scripts"
05-20 22:38:23 [SUCCESS] nonebot | Succeeded to import "mute"
05-20 22:38:23 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
05-20 22:38:23 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
05-20 22:38:23 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "pix"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "pix_update"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "update_setu"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "send_setu"
05-20 22:38:24 [SUCCESS] nonebot | Succeeded to import "send_setu_"
05-20 22:38:25 [SUCCESS] nonebot | Succeeded to import "open_cases"
05-20 22:38:25 [SUCCESS] nonebot | Succeeded to import "white2black_image"
05-20 22:38:25 [SUCCESS] nonebot | Succeeded to import "update_picture"
05-20 22:38:25 [SUCCESS] nonebot | Succeeded to import "check"
05-20 22:38:26 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
05-20 22:38:26 [SUCCESS] nonebot | Succeeded to import "russian"
05-20 22:38:28 [SUCCESS] nonebot | Succeeded to import "draw_card"
05-20 22:38:28 [SUCCESS] nonebot | Succeeded to import "luxun"
05-20 22:38:28 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
05-20 22:38:28 [SUCCESS] nonebot | Succeeded to import "search_anime"
05-20 22:38:29 [SUCCESS] nonebot | Succeeded to import "material_remind"
05-20 22:38:29 [SUCCESS] nonebot | Succeeded to import "almanac"
05-20 22:38:29 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
05-20 22:38:30 [SUCCESS] nonebot | Succeeded to import "bind"
05-20 22:38:30 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-20 22:38:30 [SUCCESS] nonebot | Succeeded to import "resin_remind"
05-20 22:38:30 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
05-20 22:38:31 [SUCCESS] nonebot | Succeeded to import "query_role"
05-20 22:38:31 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
05-20 22:38:31 [SUCCESS] nonebot | Succeeded to import "query_user"
05-20 22:38:31 [SUCCESS] nonebot | Succeeded to import "genshin"
05-20 22:38:32 [SUCCESS] nonebot | Succeeded to import "weather"
05-20 22:38:32 [SUCCESS] nonebot | Succeeded to import "send_image"
05-20 22:38:32 [SUCCESS] nonebot | Succeeded to import "move_image"
05-20 22:38:32 [SUCCESS] nonebot | Succeeded to import "delete_image"
05-20 22:38:32 [SUCCESS] nonebot | Succeeded to import "upload_image"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "image_management"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "coser"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "yiqing"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "search_image"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "pid_search"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "about"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "translate"
05-20 22:38:33 [SUCCESS] nonebot | Succeeded to import "epic"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "web_ui"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "my_info"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "poetry"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "comments_163"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "jitang"
05-20 22:38:34 [SUCCESS] nonebot | Succeeded to import "cover"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "wbtop"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "alapi"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "ai"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "music"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "quotations"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "fudu"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "dialogue"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "one_friend"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "bt"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "message_handle"
05-20 22:38:35 [SUCCESS] nonebot | Succeeded to import "model"
05-20 22:38:36 [SUCCESS] nonebot | Succeeded to import "word_hanlde"
05-20 22:38:36 [SUCCESS] nonebot | Succeeded to import "word_bank"
05-20 22:38:36 [SUCCESS] nonebot | Succeeded to import "what_anime"
05-20 22:38:36 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
05-20 22:38:36 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
05-20 22:38:37 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
05-20 22:38:37 [SUCCESS] nonebot | Succeeded to import "sign_in"
05-20 22:38:37 [SUCCESS] nonebot | Succeeded to import "black_word"
05-20 22:38:37 [SUCCESS] nonebot | Succeeded to import "fake_msg"
05-20 22:38:37 [SUCCESS] nonebot | Succeeded to import "roll"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "statistics"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "withdraw"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "poke"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "aconfig"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-20 22:38:38 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-20 22:38:39 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-20 22:38:39 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-20 22:38:39 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-20 22:38:39 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-20 22:38:39 [SUCCESS] nonebot | Running NoneBot...
05-20 22:38:39 [INFO] uvicorn | Started server process [2372]
05-20 22:38:39 [INFO] uvicorn | Waiting for application startup.
05-20 22:38:40 [INFO] services | Database loaded successfully!
C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\apscheduler\triggers\cron\__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\apscheduler\triggers\cron\__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\apscheduler\triggers\interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
05-20 22:38:40 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-20 22:38:41 [INFO] basic_plugins | 已成功加载 59 个非限制插件.
05-20 22:38:41 [INFO] utils | 已成功加载 5 个Cd限制.
05-20 22:38:41 [INFO] utils | 已成功加载 12 个Block限制.
05-20 22:38:42 [INFO] utils | 已成功加载 1 个Count限制.
05-20 22:38:55 [INFO] basic_plugins | 初始化数据完成...
05-20 22:38:55 [WARNING] plugins | prts_up_char 解析出错
05-20 22:38:56 [INFO] plugins | 更新原神资源类型成功...
05-20 22:38:56 [INFO] uvicorn | Application startup complete.
05-20 22:38:56 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
```
+ 但仍然，现象依旧，
```
05-20 22:40:02 [SUCCESS] nonebot | ONEBOT V11 000000000 | [message.group.normal]: Message -2137485643 from 00000@[群:0000000000] "原神资源查询甜甜花"
05-20 22:40:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-20 22:40:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-20 22:40:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-20 22:40:02 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-20 22:40:02 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-20 22:40:02 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-20 22:40:02 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-20 22:40:02 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-20 22:40:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False>
05-20 22:40:09 [INFO] nonebot | Matcher <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False> running complete
05-20 22:40:09 [ERROR] nonebot | Running matcher <Matcher from plugins.genshin.query_resource_points, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 30, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\py28\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\py28\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\py28\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\py28\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\py28\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\__init__.py", line 58, in _
    resource = await query_resource(resource_name)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\query_resource.py", line 56, in query_resource
    rand = await asyncio.get_event_loop().run_in_executor(
  File "c:\py28\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\BOT\zhenxun_bot\plugins\genshin\query_resource_points\map.py", line 121, in generate_resource_icon_in_map
    self.map.save(f"{IMAGE_PATH}/temp/genshin_map_{rand}.png")
  File "F:\BOT\zhenxun_bot\utils\image_utils.py", line 438, in save
    self.markImg.save(path)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Xe1Mga6A-py3.8\lib\site-packages\PIL\Image.py", line 2209, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'resources\\image/temp/genshin_map_8075.png'
```
+ 只不过提示找不到的图片名字有所变化.
* 以上。

**Comment by MingxuanGame** [comment]
试着在 `resources/image` 目录下新建 `temp` 文件夹

**Comment by MWTJC** [comment]
> 试着在 `resources/image` 目录下新建 `temp` 文件夹

+ 感谢，新建文件夹之后已经解决了
