### ISSUE TITLE
使用sign_in和shop时出现报错

### ISSUE THREAD

**Issue by RandomEnch** [HibiKier/zhenxun_bot#46]
09-10 19:13:01 [ERROR] nonebot | Failed to import "sign_in"
Traceback (most recent call last):
  File "c:\users\10484\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\10484\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\10484\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers\deploy.py", line 17, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\bot.py", line 12, in <module>
    nonebot.load_plugins("plugins")
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "c:\users\10484\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "plugins\sign_in\__init__.py", line 1, in <module>
    from .group_user_checkin import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "plugins\sign_in\group_user_checkin.py", line 2, in <module>
    from models.sign_group_user import SignGroupUser
  File ".\models\sign_group_user.py", line 6, in <module>
    class SignGroupUser(db.Model):
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\gino\declarative.py", line 117, in __new__
    rv.__table__ = getattr(rv, "_init_table")(rv)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\gino\crud.py", line 437, in _init_table
    rv = Model._init_table(sub_cls)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\gino\declarative.py", line 320, in _init_table
    rv = sa.Table(table_name, sub_cls.__metadata__, *args, **table_kw)
  File "<string>", line 2, in __new__
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\util\deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "c:\users\10484\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\sql\schema.py", line 540, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'sign_group_users' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

**Comment by HibiKier** [comment]
你的models目录下是否有sigin_group_user.py 文件？

**Comment by RandomEnch** [comment]
有

**Comment by HibiKier** [comment]
删除它

**Comment by RandomEnch** [comment]
好的
