### ISSUE TITLE
请问webui 最后启动服务的时候报错Command "serve" not found

### ISSUE THREAD

**Issue by milkasir** [HibiKier/zhenxun_bot#481]
![image](https://user-images.githubusercontent.com/92635464/169640104-02d18764-e0f2-41ce-8369-b2eaca9de79e.png)

**Comment by Su-Dream** [comment]
cd zhenxun_bot_webui
yarn serve

**Comment by milkasir** [comment]
> 

root@VM-12-8-ubuntu:~/zhenxun_bot_webui# yarn serve
yarn run v1.22.18
$ vue-cli-service serve
/bin/sh: vue-cli-service: command not found
error Command failed with exit code 127.

重装了一次vue也是这样，是我nodejs有问题吗

**Comment by milkasir** [comment]
补充问题，bot本体启动的时候词云总是加载失败，但是在文档里我也没查到word cloud，这个是干什么的，需要修复吗并且怎么修复呢

05-21 15:38:21 [SUCCESS] nonebot | Succeeded to import "word_bank"
05-21 15:38:21 [SUCCESS] nonebot | Succeeded to import "translate"
05-21 15:38:22 [ERROR] nonebot | Failed to import "word_clouds"
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhenxun_bot/plugins/word_clouds/__init__.py", line 11, in <module>
    from .data_source import draw_word_cloud, get_list_msg
  File "/home/zhenxun_bot/plugins/word_clouds/data_source.py", line 10, in <module>
    from wordcloud import WordCloud, ImageColorGenerator

**Comment by MingxuanGame** [comment]
`pip install wordcloud`

**Comment by milkasir** [comment]
已解决，感谢
