### ISSUE TITLE
mute插件加载失败，版本为2022/5/21更新的最新版本

### ISSUE THREAD

**Issue by yixue99** [HibiKier/zhenxun_bot#482]
05-21 15:16:22 [ERROR] nonebot | Failed to import "mute"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\zhenxun_bot\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\zhenxun_bot\plugins\mute.py", line 59, in <module>
    def get_data() -> Dict[Any]:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 275, in inner
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\typing.py", line 833, in __getitem__
    _check_generic(self, params, self._nparams)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\typing_extensions.py", line 113, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "weather"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "charity"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "zg_shenhe_qz"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "check_word"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_admin"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "zg_shenhe"
05-21 15:16:22 [SUCCESS] nonebot | Succeeded to import "shorturl"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "sq_sign"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "jianzhi"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "zg99"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "crm_sj"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "crm_zz"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "crm_ds"
05-21 15:16:23 [SUCCESS] nonebot | Succeeded to import "jtui"
05-21 15:16:25 [SUCCESS] nonebot | Succeeded to import "petpet"
05-21 15:16:25 [SUCCESS] my_plugins | 读取词库位于 C:\Users\Administrator\Desktop\bot\zhenxun_bot\data\word_bank\bank.json
05-21 15:16:25 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_word_bank2"
05-21 15:16:27 [SUCCESS] nonebot | Succeeded to import "mockingbird"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_morning"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-21 15:16:28 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-21 15:16:28 [SUCCESS] nonebot | Running NoneBot...
05-21 15:16:28 [INFO] uvicorn | Started server process [1644]
05-21 15:16:28 [INFO] uvicorn | Waiting for application startup.
05-21 15:16:28 [INFO] services | Database loaded successfully!
05-21 15:16:28 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-21 15:16:28 [WARNING] basic_plugins | 插件 mute 加载失败...，插件控制未加载.
05-21 15:16:28 [WARNING] basic_plugins | 插件 mute 加载失败...，插件控制未加载.
05-21 15:16:29 [INFO] basic_plugins | 已成功加载 49 个非限制插件.
05-21 15:16:29 [INFO] utils | 已成功加载 4 个Cd限制.
05-21 15:16:29 [INFO] utils | 已成功加载 4 个Block限制.
05-21 15:16:29 [INFO] utils | 已成功加载 4 个Count限制.
05-21 15:16:29 [WARNING] basic_plugins | 插件 mute 加载失败...，资源控制未加载...
05-21 15:16:29 [INFO] basic_plugins | 初始化数据完成...

**Comment by MingxuanGame** [comment]
Fix in https://github.com/HibiKier/zhenxun_bot/commit/08a0670a5a45a618f815bd7829e9e8e3b3514cf8

**Comment by yixue99** [comment]
已解决

**Comment by yixue99** [comment]
设置刷屏禁言时长 次数等参数时，数据未成功写入group_mute_data.json

**Comment by yixue99** [comment]
> 在 [08a0670](https://github.com/HibiKier/zhenxun_bot/commit/08a0670a5a45a618f815bd7829e9e8e3b3514cf8) 中修复

设置刷屏禁言时长 次数等参数时，数据未成功写入group_mute_data.json

**Comment by HibiKier** [comment]
> > 在 [08a0670](https://github.com/HibiKier/zhenxun_bot/commit/08a0670a5a45a618f815bd7829e9e8e3b3514cf8) 中修复
> 
> 设置刷屏禁言时长 次数等参数时，数据未成功写入group_mute_data.json

已修

**Comment by yixue99** [comment]
> > > 在 [08a0670](https://github.com/HibiKier/zhenxun_bot/commit/08a0670a5a45a618f815bd7829e9e8e3b3514cf8) 中修复
> > 
> > 
> > 设置刷屏禁言时长 次数等参数时，数据未成功写入group_mute_data.json
> 
> 已修
完美
