### ISSUE TITLE
能帮看一下这个日志显示的错误要怎么解决嘛

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#564]
05-23 17:35:07 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\bot\basic_plugins\init_plugin_config\__init__.py", line 47, in _
    init_none_plugin_count_manager()
  File "D:\bot\basic_plugins\init_plugin_config\init_none_plugin_count_manager.py", line 29, in init_none_plugin_count_manager
    if none_plugin_count_manager.check(module):
  File "D:\bot\utils\manager\none_plugin_count_manager.py", line 45, in check
    return self._data.keys() > self._max_count
TypeError: '>' not supported between instances of 'dict_keys' and 'int'

05-23 17:35:07 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by yajiwa** [comment]
请确认D:\bot\utils\manager\none_plugin_count_manager.py这个文件是否为最新版

**Comment by 80546033** [comment]
> 请确认D:\bot\utils\manager\none_plugin_count_manager.py这个文件是否为最新版

我重新解压出来这个文件试了一下错误变成这样了
05-23 18:35:42 [ERROR] uvicorn | Application startup failed. Exiting.
05-23 18:35:42 [ERROR] apscheduler | Error running job c056327f52694302a90441281e5e3e89
Traceback (most recent call last):

  File "bot.py", line 20, in <module>
    nonebot.run()
    │       └ <function run at 0x00000000035EB700>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-azjZwigI-py3.8\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x00000000022E0310>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x000000000494ACA0>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-azjZwigI-py3.8\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x000000000494AE50>
    └ <uvicorn.server.Server object at 0x0000000010AC4790>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000000000494AEE0>
           │       │   └ <uvicorn.server.Server object at 0x0000000010AC4790>
           │       └ <function run at 0x0000000002F3F3A0>
           └ <module 'asyncio' from 'c:\\program files\\python38\\lib\\asyncio\\__init__.py'>

  File "c:\program files\python38\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
    │                 └ <ProactorEventLoop running=True closed=False debug=False>
    └ <function _cancel_all_tasks at 0x000000000302EF70>

  File "c:\program files\python38\lib\asyncio\runners.py", line 62, in _cancel_all_tasks
    loop.run_until_complete(
    │    └ <function BaseEventLoop.run_until_complete at 0x0000000003031820>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\program files\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000000003079E50>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\program files\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "c:\program files\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000000003033310>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\program files\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000000002FE00D0>
    └ <Handle AsyncIOExecutor._do_submit_job.<locals>.callback(<Task cancell...se_py3.py:13>>) at C:\Users\Administrator\AppData\Lo...

  File "c:\program files\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle AsyncIOExecutor._do_submit_job.<locals>.callback(<Task cancell...se_py3.py:13>>) at C:\Users\Administrator\AppData\Lo...
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle AsyncIOExecutor._do_submit_job.<locals>.callback(<Task cancell...se_py3.py:13>>) at C:\Users\Administrator\AppData\Lo...
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle AsyncIOExecutor._do_submit_job.<locals>.callback(<Task cancell...se_py3.py:13>>) at C:\Users\Administrator\AppData\Lo...

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\apscheduler\executors\asyncio.py", line 42, in callback
    events = f.result()
             │ └ <method 'result' of '_asyncio.Task' objects>
             └ <Task cancelled name='Task-33' coro=<run_coroutine_job() done, defined at C:\Users\Administrator\AppData\Local\pypoetry\Cache...

asyncio.exceptions.CancelledError

**Comment by HibiKier** [comment]
日志不全
