### ISSUE TITLE
大佬们帮看看这个错误怎么解决

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#567]
05-23 18:59:31 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\bot\basic_plugins\init_plugin_config\__init__.py", line 47, in _
    init_none_plugin_count_manager()
  File "D:\bot\basic_plugins\init_plugin_config\init_none_plugin_count_manager.py", line 29, in init_none_plugin_count_manager
    if none_plugin_count_manager.check(module):
  File "D:\bot\utils\manager\none_plugin_count_manager.py", line 45, in check
    return self._data.keys() > self._max_count
TypeError: '>' not supported between instances of 'dict_keys' and 'int'

05-23 18:59:31 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by MingxuanGame** [comment]
Dumplice of #564

**Comment by 80546033** [comment]
> #564的副本[](https://github.com/HibiKier/zhenxun_bot/issues/564)

重装解决了，谢谢
