### ISSUE TITLE
插件好像突然全炸了

### ISSUE THREAD

**Issue by w-victorique** [HibiKier/zhenxun_bot#717]
Uuntu 20.04 
Python 3.8.10
真寻 0.1.5.8
泪目，垃圾服务器使用mockingbird语音插件内存炸了。重启之后插件好像全不行了？
`ModuleNotFoundError: No module named 'rich'
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "genshin"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "my_info"
05-30 15:37:35 [ERROR] nonebot | Failed to import "epic"
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/zhenxun_bot/plugins/epic/__init__.py", line 6, in <module>
    from .data_source import get_epic_free
  File "/home/ubuntu/zhenxun_bot/plugins/epic/data_source.py", line 5, in <module>
    from utils.http_utils import AsyncHttpx
  File "/home/ubuntu/zhenxun_bot/utils/http_utils.py", line 17, in <module>
    import rich
ModuleNotFoundError: No module named 'rich'
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-30 15:37:35 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-30 15:37:35 [SUCCESS] nonebot | Running NoneBot...
05-30 15:37:35 [INFO] uvicorn | Started server process [1645]
05-30 15:37:35 [INFO] uvicorn | Waiting for application startup.
05-30 15:37:35 [INFO] services | Database loaded successfully!
/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
05-30 15:37:35 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：translate 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：wbtop 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：search_anime 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：pix 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：search_image 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：yiqing 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：music 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：word_clouds 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：search_buff_skin_price 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：quotations 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：nbnhhsh 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：send_setu 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：pid_search 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：weather 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：open_cases 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：what_anime 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：update_picture 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：query_resource_points 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：query_role 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：query_memo 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：genshin_sign 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：resin_remind 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：epic 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：bilibili_sub 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：bt 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：white2black_image 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：pixiv_rank_search 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：pix_show_info 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：black_word 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：ai 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：almanac 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：ddcheck 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：mockingbird 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：crazy_thursday 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：ApexLegends-QQ-Robot 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [WARNING] basic_plugins | 配置文件 模块：logo 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 15:37:35 [INFO] basic_plugins | 已成功加载 61 个非限制插件.
05-30 15:37:35 [INFO] utils | 已成功加载 5 个Cd限制.
05-30 15:37:35 [INFO] utils | 已成功加载 15 个Block限制.
05-30 15:37:35 [INFO] utils | 已成功加载 1 个Count限制.
05-30 15:37:36 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/ubuntu/zhenxun_bot/basic_plugins/init_plugin_config/init_plugins_config.py", line 86, in init_plugins_config
    admin_manager.set_admin_level(k, v)
  File "/home/ubuntu/zhenxun_bot/utils/manager/admin_manager.py", line 31, in set_admin_level
    self._data[plugin]["level"] = level
KeyError: 'custom_welcome_message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 614, in startup
    handler()
  File "/home/ubuntu/zhenxun_bot/basic_plugins/init_plugin_config/__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "/home/ubuntu/zhenxun_bot/basic_plugins/init_plugin_config/init_plugins_config.py", line 88, in init_plugins_config
    raise KeyError(f"{e} ****** 请检查是否有插件加载失败 ******")
KeyError: "'custom_welcome_message' ****** 请检查是否有插件加载失败 
![1234](https://user-images.githubusercontent.com/30694574/170942417-37719dee-aec2-4b01-b682-c31c467986d6.png)
******"

05-30 15:37:36 [ERROR] uvicorn | Application startup failed. Exiting.
`

**Comment by w-victorique** [comment]
没事了poetry install重新来一遍。不过其他插件没得重新安装
