### ISSUE TITLE
运行bot.py时，指定的网络名不再可用，数据库连接错误

### ISSUE THREAD

**Issue by THNEden** [HibiKier/zhenxun_bot#720]
### 错误截图

不方便截图，采用代码块复现
```
05-30 19:33:30 [ERROR] uvicorn | Traceback (most recent call last):
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Bot\zhenxun_bot\services\db_context.py", line 16, in init
    await db.set_bind(i_bind)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\pool.py", line 413, in _async__init__
    await self._initialize()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\pool.py", line 441, in _initialize
    await first_ch.connect()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\asyncpg\compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-tQXzWbWr-py3.9\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Bot\zhenxun_bot\services\db_context.py", line 20, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.ConnectionDoesNotExistError'>: connection was closed in the middle of operation

05-30 19:33:30 [ERROR] uvicorn | Application startup failed. Exiting.
```

### 日志

已经通过```vs_buildtools```安装最新的C++插件与Windows 10 SDK

---
在运行```bot.py```前已成功执行
```
pip3 install poetry
poetry install
poetry shell
```
---
已经安装```Postgresql数据库```，并配置了```pgAdmin4```，以下为照片（不方便截图）

![IMG_20220530_195258](https://user-images.githubusercontent.com/87106832/170990817-9bf4f410-9413-4975-abe6-6eb40fab216d.jpg)
![IMG_20220530_200847](https://user-images.githubusercontent.com/87106832/170990827-ef1bbf07-babb-43f6-8377-94afacc370a6.jpg)
---
已经为```pg_hba.conf```下添加
```
host    all             all             0.0.0.0/0               md5
```

在最新的```Postgresql```中，```listen_addresses: '*' ```一栏不再被注释，故不作修改

---
已经配置```\configs\config.py```，内容如下
```
# 数据库（必要）
# 如果填写了bind就不需要再填写后面的字段了#）
# 示例："bind": "postgresql://user:password@127.0.0.1:5432/database"
bind: str = ""  # 数据库连接链接
sql_name: str = "postgresql"
user: str = "Bot"  # 数据用户名
password: str = "2462949771"  # 数据库密码
address: str = "127.0.0.1"  # 数据库地址
port: str = "5432"  # 数据库端口
database: str = "Bot"  # 数据库名称

# 代理，例如 "http://127.0.0.1:7890"
SYSTEM_PROXY: Optional[str] = None  # 全局代理
```
---
### 错误说明

已经在大奶机上成功部署了bot，奈何没有条件持续挂机（电费好贵），想起手上还有一块老古董Surface3，就拿去折腾了，使用WIFI连接网络，刷了精简版的win10，直接使用了在大奶机上的bot文件和其他所有配置，最后在运行```python bot.py```时死活打不开，故求助

**Comment by HibiKier** [comment]
看着似乎没什么问题，吧user换成postgres试试

**Comment by THNEden** [comment]
> 看着似乎没什么问题，吧user换成postgres试试

问题解决，非常感谢
