### ISSUE TITLE
KeyError: 'win_rate'报错

### ISSUE THREAD

**Issue by KONOHADA** [HibiKier/zhenxun_bot#729]
### 错误截图
05-31 19:48:47 [SUCCESS] nonebot | ONEBOT V11 3024699417 | [message.private.friend]: Message -2075663785 from 599050359 "ys"
05-31 19:48:47 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-31 19:48:47 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-31 19:48:47 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-31 19:48:48 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-31 19:48:48 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-31 19:48:48 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-31 19:48:48 [INFO] nonebot | Event will be handled by <Matcher from plugins.genshin.query_user.query_role, type=message, priority=5, temp=False>
05-31 19:48:48 [INFO] nonebot | Matcher <Matcher from plugins.genshin.query_user.query_role, type=message, priority=5, temp=False> running complete
05-31 19:48:48 [ERROR] nonebot | Running matcher <Matcher from plugins.genshin.query_user.query_role, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BY5vr5RN-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\Desktop\qq\BOT\zhenxun_bot\plugins\genshin\query_user\query_role\__init__.py", line 50, in _
    data = await query_role_data(event.user_id, uid, mys_id, nickname)
  File "C:\Users\Administrator\Desktop\qq\BOT\zhenxun_bot\plugins\genshin\query_user\query_role\data_source.py", line 26, in query_role_data
    return await get_image(user_id, uid, server_id, mys_id, nickname)
  File "C:\Users\Administrator\Desktop\qq\BOT\zhenxun_bot\plugins\genshin\query_user\query_role\data_source.py", line 49, in get_image
    char_data_list, role_data, world_data_dict, home_data_list = parsed_data(data)
  File "C:\Users\Administrator\Desktop\qq\BOT\zhenxun_bot\plugins\genshin\query_user\query_role\data_source.py", line 185, in parsed_data
    "win_rate": data["stats"]["win_rate"],
KeyError: 'win_rate'

### 错误说明

更新之后对真寻发送ys就会这样报错

**Comment by HibiKier** [comment]
更新最新的
