### ISSUE TITLE
求助，指定的网络名不再可用，数据库连接错误

### ISSUE THREAD

**Issue by pamss** [HibiKier/zhenxun_bot#730]
### 错误截图

05-31 19:43:00 [ERROR] uvicorn | Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\qq robot\zhenxun_bot-main\services\db_context.py", line 16, in init
    await db.set_bind(i_bind)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 413, in _async__init__
    await self._initialize()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 441, in _initialize
    await first_ch.connect()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\qq robot\zhenxun_bot-main\services\db_context.py", line 20, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.ConnectionDoesNotExistError'>: connection was closed in the middle of operation

05-31 19:43:00 [ERROR] uvicorn | Application startup failed. Exiting.

### 日志截图

05-31 19:56:12 [ERROR] uvicorn | Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\qq robot\zhenxun_bot-main\services\db_context.py", line 16, in init
    await db.set_bind(i_bind)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 413, in _async__init__
    await self._initialize()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 441, in _initialize
    await first_ch.connect()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\asyncpg\compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-A3v1UyDD-py3.8\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\qq robot\zhenxun_bot-main\services\db_context.py", line 20, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.ConnectionDoesNotExistError'>: connection was closed in the middle of operation

05-31 19:56:12 [ERROR] uvicorn | Application startup failed. Exiting.

### 错误说明

![uTools_1653998414278](https://user-images.githubusercontent.com/106173477/171168532-41b31fc9-62dd-4e85-96e2-b1650f3b7886.png)
![uTools_1653998344143](https://user-images.githubusercontent.com/106173477/171168539-bce46f1a-621b-4b58-bc1b-52b68b49a0d3.png)

**Comment by THNEden** [comment]
#720 ，问题类似，已经得到解决，看看对你有没有帮助

**Comment by pamss** [comment]
> #720 ，问题类似，已经得到解决，看看对你有没有帮助

谢谢，问题解决了，但是又出现了新的问题（悲）
 [ERROR] uvicorn | [Errno 10013] error while attempting to bind on address ('127.0.0.1', 5432): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
