### ISSUE TITLE
关于签到插件提示http错误的求助

### ISSUE THREAD

**Issue by SpideyUU** [HibiKier/zhenxun_bot#766]
系统版本：Windows 11 21H2
真寻版本：0.1.5.8
错误日志：
06-04 17:27:40 [SUCCESS] nonebot | ONEBOT V11 3432348028 | [message.group.normal]: Message -2120250421 from 1131700913@[群:818040589] "签到"
06-04 17:27:40 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
06-04 17:27:40 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
06-04 17:27:40 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
06-04 17:27:40 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
06-04 17:27:40 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
06-04 17:27:40 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
06-04 17:27:40 [INFO] nonebot | Event will be handled by <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
06-04 17:27:40 [INFO] plugins | (USER 1131700913, GROUP 818040589) CHECKED IN successfully. score: 0.88 (+0.88).获取金币：87
06-04 17:27:40 [INFO] nonebot | Matcher <Matcher from plugins.sign_in, type=message, priority=5, temp=False> running complete
06-04 17:27:40 [ERROR] nonebot | Running matcher <Matcher from plugins.sign_in, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\http11.py", line 102, in handle_async_request
    raise exc
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\http11.py", line 81, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\http11.py", line 143, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_async\http11.py", line 172, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\backends\asyncio.py", line 33, in read
    return b""
  File "D:\ProgramData\Anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\plugins\sign_in\__init__.py", line 93, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\plugins\sign_in\group_user_checkin.py", line 39, in group_user_check_in
    return await _handle_check_in(nickname, user_qq, group, present)  # ok
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\plugins\sign_in\group_user_checkin.py", line 97, in _handle_check_in
    return await get_card(user, nickname, impression_added, gold, gift)
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\plugins\sign_in\utils.py", line 76, in get_card
    ava = BytesIO(await get_user_avatar(user_id))
  File "E:\QQ_bot\zhenxun_bot\zhenxun_bot\utils\utils.py", line 340, in get_user_avatar
    return (await client.get(url)).content
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1729, in get
    return await self.request(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\ProgramData\Anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\wushe\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-f7d-BDSF-py3.9\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
错误截图：
![image](https://user-images.githubusercontent.com/34191381/171993824-22704b23-adcf-4f83-93eb-0aa16be1f8f8.png)
![image](https://user-images.githubusercontent.com/34191381/171993850-e5e389ba-02e8-42a7-a38d-73749349e92b.png)
![image](https://user-images.githubusercontent.com/34191381/171993875-d1167b17-cdd8-42b8-89c0-6035d4706225.png)

该错误发生在更换网络后，有线网络改用为无线网络，【暂时不可逆】，查看错误日志时发现是网络名称有变化。
请问如何在不改回原有网络的情况下，修复此错误呢？

**Comment by HibiKier** [comment]
建议百度
