### ISSUE TITLE
更新v0.1.5.9报错

### ISSUE THREAD

**Issue by PokiAcg** [HibiKier/zhenxun_bot#768]
### 错误截图
![image](https://user-images.githubusercontent.com/105905387/172061486-2853547a-1312-4500-9d29-f9a352c107a4.png)

[img]
06-06 00:49:22 [ERROR] apscheduler | Job "_remind (trigger: date[2022-06-06 00:49:22 CST], next run at: 2022-06-06 00:49:22 CST)" raised an exception
Traceback (most recent call last):

  File "C:\zhenxun_bot-0.1.5.6\bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x0000006C5A1F60D0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-OCSshLtQ-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-OCSshLtQ-py3.9\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x0000006C577D9280>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-OCSshLtQ-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x0000006C5B54B310>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-OCSshLtQ-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-OCSshLtQ-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x0000006C5B54B4C0>
    └ <uvicorn.server.Server object at 0x0000006C6BAE4970>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-OCSshLtQ-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x0000006C5B54B550>
           │       │   └ <uvicorn.server.Server object at 0x0000006C6BAE4970>
           │       └ <function run at 0x0000006C59C40DC0>
           └ <module 'asyncio' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib\\asyncio\\__init__.py'>

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x0000006C6AF1FA40>
           │    └ <function BaseEventLoop.run_until_complete at 0x0000006C59C3E0D0>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000006C59C9B280>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000006C59C40B80>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000006C59BE0CA0>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000006C70120CD0>(<Future finished result=None>)>

  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000006C70120CD0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000006C70120CD0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000006C70120CD0>(<Future finished result=None>)>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-OCSshLtQ-py3.9\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=genshin_resin_remind_104738087_392834728 name=_remind)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=genshin_resin_remind_104738087_392834728 name=_remind)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=genshin_resin_remind_104738087_392834728 name=_remind)>

  File "C:\zhenxun_bot-0.1.5.6\plugins\genshin\query_user\resin_remind\init_task.py", line 199, in _remind
    scheduler.add_job(
    │         └ <function BaseScheduler.add_job at 0x0000006C5B9271F0>
    └ <apscheduler.schedulers.asyncio.AsyncIOScheduler object at 0x0000006C5B840D00>

TypeError: add_job() got multiple values for argument 'args'

[img]

更新报错

**Comment by McElaga** [comment]
报错内容是原神插件问题,和更新没关系.这个原神的报错已经在新版本中解决.你的机器应该正在下载更新文件
