### ISSUE TITLE
正在检查 Chromium 更新后就报错了...

### ISSUE THREAD

**Issue by ID114514** [HibiKier/zhenxun_bot#89]
File "C:\Program Files\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by ID114514** [comment]
貌似没有自动生成 各种配置文件

**Comment by HibiKier** [comment]
报错可以给的详细一点？如果系统时win的话可以暂时先把utils/browser.py中的install注释掉

**Comment by ID114514** [comment]
> 报错可以给的详细一点？如果系统时win的话可以暂时先把utils/browser.py中的install注释掉

我尝试重装了py并且从头开始部署，这次虽然能反向到CQ，不过没有自动生成配置文件 以及使用命令没反应

**Comment by ID114514** [comment]
> 报错可以给的详细一点？如果系统时win的话可以暂时先把utils/browser.py中的install注释掉

插件控制失败*N

12-11 16:09:51 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Program Files\lib\site-packages\starlette\routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "C:\Program Files\lib\site-packages\starlette\routing.py", line 481, in default_lifespan
    await self.startup()
  File "C:\Program Files\lib\site-packages\starlette\routing.py", line 518, in startup
    handler()
  File "basic_plugins\init_plugin_config\__init__.py", line 45, in _
    init_plugins_data(DATA_PATH)
  File "basic_plugins\init_plugin_config\init_plugins_data.py", line 82, in init_plugins_data
    plugins_manager.save()
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\utils\manager\data_class.py", line 54, in save
    json.dump(self._data, f, ensure_ascii=False, indent=4)
TypeError: <module 'nonebot.plugin.manager._internal.ef43799e922fd6cac50e4b16ef9b5f74.one_friend' from 'plugins\\one_friend\\__init__.py'> is not JSON serializable

12-11 16:09:51 [ERROR] uvicorn | Application startup failed. Exiting.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "C:\Program Files\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by HibiKier** [comment]
nonebot2什么版本，插件加载有无报错？

**Comment by ID114514** [comment]
> nonebot2什么版本，插件加载有无报错？

呃，这个issue的问题解决了，应该是依赖的问题......多谢大佬抽空指导
我先运行看看有没有其他问题，再向大佬请教
