### ISSUE TITLE
装了nonebot_plugin_htmlrender后真寻就启动不了了

### ISSUE THREAD

**Issue by xharaut** [HibiKier/zhenxun_bot#932]
系统版本：Ubuntu 20.04
真寻版本：0.1.6.1
装了nonebot-plugin-htmlrender后真寻就启动不了了

[INFO] nonebot_plugin_htmlrender | 正在安装 firefox
[INFO] nonebot_plugin_htmlrender | 正在安装依赖
Installing dependencies...
Hit:1 http://mirrors.aliyun.com/ubuntu focal InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu focal-security InRelease
Hit:3 http://mirrors.aliyun.com/ubuntu focal-updates InRelease                 
Hit:4 http://mirrors.aliyun.com/ubuntu focal-backports InRelease               
Ign:5 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu focal InRelease    
Err:6 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu focal Release
  404  Not Found [IP: 185.125.190.52 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/fcitx-team/nightly/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Failed to install browser dependencies
Error: Installation process exited with code: 100
07-19 20:20:02 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 29, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 41, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-qDYi5r -juggler-pipe -silent
<launched> pid=5281
[pid=5281][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
[pid=5281] <process did exit: exitCode=1, signal=null>
[pid=5281] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-qDYi5r -juggler-pipe -silent
<launched> pid=5281
[pid=5281][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
[pid=5281] <process did exit: exitCode=1, signal=null>
[pid=5281] starting temporary directories cleanup
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 45, in get_browser
    return _browser or await init(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 32, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 41, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-7sObhr -juggler-pipe -silent
<launched> pid=5779
[pid=5779][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-7sObhr -juggler-pipe -silent
<launched> pid=5779
[pid=5779][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
============================================================

[ERROR] uvicorn | Application startup failed. Exiting.

**Comment by HibiKier** [comment]
？别人插件发送错误你来我这提issues？
