### ISSUE TITLE
自行添加插件失败

### ISSUE THREAD

**Issue by THNEden** [HibiKier/zhenxun_bot#938]
### 错误截图
因设备原因不便截图，现提供错误日志
```
07-20 21:33:40 [ERROR] nonebot | Failed to import "nonebot_plugin_imageutils"
Traceback (most recent call last):
  File "C:\Bot\zhenxun_bot-0.1.6.1\bot.py", line 15, in <module>
    nonebot.load_plugins("new_plugins")
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_petpet\__init__.py", line 11, in <module>
    require("nonebot_plugin_imageutils")
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\load.py", line 161, in require
    plugin = manager.load_plugin(name)
> File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\__init__.py", line 1, in <module>
    from .build_image import BuildImage
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\build_image.py", line 14, in <module>
    from .text2image import Text2Image
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\text2image.py", line 2, in <module>
    from bbcode import Parser
ModuleNotFoundError: No module named 'bbcode'
07-20 21:33:40 [ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "C:\Bot\zhenxun_bot-0.1.6.1\bot.py", line 15, in <module>
    nonebot.load_plugins("new_plugins")
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_petpet\__init__.py", line 11, in <module>
    require("nonebot_plugin_imageutils")
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\load.py", line 165, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_imageutils"!
07-20 21:33:41 [ERROR] nonebot | Failed to import "nonebot_plugin_imageutils"
Traceback (most recent call last):
  File "C:\Bot\zhenxun_bot-0.1.6.1\bot.py", line 15, in <module>
    nonebot.load_plugins("new_plugins")
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\thneden\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\THNEden\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EDDJpxAf-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\__init__.py", line 1, in <module>
    from .build_image import BuildImage
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\build_image.py", line 14, in <module>
    from .text2image import Text2Image
  File "C:\Bot\zhenxun_bot-0.1.6.1\new_plugins\nonebot_plugin_imageutils\text2image.py", line 2, in <module>
    from bbcode import Parser
ModuleNotFoundError: No module named 'bbcode'
```

### 错误说明

[[直接将插件拖进自建插件文件夹启动后出现上述报错，在查询[#435](https://github.com/HibiKier/zhenxun_bot/issues/435)后尝试使用poetry安装```bbcode```时，一直显示```Resolving dependencies...```且没有出现进度条，不知是否正常，特此求助

**Comment by HibiKier** [comment]
正常
