### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by misaka10843** [HibiKier/zhenxun_bot#94]
先附个err log
```python
12-17 16:11:28 [INFO] nonebot | Running NoneBot...
12-17 16:11:28 [INFO] uvicorn | Started server process [158706]
12-17 16:11:28 [INFO] uvicorn | Waiting for application startup.
12-17 16:11:28 [ERROR] uvicorn | Traceback (most recent call last):
  File "/www/wwwroot/QQ-cqhttp/QQ-Bot/zhenxun_bot/services/db_context.py", line 16, in init
    await db.set_bind(i_bind)
  File "/usr/local/lib/python3.8/dist-packages/gino/api.py", line 413, in set_bind
    bind = make_url(bind)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/www/wwwroot/QQ-cqhttp/QQ-Bot/zhenxun_bot/services/db_context.py", line 20, in init
    raise Exception(f'数据库连接错误.... e: {e}')
Exception: 数据库连接错误.... e: invalid literal for int() with base 10: ''

12-17 16:11:28 [ERROR] uvicorn | Application startup failed. Exiting.
```
其中，sql为[教程中](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_postgresql.html)所安装的Postgresql，并且按照教程新建的数据库，并且按照教程修改了配置文件重启了sql，但是还是弹出此错误

请问如何才能修复此问题？

---

```
系统：Ubuntu 20.04TLS
python：3.8.10
```

**Comment by HibiKier** [comment]
你确定填写了configs/config.py中的数据库配置？

**Comment by misaka10843** [comment]
填写了，我试试修改下数据库的端口吧qwq

**Comment by misaka10843** [comment]
> Exception: 数据库连接错误.... e: invalid literal for int() with base 10: ''，无法将空字符串转为int类型，你填了的话也不会是空字符串

刚刚查了一下，发现可能是因为ssh连接时网络问题，所以vim没有保存上去qwq
（最后还是通过ftp下载了文件夹才发现的qwq）
