### ISSUE TITLE
Ubuntu 真寻机器人 数据库连接错误问题

### ISSUE THREAD

**Issue by Focuskenny** [HibiKier/zhenxun_bot#942]
系统版本：Ubuntu 20.04
真寻版本：0.1.6.1

错误截图

![bandicam 2022-07-22 20-31-08-488](https://user-images.githubusercontent.com/93857726/180439763-06e24c74-f0d3-4dfc-a81b-566ac182a391.jpg)
![bandicam 2022-07-22 20-31-01-049](https://user-images.githubusercontent.com/93857726/180439775-34dcb86b-53b7-4808-8777-5052c0fa3f80.jpg)
![bandicam 2022-07-22 20-30-52-149](https://user-images.githubusercontent.com/93857726/180439789-ba423c0c-2667-4718-833c-cb6167536204.jpg)

日志：
[ERROR] uvicorn | Traceback (most recent call last):
  File "/home/ubuntu/zhenxun_bot/services/db_context.py", line 19, in init
    await db.set_bind(i_bind)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/gino/api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/gino/strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/gino/dialects/asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 413, in _async__init__
    await self._initialize()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 441, in _initialize
    await first_ch.connect()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 790, in _connect_addr
    return await __connect_addr(params_retry, timeout, False, *args)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "uname"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/ubuntu/zhenxun_bot/services/db_context.py", line 23, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.InvalidPasswordError'>: password authentication failed for user "uname"

07-22 12:28:54 [ERROR] uvicorn | Application startup failed. Exiting.

![bandicam 2022-07-22 16-30-19-335](https://user-images.githubusercontent.com/93857726/180400620-434ddd0f-1df9-4fa1-b502-b5dbf6901cd7.jpg)
![bandicam 2022-07-22 16-30-42-896](https://user-images.githubusercontent.com/93857726/180400630-09b3bf24-7764-498f-a9ad-c6155b71582a.jpg)
![bandicam 2022-07-22 16-33-02-172](https://user-images.githubusercontent.com/93857726/180400637-622f885d-0135-48dd-88a3-577d0be1b5e5.jpg)

错误说明：

Ubuntu系统（AWS的免费方案EC2服务器），按教程走，在连线gocqhttp没问题，但在真寻机器人开上去后就跳出这问题了
不晓得是Postgresql数据库没整好还是有啥设定出错，请求各位解答，麻烦了，非常感谢

**Comment by Focuskenny** [comment]
已自行解决了

**Comment by RMSCA** [comment]
请问是怎么解决的呢

**Comment by romanticfire** [comment]
你好，我也遇到了一样的问题，请问是怎样解决的呢？
我尝试更改数据库的密码和用户名，但是失败了
如果你可以告诉我如何解决我将不胜感激
![image](https://user-images.githubusercontent.com/60844769/215107940-976e1408-5af5-4f7d-a7b3-5f5deeeb92a6.png)
