### ISSUE TITLE
开箱插件报错

### ISSUE THREAD

**Issue by CallTrane** [HibiKier/zhenxun_bot#966]
### 错误截图

[img]

### 日志截图

08-04 01:39:12 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-04 01:39:12 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-04 01:39:12 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
08-04 01:39:12 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
08-04 01:39:12 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
08-04 01:39:12 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
08-04 01:39:12 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
08-04 01:39:12 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
08-04 01:39:12 [INFO] nonebot | Event will be handled by <Matcher from plugins.open_cases, type=message, priority=5, temp=False>
08-04 01:39:18 [INFO] nonebot | Matcher <Matcher from plugins.open_cases, type=message, priority=5, temp=False> running complete
08-04 01:39:18 [ERROR] nonebot | Running matcher <Matcher from plugins.open_cases, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "/usr/local/bin/zhenxun_bot-0.1.6.2/bot.py", line 21, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/bin/zhenxun_bot-0.1.6.2/plugins/open_cases/__init__.py", line 164, in _
    await open_shilian.finish("必须要是数字切不要超过30啊笨蛋！中文也可！", at_sender=True)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 464, in finish
    await cls.send(message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 131, in _call_api
    return handle_api_result(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-QwxtWYWx-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/utils.py", line 47, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=2, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

### 错误说明

回复十连开箱报错，机器人没反应

**Comment by HibiKier** [comment]
请参考 go-cqhttp 端输出
